Repository memgraph/memgraph, pull requests merged in 2022-06, with the labels that each got.

#405 [master < T0876-MG] Add an uncatchable kill method to the python MemgraphInstanceRunner
  tests/e2e/memgraph.py
Labels: tests

#379 [master < T0833-MG] Add replica state to SHOW REPLICAS
  src/query/frontend/ast/ast.lcp
  src/query/interpreter.cpp
  src/query/interpreter.hpp
  src/storage/v2/storage.cpp
  tests/e2e/CMakeLists.txt
  tests/e2e/interactive_mg_runner.py
  tests/e2e/memgraph.py
  tests/e2e/replication/CMakeLists.txt
  tests/e2e/replication/show.py
  tests/e2e/replication/show_while_creating_invalid_state.py
  tests/e2e/replication/workloads.yaml
  tests/e2e/runner.py
Labels: enhancement

#412 [master < T0880-MG] Add information on show replicas to express how uptodate is replica
  src/query/interpreter.cpp
  src/query/interpreter.hpp
  src/storage/v2/replication/replication_client.cpp
  src/storage/v2/replication/replication_client.hpp
  src/storage/v2/replication/replication_server.cpp
  src/storage/v2/replication/replication_server.hpp
  src/storage/v2/replication/rpc.lcp
  src/storage/v2/storage.cpp
  src/storage/v2/storage.hpp
  tests/e2e/replication/show.py
  tests/e2e/replication/show_while_creating_invalid_state.py
  tests/e2e/replication/workloads.yaml
Labels: enhancement

#414 [master < T0882-MG] Registering a replica with timeout 0 should not be allowed
  src/query/interpreter.cpp
  src/storage/v2/replication/replication_client.cpp
  tests/e2e/interactive_mg_runner.py
  tests/e2e/replication/show_while_creating_invalid_state.py
  tests/e2e/replication/workloads.yaml
  tests/e2e/runner.py
Labels: bug
