Repository memgraph/memgraph, pull requests merged in 2022-10, with the labels that each got.

#582 [master < T1076-MG] Bug fix for EdgeType and Label getters in pymodule
  src/query/procedure/mg_procedure_impl.cpp
Labels: bug

#580 [:pineapple: < MG-T1071] Implement create expand request in query
  src/coordinator/shard_map.hpp
  src/glue/v2/communication.cpp
  src/memgraph.cpp
  src/query/v2/accessors.cpp
  src/query/v2/accessors.hpp
  src/query/v2/context.hpp
  src/query/v2/interpreter.cpp
  src/query/v2/interpreter.hpp
  src/query/v2/plan/operator.cpp
  src/query/v2/plan/vertex_count_cache.hpp
  src/query/v2/requests.hpp
  src/query/v2/shard_request_manager.hpp
  src/storage/v3/bindings/db_accessor.hpp
  src/storage/v3/shard_rsm.cpp
  src/storage/v3/shard_rsm.hpp
  tests/simulation/shard_request_manager.cpp
  tests/simulation/shard_rsm.cpp
Labels: :pineapple:

#567 [master <] Add libcxx to the toolchain
  environment/toolchain/.gitignore
  environment/toolchain/v4.sh
Labels: infrastructure

#594 [:pineapple: < MG-T1082] Add OrderBy in ScanAll
  src/query/v2/requests.hpp
  src/storage/v3/CMakeLists.txt
  src/storage/v3/expr.cpp
  src/storage/v3/expr.hpp
  src/storage/v3/request_helper.cpp
  src/storage/v3/request_helper.hpp
  src/storage/v3/shard_rsm.cpp
  tests/simulation/shard_rsm.cpp
  tools/gdb-plugins/pretty_printers.py
Labels: :pineapple:

#585 [🍍 <] Decouple interactive planning manual test
  tests/manual/CMakeLists.txt
  tests/manual/interactive/db_accessor.hpp
  tests/manual/interactive/plan.hpp
  tests/manual/interactive/planning.cpp
  tests/manual/interactive/planning.hpp
  tests/manual/interactive/readline.hpp
  tests/manual/interactive/timer.hpp
  tests/manual/query_execution_dummy.cpp
  tests/manual/query_planner.cpp
Labels: tech debt

#599 [master <] Add Fedora 36 as an OS
  environment/os/fedora-36.sh
Labels: infrastructure
