Repository memgraph/memgraph, pull requests merged in 2022-11, with the labels that each got.

#628 [:pineapple: < MG-T1138] Fix edge id allocator
  src/query/v2/context.hpp
  src/query/v2/interpreter.cpp
  src/query/v2/plan/operator.cpp
Labels: :pineapple:

#636 [< T298-MAGE] allShortest bugfix
  src/query/plan/operator.cpp
  tests/unit/interpreter.cpp
Labels: bug

#642 [master <] Remove tools/check-build-system
  tools/check-build-system
Labels: infrastructure

#638 [:pineapple: < MG-T1148] Fix expand one source vertex pk setting
  src/storage/v3/shard_rsm.cpp
  tests/e2e/distributed_queries/CMakeLists.txt
  tests/e2e/distributed_queries/common.py
  tests/e2e/distributed_queries/distributed_expand_one.py
  tests/e2e/distributed_queries/workloads.yaml
Labels: :pineapple:

#643 [master < MG-python-check] Add python check
  .github/workflows/daily_benchmark.yaml
  .github/workflows/diff.yaml
  .github/workflows/full_clang_tidy.yaml
  .github/workflows/package_all.yaml
  .github/workflows/release_centos8.yaml
  .github/workflows/release_debian10.yaml
  .github/workflows/release_docker.yaml
  .github/workflows/release_ubuntu2004.yaml
  .pre-commit-config.yaml
  config/generate.py
  init
  pyproject.toml
Labels: infrastructure

#648 [:pineapple: < MG-remove-unused-fies] Remove `storage.hpp` and `storage.cpp` files
  src/query/v2/db_accessor.hpp
  src/query/v2/interpreter.cpp
  src/storage/v3/CMakeLists.txt
  src/storage/v3/shard_rsm.cpp
  src/storage/v3/storage.cpp
  src/storage/v3/storage.hpp
  tests/unit/query_v2_query_plan_common.hpp
  tests/unit/query_v2_query_plan_create_set_remove_delete.cpp
  tests/unit/query_v2_query_plan_edge_cases.cpp
  tests/unit/query_v2_query_plan_v2_create_set_remove_delete.cpp
  tests/unit/result_stream_faker.hpp
  tests/unit/storage_v3_indices.cpp
  tests/unit/storage_v3_isolation_level.cpp
  tests/unit/storage_v3_schema.cpp
  tests/unit/storage_v3_test_utils.hpp
Labels: :pineapple:

#646 [:pineapple: < T1116-MG] Update/Delete vertex labels
  src/query/v2/requests.hpp
  src/storage/v3/request_helper.cpp
  src/storage/v3/request_helper.hpp
  src/storage/v3/shard_rsm.cpp
  src/storage/v3/shard_rsm.hpp
  src/utils/template_utils.hpp
  tests/simulation/shard_rsm.cpp
  tests/unit/CMakeLists.txt
  tests/unit/storage_v3_shard_rsm.cpp
Labels: :pineapple:

#611 [:pineapple: < T1083-MG] Add limit and OrderBy to ExpandOne
  src/query/v2/requests.hpp
  src/storage/v3/expr.cpp
  src/storage/v3/expr.hpp
  src/storage/v3/request_helper.cpp
  src/storage/v3/request_helper.hpp
  src/storage/v3/shard_rsm.cpp
  src/storage/v3/value_conversions.hpp
  tests/simulation/shard_rsm.cpp
Labels: :pineapple:

#649 [:pineapple: < MG-T0995] Implement top level error handling in storage
  src/common/errors.hpp
  src/expr/interpret/eval.hpp
  src/glue/v2/communication.cpp
  src/glue/v2/communication.hpp
  src/memgraph.cpp
  src/query/v2/bindings/eval.hpp
  src/query/v2/common.hpp
  src/query/v2/db_accessor.hpp
  src/query/v2/exceptions.hpp
  src/query/v2/plan/operator.cpp
  src/query/v2/requests.hpp
  src/query/v2/shard_request_manager.hpp
  src/storage/v3/bindings/db_accessor.hpp
  src/storage/v3/bindings/eval.hpp
  src/storage/v3/edge_accessor.cpp
  src/storage/v3/edge_accessor.hpp
  src/storage/v3/request_helper.cpp
  src/storage/v3/request_helper.hpp
  src/storage/v3/result.hpp
  src/storage/v3/schema_validator.cpp
  src/storage/v3/schema_validator.hpp
  src/storage/v3/shard.cpp
  src/storage/v3/shard.hpp
  src/storage/v3/shard_operation_result.hpp
  src/storage/v3/shard_rsm.cpp
  src/storage/v3/vertex_accessor.cpp
  src/storage/v3/vertex_accessor.hpp
  tests/simulation/shard_rsm.cpp
  tests/simulation/test_cluster.hpp
  tests/unit/high_density_shard_create_scan.cpp
  tests/unit/machine_manager.cpp
  tests/unit/storage_v3.cpp
  tests/unit/storage_v3_edge.cpp
  tests/unit/storage_v3_schema.cpp
  tests/unit/storage_v3_shard_rsm.cpp
  tests/unit/storage_v3_vertex_accessors.cpp
Labels: :pineapple:

#654 [E202-MG < T1164-MG] Add aggregation distinct
  src/query/frontend/ast/ast.lcp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/plan/operator.cpp
  src/query/plan/operator.lcp
  src/query/plan/pretty_print.cpp
  src/query/plan/rule_based_planner.cpp
  tests/mgbench/datasets.py
  tests/unit/plan_pretty_print.cpp
  tests/unit/query_common.hpp
  tests/unit/query_expression_evaluator.cpp
  tests/unit/query_plan.cpp
  tests/unit/query_plan_accumulate_aggregate.cpp
  tests/unit/query_plan_checker.hpp
  tests/unit/query_semantic.cpp
Labels: enhancement

#664 [:pineapple: < MG] Make implicit-fallthrough a compilation error
  CMakeLists.txt
  src/communication/bolt/v1/states/executing.hpp
  src/storage/v2/constraints.cpp
  src/storage/v3/request_helper.cpp
Labels: infrastructure

#566 [master < T0945DX] Add Neo4j client and mixed workload to mgbench
  src/communication/bolt/client.cpp
  tests/mgbench/README.md
  tests/mgbench/benchmark.py
  tests/mgbench/compare_results.py
  tests/mgbench/datasets.py
  tests/mgbench/graph_bench.py
  tests/mgbench/runners.py
Labels: infrastructure, tests

#644 [:pineapple: < T1159-MG] Add memgraph functions lib
  .github/workflows/diff.yaml
  .pre-commit-config.yaml
  src/CMakeLists.txt
  src/expr/CMakeLists.txt
  src/expr/interpret/eval.hpp
  src/functions/CMakeLists.txt
  src/functions/awesome_memgraph_functions.hpp
  src/query/v2/CMakeLists.txt
  src/query/v2/accessors.cpp
  src/query/v2/accessors.hpp
  src/query/v2/bindings/eval.hpp
  src/query/v2/conversions.hpp
  src/query/v2/frontend/ast/ast.lcp
  src/query/v2/interpret/awesome_memgraph_functions.cpp
  src/query/v2/plan/preprocess.cpp
  src/query/v2/shard_request_manager.hpp
  src/storage/v3/CMakeLists.txt
  src/storage/v3/bindings/ast/ast.lcp
  src/storage/v3/bindings/db_accessor.hpp
  src/storage/v3/conversions.hpp
  src/storage/v3/edge_accessor.cpp
  src/storage/v3/edge_accessor.hpp
  src/storage/v3/expr.cpp
  src/storage/v3/request_helper.cpp
  src/storage/v3/shard.cpp
  tests/e2e/distributed_queries/CMakeLists.txt
  tests/e2e/distributed_queries/awesome_memgraph_functions.py
  tests/e2e/distributed_queries/workloads.yaml
  tests/unit/CMakeLists.txt
  tests/unit/query_v2_expression_evaluator.cpp
  tests/unit/storage_v3_edge.cpp
Labels: :pineapple:

#675 [master < T1006-DX-update-readme] Update README with one new paragraph and link
  README.md
Labels: documentation
