Repository memgraph/memgraph, pull requests merged in 2022-12, with the labels that each got.

#660 [master < MG-update-mgconsole] Raise mgconsole version
  libs/setup.sh
Labels: infrastructure, v2.5

#652 [:pineapple: < T0919-MG] Implement GetProperties() on storage
  src/query/v2/requests.hpp
  src/storage/v3/request_helper.cpp
  src/storage/v3/request_helper.hpp
  src/storage/v3/shard_rsm.cpp
  tests/simulation/shard_rsm.cpp
Labels: :pineapple:

#666 [:pineapple: < T1172-MG] implement GetProperties on RequestRouter
  src/query/v2/request_router.hpp
  tests/simulation/CMakeLists.txt
  tests/simulation/common.hpp
  tests/simulation/request_router.cpp
  tests/unit/query_v2_expression_evaluator.cpp
Labels: :pineapple:

#665 [master < E202-MG] Add aggregation distinct (#654)
  src/query/frontend/ast/ast.lcp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/plan/operator.cpp
  src/query/plan/operator.lcp
  src/query/plan/pretty_print.cpp
  src/query/plan/rule_based_planner.cpp
  tests/mgbench/datasets.py
  tests/unit/plan_pretty_print.cpp
  tests/unit/query_common.hpp
  tests/unit/query_expression_evaluator.cpp
  tests/unit/query_plan.cpp
  tests/unit/query_plan_accumulate_aggregate.cpp
  tests/unit/query_plan_checker.hpp
  tests/unit/query_semantic.cpp
Labels: enhancement, v2.5

#676 [:pineapple: < MG-T1163] Impl of Multiframe and iterators
  jba.txt
  src/expr/interpret/frame.hpp
  src/query/v2/CMakeLists.txt
  src/query/v2/bindings/frame.hpp
  src/query/v2/interpreter.cpp
  src/query/v2/multiframe.cpp
  src/query/v2/multiframe.hpp
  src/query/v2/plan/operator.cpp
  src/query/v2/plan/operator.lcp
Labels: :pineapple:

#694 [:pineapple: < T1188-MG] Remove unused jba.txt
  jba.txt
Labels: :pineapple:

#695 [:pineapple: < T1163-MG] remove template from frame
  src/expr/interpret/eval.hpp
  src/expr/interpret/frame.hpp
  src/query/v2/bindings/frame.hpp
  src/query/v2/interpreter.cpp
  src/storage/v3/bindings/frame.hpp
Labels: :pineapple:

#688 Fix MAGE C++ API bugs
  include/_mgp.hpp
  include/mgp.hpp
  query_modules/example.cpp
  tests/unit/cpp_api.cpp
Labels: bug, tests, v2.5

#683 [E206-MG < T1184-MG] Init file before server starts and init data file after servers starts
  src/memgraph.cpp
  tests/e2e/configuration/default_config.py
  tests/integration/CMakeLists.txt
  tests/integration/flag_check/CMakeLists.txt
  tests/integration/flag_check/flag_check.cpp
  tests/integration/flag_check/runner.py
  tests/integration/flag_check/tester.cpp
Labels: enhancement, v2.5

#693 [master<051222]Add information about community to readme
  README.md
Labels: documentation

#681 [E206-MG < T1183-MG] Create user from env variables
  src/helpers.hpp
  src/memgraph.cpp
  tests/e2e/configuration/workloads.yaml
  tests/integration/CMakeLists.txt
  tests/integration/env_variable_check/CMakeLists.txt
  tests/integration/env_variable_check/runner.py
  tests/integration/env_variable_check/tester.cpp
Labels: enhancement, v2.5

#682 [master <- ] Add support for -h to show help in addition to --help
  src/memgraph.cpp
  tests/e2e/configuration/configuration_check.py
Labels: enhancement, v2.5

#697 [master < T474-FL] Fixed graph projection bug
  src/query/db_accessor.cpp
  src/query/db_accessor.hpp
Labels: bug, v2.5

#667 [master < T507-FL] EmptyResult operator
  src/query/plan/operator.cpp
  src/query/plan/operator.lcp
  src/query/plan/pretty_print.cpp
  src/query/plan/pretty_print.hpp
  src/query/plan/read_write_type_checker.cpp
  src/query/plan/read_write_type_checker.hpp
  src/query/plan/rewrite/index_lookup.hpp
  src/query/plan/rule_based_planner.hpp
  src/utils/event_counter.cpp
  tests/gql_behave/tests/memgraph_V1/features/update_clauses.feature
  tests/unit/interpreter.cpp
  tests/unit/query_plan.cpp
  tests/unit/query_plan_checker.hpp
Labels: bug, v2.5

#653 [master < T499-FL] Python submodules reloading
  src/query/procedure/module.cpp
  tests/e2e/CMakeLists.txt
  tests/e2e/configuration/default_config.py
  tests/e2e/python_query_modules_reloading/CMakeLists.txt
  tests/e2e/python_query_modules_reloading/common.py
  tests/e2e/python_query_modules_reloading/procedures/CMakeLists.txt
  tests/e2e/python_query_modules_reloading/procedures/mage/CMakeLists.txt
  tests/e2e/python_query_modules_reloading/procedures/mage/test_module/CMakeLists.txt
  tests/e2e/python_query_modules_reloading/procedures/mage/test_module/test_functions.py
  tests/e2e/python_query_modules_reloading/procedures/mage/test_module/test_functions_dir/CMakeLists.txt
  tests/e2e/python_query_modules_reloading/procedures/mage/test_module/test_functions_dir/test_subfunctions.py
  tests/e2e/python_query_modules_reloading/procedures/test_module.py
  tests/e2e/python_query_modules_reloading/test_reload_query_module.py
  tests/e2e/python_query_modules_reloading/workloads.yaml
Labels: bug, enhancement, v2.5

#700 [E206 < epic_branch_fix] Epic branch pr fix
  src/memgraph.cpp
  src/query/db_accessor.cpp
  src/query/db_accessor.hpp
  src/query/plan/operator.cpp
  src/query/plan/operator.lcp
  src/query/plan/pretty_print.cpp
  src/query/plan/pretty_print.hpp
  src/query/plan/read_write_type_checker.cpp
  src/query/plan/read_write_type_checker.hpp
  src/query/plan/rewrite/index_lookup.hpp
  src/query/plan/rule_based_planner.hpp
  src/query/procedure/module.cpp
  src/utils/event_counter.cpp
  tests/e2e/CMakeLists.txt
  tests/e2e/configuration/default_config.py
  tests/e2e/python_query_modules_reloading/CMakeLists.txt
  tests/e2e/python_query_modules_reloading/common.py
  tests/e2e/python_query_modules_reloading/procedures/CMakeLists.txt
  tests/e2e/python_query_modules_reloading/procedures/mage/CMakeLists.txt
  tests/e2e/python_query_modules_reloading/procedures/mage/test_module/CMakeLists.txt
  tests/e2e/python_query_modules_reloading/procedures/mage/test_module/test_functions.py
  tests/e2e/python_query_modules_reloading/procedures/mage/test_module/test_functions_dir/CMakeLists.txt
  tests/e2e/python_query_modules_reloading/procedures/mage/test_module/test_functions_dir/test_subfunctions.py
  tests/e2e/python_query_modules_reloading/procedures/test_module.py
  tests/e2e/python_query_modules_reloading/test_reload_query_module.py
  tests/e2e/python_query_modules_reloading/workloads.yaml
  tests/gql_behave/tests/memgraph_V1/features/update_clauses.feature
  tests/integration/env_variable_check/runner.py
  tests/unit/interpreter.cpp
  tests/unit/query_plan.cpp
  tests/unit/query_plan_checker.hpp
Labels: v2.5

#668 [:pineapple: < MG-T1173] Benchmark datastructures
  tests/benchmark/CMakeLists.txt
  tests/benchmark/data_structures_common.hpp
  tests/benchmark/data_structures_contains.cpp
  tests/benchmark/data_structures_find.cpp
  tests/benchmark/data_structures_insert.cpp
  tests/benchmark/data_structures_remove.cpp
  tests/benchmark/skip_list_common.hpp
  tools/plot/benchmark_datastructures.py
  tools/plot/benchmark_datastructures.sh
Labels: :pineapple:

#680 [:pineapple: < MG-T1185] Replace skip list
  src/storage/v3/CMakeLists.txt
  src/storage/v3/delta.hpp
  src/storage/v3/edge.hpp
  src/storage/v3/edge_accessor.hpp
  src/storage/v3/indices.cpp
  src/storage/v3/indices.hpp
  src/storage/v3/key_store.cpp
  src/storage/v3/key_store.hpp
  src/storage/v3/lexicographically_ordered_vertex.cpp
  src/storage/v3/lexicographically_ordered_vertex.hpp
  src/storage/v3/mvcc.hpp
  src/storage/v3/shard.cpp
  src/storage/v3/shard.hpp
  src/storage/v3/vertex.cpp
  src/storage/v3/vertex.hpp
  src/storage/v3/vertex_accessor.cpp
  tests/benchmark/data_structures_common.hpp
  tests/benchmark/data_structures_contains.cpp
  tests/benchmark/data_structures_find.cpp
  tests/benchmark/data_structures_insert.cpp
  tests/benchmark/data_structures_remove.cpp
  tests/unit/CMakeLists.txt
  tests/unit/storage_v3_key_store.cpp
Labels: :pineapple:

#712 [master<T1215-MG] Fix LOAD CSV large memory usage
  src/query/interpreter.cpp
  src/query/plan/operator.cpp
  src/utils/csv_parsing.cpp
  src/utils/memory.cpp
  src/utils/memory.hpp
  tests/unit/utils_memory.cpp
Labels: v2.5.1

#724 [master < DX-T1012 ]Fix create edge type hint and comment.
  include/mgp.py
Labels: documentation, community, v2.5.1

#709 [master < T1213] Match not allowed on replica
  src/query/plan/read_write_type_checker.cpp
  src/query/plan/read_write_type_checker.hpp
  tests/unit/query_plan_read_write_typecheck.cpp
Labels: bug, v2.5.1

#727 [master < T1029-DX] Release mgp 1.1.1
  release/mgp/.gitignore
  release/mgp/pyproject.toml
Labels: v2.5.1
