Repository memgraph/memgraph, pull requests merged in 2023-10, with the labels that each got.

#1286 Add mgbench support for disk storage and analytical mode
  .github/workflows/diff.yaml
  tests/mgbench/README.md
  tests/mgbench/benchmark.py
  tests/mgbench/benchmark_context.py
  tests/mgbench/benchmark_results.py
  tests/mgbench/constants.py
  tests/mgbench/helpers.py
  tests/mgbench/log.py
  tests/mgbench/runners.py
  tests/mgbench/workloads/base.py
  tests/mgbench/workloads/disk_pokec.py
  tests/mgbench/workloads/importers/disk_importer_pokec.py
  tools/bench-graph-client/main.py
Labels: benchmarking, on disk, analytical mode

#1318 Fix a crash caused when declaring a path with only one node in OPTIONAL MATCH clause
  src/query/plan/rule_based_planner.hpp
  tests/gql_behave/tests/openCypher_M09/features/OptionalMatchAcceptance.feature
Labels: bug, Ready for review

#1238 Add GQL behave tests for on-disk storage
  .github/workflows/diff.yaml
  src/query/db_accessor.hpp
  tests/e2e/run.sh
  tests/gql_behave/README.md
  tests/gql_behave/continuous_integration
  tests/gql_behave/run.py
  tests/gql_behave/tests/config.yaml
  tests/setup.sh
Labels: on disk

#1325 Decouple pure replication state from storage
  src/CMakeLists.txt
  src/kvstore/CMakeLists.txt
  src/query/interpreter.cpp
  src/query/interpreter.hpp
  src/query/procedure/mg_procedure_impl.cpp
  src/replication/CMakeLists.txt
  src/replication/config.cpp
  src/replication/epoch.cpp
  src/replication/include/replication/config.hpp
  src/replication/include/replication/epoch.hpp
  src/replication/include/replication/mode.hpp
  src/replication/include/replication/role.hpp
  src/replication/include/replication/state.hpp
  src/replication/include/replication/status.hpp
  src/replication/state.cpp
  src/replication/status.cpp
  src/storage/v2/CMakeLists.txt
  src/storage/v2/disk/storage.hpp
  src/storage/v2/durability/durability.cpp
  src/storage/v2/durability/durability.hpp
  src/storage/v2/durability/paths.hpp
  src/storage/v2/durability/snapshot.cpp
  src/storage/v2/durability/snapshot.hpp
  src/storage/v2/inmemory/replication/replication_client.cpp
  src/storage/v2/inmemory/replication/replication_client.hpp
  src/storage/v2/inmemory/replication/replication_server.cpp
  src/storage/v2/inmemory/replication/replication_server.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/replication/enums.hpp
  src/storage/v2/replication/global.hpp
  src/storage/v2/replication/replication.cpp
  src/storage/v2/replication/replication.hpp
  src/storage/v2/replication/replication_client.cpp
  src/storage/v2/replication/replication_client.hpp
  src/storage/v2/replication/replication_handler.cpp
  src/storage/v2/replication/replication_handler.hpp
  src/storage/v2/replication/replication_server.cpp
  src/storage/v2/replication/replication_server.hpp
  src/storage/v2/replication/replication_storage_state.cpp
  src/storage/v2/replication/replication_storage_state.hpp
  src/storage/v2/replication/rpc.hpp
  src/storage/v2/storage.cpp
  src/storage/v2/storage.hpp
  src/utils/CMakeLists.txt
  tests/unit/replication_persistence_helper.cpp
  tests/unit/storage_v2_replication.cpp
Labels: high-availability, multi-tenancy

#1335 Improve expansions on disk
  src/query/db_accessor.hpp
  src/query/dump.cpp
  src/query/interpret/awesome_memgraph_functions.cpp
  src/query/plan/operator.cpp
  src/query/procedure/mg_procedure_impl.cpp
  src/query/trigger_context.cpp
  src/storage/v2/all_vertices_iterable.cpp
  src/storage/v2/all_vertices_iterable.hpp
  src/storage/v2/disk/edge_import_mode_cache.cpp
  src/storage/v2/disk/edge_import_mode_cache.hpp
  src/storage/v2/disk/label_index.cpp
  src/storage/v2/disk/label_index.hpp
  src/storage/v2/disk/label_property_index.cpp
  src/storage/v2/disk/label_property_index.hpp
  src/storage/v2/disk/rocksdb_storage.cpp
  src/storage/v2/disk/rocksdb_storage.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/durability/snapshot.cpp
  src/storage/v2/durability/snapshot.hpp
  src/storage/v2/edge_accessor.cpp
  src/storage/v2/edge_accessor.hpp
  src/storage/v2/indices/indices.cpp
  src/storage/v2/indices/label_index.hpp
  src/storage/v2/indices/label_property_index.hpp
  src/storage/v2/inmemory/label_index.cpp
  src/storage/v2/inmemory/label_index.hpp
  src/storage/v2/inmemory/label_property_index.cpp
  src/storage/v2/inmemory/label_property_index.hpp
  src/storage/v2/inmemory/replication/replication_server.cpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/modified_edge.hpp
  src/storage/v2/storage.cpp
  src/storage/v2/storage.hpp
  src/storage/v2/transaction.hpp
  src/storage/v2/vertex_accessor.cpp
  src/storage/v2/vertex_accessor.hpp
  src/storage/v2/vertex_info_helpers.hpp
  src/utils/rocksdb_serialization.hpp
  tests/e2e/mock_api/workloads.yaml
  tests/e2e/triggers/workloads.yaml
  tests/e2e/write_procedures/workloads.yaml
  tests/gql_behave/tests/memgraph_V1/features/foreach.feature
  tests/unit/clearing_old_disk_data.cpp
  tests/unit/query_dump.cpp
  tests/unit/query_plan_common.hpp
  tests/unit/query_plan_create_set_remove_delete.cpp
  tests/unit/query_plan_v2_create_set_remove_delete.cpp
  tests/unit/query_procedures_mgp_graph.cpp
  tests/unit/query_trigger.cpp
  tests/unit/storage_v2_edge_ondisk.cpp
Labels: enhancement, on disk, Docs needed

#1347 Refactor disk storage
  src/query/plan/operator.cpp
  src/storage/v2/CMakeLists.txt
  src/storage/v2/disk/durable_metadata.cpp
  src/storage/v2/disk/durable_metadata.hpp
  src/storage/v2/disk/label_index.cpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/disk/unique_constraints.cpp
  src/storage/v2/id_types.hpp
  src/storage/v2/storage.cpp
  src/storage/v2/storage.hpp
  src/storage/v2/transaction.hpp
  src/storage/v2/vertex_accessor.cpp
  src/utils/rocksdb_serialization.hpp
  tests/e2e/mock_api/workloads.yaml
  tests/e2e/triggers/workloads.yaml
  tests/e2e/write_procedures/workloads.yaml
  tests/unit/storage_rocks.cpp
  tests/unit/storage_v2_constraints.cpp
Labels: enhancement, on disk

#1366 Add human readable memory allocations in show storage info
  src/query/interpreter.cpp
Labels: enhancement, Docs needed

#1327 Fix CPU 100% usage
  src/communication/websocket/session.cpp
  src/communication/websocket/session.hpp
Labels: bug

#1370 Fix subtle replication bug
  src/storage/v2/replication/replication_handler.cpp
Labels: bug

#1368 Fix DB configuration error under expansion gbench
  tests/benchmark/expansion.cpp
Labels: bug

#1324 Parametrize CI workflows to be able to change build type
  .github/workflows/diff.yaml
  .github/workflows/package_all.yaml
  .github/workflows/performance_benchmarks.yaml
  .github/workflows/release_centos8.yaml
  .github/workflows/release_debian10.yaml
  .github/workflows/release_ubuntu2004.yaml
  release/package/run.sh
  tools/setup
Labels: infrastructure

#1288 Improve systemd config
  release/memgraph.service
Labels: infrastructure

#1367 Forbid changing isolation level for disk and analytical
  src/query/exceptions.hpp
  src/query/interpreter.cpp
  src/storage/v2/storage.cpp
  tests/e2e/graphql/graphql_server.py
Labels: bug, Docs - changelog only

#1355 Fix crash caused by deleting non-existing relationship in DETACH DELETE clause
  src/storage/v2/storage.cpp
  tests/gql_behave/tests/memgraph_V1/features/delete.feature
Labels: bug

#1278 Fix SHOW CONFIG doesn't show the run-time flag status
  src/flags/bolt.cpp
  src/flags/bolt.hpp
  src/flags/general.cpp
  src/flags/general.hpp
  src/flags/log_level.cpp
  src/flags/log_level.hpp
  src/flags/run_time_configurable.cpp
  src/flags/run_time_configurable.hpp
  src/glue/CMakeLists.txt
  src/glue/SessionHL.cpp
  src/query/interpreter.cpp
  tests/e2e/configuration/default_config.py
  tests/integration/run_time_settings/CMakeLists.txt
  tests/integration/run_time_settings/config_checker.cpp
  tests/integration/run_time_settings/runner.py
  tests/unit/interpreter.cpp
Labels: bug, Ship it, Docs unnecessary

#1250 Implement jemalloc extent hooks memory tracker
  cmake/FindJemalloc.cmake
  cmake/Findjemalloc.cmake
  libs/CMakeLists.txt
  libs/setup.sh
  src/memgraph.cpp
  src/memory/CMakeLists.txt
  src/memory/memory_control.cpp
  src/memory/memory_control.hpp
  src/memory/new_delete.cpp
  tests/e2e/disk_storage/workloads.yaml
  tests/e2e/memgraph.py
  tests/e2e/memory/workloads.yaml
  tests/stress/common.py
  tests/stress/continuous_integration
  tests/stress/memory_limit.py
  tests/stress/memory_tracker.py
  tests/stress/test_config.py
Labels: memory, Docs - changelog only

#1252 Fix bug in alias mapping
  config/mappings.json
  src/query/procedure/module.cpp
Labels: bug, Docs - changelog only

#1336 Implement key_exists under map under mgp
  include/_mgp.hpp
  include/mg_procedure.h
  include/mgp.hpp
  src/query/procedure/mg_procedure_impl.cpp
  tests/unit/cpp_api.cpp
Labels: Ship it, Docs needed

#1246 Add values and keys function to map
  src/query/interpret/awesome_memgraph_functions.cpp
Labels: feature, Docs needed

#1323 Add DNS support for cluster replica address
  src/io/network/endpoint.cpp
  src/io/network/endpoint.hpp
  src/io/network/socket.cpp
  src/query/interpreter.cpp
  src/storage/v2/replication/replication_client.cpp
  src/storage/v2/replication/replication_handler.cpp
Labels: feature, high-availability, k8s, Docs needed

#1224 Revision of Contributing section in README
  README.md
Labels: documentation

#1364 Add renaming of edge types
  include/_mgp.hpp
  include/mg_procedure.h
  include/mgp.hpp
  src/query/db_accessor.cpp
  src/query/db_accessor.hpp
  src/query/procedure/mg_procedure_impl.cpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/storage.hpp
  tests/e2e/transaction_rollback/CMakeLists.txt
  tests/e2e/transaction_rollback/procedures/procedures.cpp
  tests/e2e/transaction_rollback/transaction.py
  tests/unit/cpp_api.cpp
Labels: feature, Ready for review, Docs needed

#1361 Add retry logic possible when conflicting transactions
  src/glue/SessionHL.cpp
  src/query/exceptions.hpp
  tests/drivers/csharp/v4_1/ParallelEdgeImport/ParallelEdgeImport.csproj
  tests/drivers/csharp/v4_1/ParallelEdgeImport/Program.cs
  tests/drivers/go/v5/go.mod
  tests/drivers/go/v5/go.sum
  tests/drivers/go/v5/parallel_edge_import.go
  tests/drivers/go/v5/run.sh
  tests/drivers/java/v5_8/pom.xml
  tests/drivers/java/v5_8/run.sh
  tests/drivers/java/v5_8/src/main/java/memgraph/ParallelEdgeImport.java
  tests/drivers/node/v4_1/parallel_edge_import.js
  tests/drivers/node/v5_8/parallel_edge_import.js
  tests/drivers/node/v5_8/run.sh
  tests/drivers/python/v4_1/parallel_edge_import.py
  tests/drivers/python/v4_1/run.sh
  tests/drivers/python/v5_8/parallel_edge_import.py
  tests/drivers/python/v5_8/run.sh
Labels: bug, Docs needed

#1393 Add cartesian mgbench
  .github/workflows/daily_benchmark.yaml
  .github/workflows/performance_benchmarks.yaml
  tests/mgbench/workloads/cartesian.py
Labels: benchmarking, Docs unnecessary

#1226 Add HashJoin operator
  src/query/plan/cost_estimator.hpp
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  src/query/plan/operator_type_info.cpp
  src/query/plan/planner.hpp
  src/query/plan/pretty_print.cpp
  src/query/plan/pretty_print.hpp
  src/query/plan/rewrite/join.hpp
  src/utils/event_counter.cpp
  src/utils/typeinfo.hpp
  tests/gql_behave/README.md
  tests/gql_behave/tests/memgraph_V1/features/cartesian.feature
  tests/unit/query_common.hpp
  tests/unit/query_plan.cpp
  tests/unit/query_plan_checker.hpp
  tests/unit/query_plan_operator_to_string.cpp
Labels: Ready for review, optimization, Docs needed

#1343 Provide textual information for inefficient plans with notifications
  libs/CMakeLists.txt
  libs/setup.sh
  src/query/CMakeLists.txt
  src/query/interpreter.cpp
  src/query/metadata.cpp
  src/query/metadata.hpp
  src/query/plan/hint_provider.cpp
  src/query/plan/hint_provider.hpp
  src/query/plan/preprocess.hpp
  tests/unit/CMakeLists.txt
  tests/unit/query_hint_provider.cpp
Labels: feature, Docs - changelog only

#1299 Fix bug on memory::Pool wrong last_dealloc_pool
  src/utils/memory.cpp
Labels: memory, Docs - changelog only

#1387 Storage GC changes
  src/memory/CMakeLists.txt
  src/storage/v2/delta.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/transaction.hpp
  src/storage/v2/vertex_info_cache.cpp
  src/storage/v2/vertex_info_cache.hpp
  src/utils/bond.hpp
  src/utils/scheduler.hpp
  tests/benchmark/CMakeLists.txt
  tests/benchmark/storage_v2_gc2.cpp
Labels: Docs - changelog only

#1399 Fix gql behave dropping connection on Memgraph
  src/query/plan/hint_provider.hpp
  tests/gql_behave/.gitignore
  tests/gql_behave/continuous_integration
Labels: bug, Docs unnecessary

#1379 Add OOM enabler in operator tree
  src/query/interpreter.cpp
  src/query/plan/operator.cpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/storage.cpp
  tests/e2e/memory/CMakeLists.txt
  tests/e2e/memory/memory_limit_accumulation.cpp
  tests/e2e/memory/memory_limit_delete.cpp
  tests/e2e/memory/memory_limit_edge_create.cpp
  tests/e2e/memory/workloads.yaml
Labels: memory, Docs - changelog only

#1341 Add constraint verification update only on necessary actions
  src/storage/v2/CMakeLists.txt
  src/storage/v2/constraint_verification_info.cpp
  src/storage/v2/constraint_verification_info.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/unique_constraints.hpp
  src/storage/v2/transaction.hpp
  src/storage/v2/vertex_accessor.cpp
  tests/e2e/CMakeLists.txt
  tests/e2e/constraints/CMakeLists.txt
  tests/e2e/constraints/common.py
  tests/e2e/constraints/constraints_validation.py
  tests/e2e/constraints/workloads.yaml
Labels: feature, Docs - changelog only

#1340 Use extent hooks for per query memory limit
  include/mg_procedure.h
  src/memgraph.cpp
  src/memory/CMakeLists.txt
  src/memory/global_memory_control.cpp
  src/memory/global_memory_control.hpp
  src/memory/query_memory_control.cpp
  src/memory/query_memory_control.hpp
  src/query/db_accessor.cpp
  src/query/db_accessor.hpp
  src/query/interpreter.cpp
  src/query/interpreter.hpp
  src/query/procedure/mg_procedure_impl.cpp
  src/utils/memory_tracker.cpp
  src/utils/memory_tracker.hpp
  tests/e2e/memgraph.py
  tests/e2e/memory/CMakeLists.txt
  tests/e2e/memory/procedures/CMakeLists.txt
  tests/e2e/memory/procedures/query_memory_limit_proc.cpp
  tests/e2e/memory/procedures/query_memory_limit_proc_multi_thread.cpp
  tests/e2e/memory/query_memory_limit_create.cpp
  tests/e2e/memory/query_memory_limit_multi_thread.cpp
  tests/e2e/memory/query_memory_limit_proc.cpp
  tests/e2e/memory/query_memory_limit_proc_multi_thread.cpp
  tests/e2e/memory/workloads.yaml
  tests/integration/audit/runner.py
  tests/integration/auth/runner.py
  tests/integration/durability/runner.py
  tests/integration/env_variable_check/runner.py
  tests/integration/fine_grained_access/runner.py
  tests/integration/flag_check/runner.py
  tests/integration/ldap/runner.py
  tests/integration/mg_import_csv/runner.py
  tests/integration/run_time_settings/runner.py
  tests/integration/storage_mode/runner.py
  tests/macro_benchmark/databases.py
Labels: memory, Docs needed

#1384 Transfer query modules from MAGE to Memgraph
  query_modules/CMakeLists.txt
  query_modules/convert.py
  query_modules/mgps.py
  query_modules/schema.cpp
  tests/e2e/CMakeLists.txt
  tests/e2e/query_modules/CMakeLists.txt
  tests/e2e/query_modules/common.py
  tests/e2e/query_modules/conftest.py
  tests/e2e/query_modules/convert_test.py
  tests/e2e/query_modules/mgps_test.py
  tests/e2e/query_modules/schema_test.py
  tests/e2e/query_modules/workloads.yaml
  tests/e2e/runner.py
  tests/e2e/x.sh
Labels: Ready for review, Docs needed

#1265 Add filtering details to EXPLAIN and PROFILE
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  src/query/plan/preprocess.hpp
  src/query/plan/pretty_print.cpp
  src/query/plan/rule_based_planner.hpp
  tests/e2e/analyze_graph/optimize_indexes.py
  tests/unit/interpreter.cpp
  tests/unit/query_common.hpp
  tests/unit/query_plan_operator_to_string.cpp
Labels: feature, Ready for review, Docs needed

#1345 Add index hints
  .gitignore
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/frontend/opencypher/grammar/MemgraphCypherLexer.g4
  src/query/plan/operator.hpp
  src/query/plan/planner.hpp
  src/query/plan/rewrite/index_lookup.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/disk_storage/workloads.yaml
  tests/e2e/index_hints/CMakeLists.txt
  tests/e2e/index_hints/common.py
  tests/e2e/index_hints/index_hints.py
  tests/e2e/index_hints/workloads.yaml
  tests/unit/query_plan_operator_to_string.cpp
Labels: feature, Ship it, Docs needed

#1424 Fix GQL release worklflows
  .github/workflows/release_centos8.yaml
  .github/workflows/release_debian10.yaml
  .github/workflows/release_ubuntu2004.yaml
Labels: bug

#1410 Fix mgbench upload script call
  .github/workflows/daily_benchmark.yaml
  .github/workflows/performance_benchmarks.yaml
Labels: bug, Docs unnecessary

#1431 Fix PROFILE infinite loop
  src/query/plan/operator.cpp
  tests/e2e/CMakeLists.txt
  tests/e2e/inspect_query/CMakeLists.txt
  tests/e2e/inspect_query/common.py
  tests/e2e/inspect_query/inspect_query.py
  tests/e2e/inspect_query/workloads.yaml
Labels: bug, Ready for review, Docs unnecessary
