Repository memgraph/memgraph, pull requests merged in 2023-11, with the labels that each got.

#1382 Throw when exists() combined with CASE
  src/query/frontend/semantic/symbol_generator.cpp
  tests/gql_behave/tests/memgraph_V1/features/case.feature
  tests/gql_behave/tests/memgraph_V1_on_disk/features/case.feature
Labels: bug

#1398 Make FrameChangeCollector owning the memory resource
  src/query/frame_change.hpp
  src/query/interpreter.cpp
Labels: bug

#1383 Support deleting paths
  src/query/plan/operator.cpp
  src/storage/v2/edge_accessor.hpp
  src/storage/v2/vertex_accessor.hpp
  tests/gql_behave/tests/memgraph_V1/features/delete.feature
  tests/gql_behave/tests/memgraph_V1_on_disk/features/delete.feature
  tests/gql_behave/tests/openCypher_M09/features/DeleteAcceptance.feature
Labels: feature, Docs - changelog only

#1381 Support localdatetime to date and localtime transfer
  src/query/interpret/awesome_memgraph_functions.cpp
  tests/gql_behave/tests/memgraph_V1/features/match.feature
  tests/gql_behave/tests/memgraph_V1_on_disk/features/match.feature
  tests/unit/utils_temporal.cpp
Labels: feature, Docs - changelog only

#1425 Remove all shortest paths logs
  src/query/interpreter.cpp
Labels: Docs unnecessary

#1426 Rename memory usage and memory allocated
  src/http_handlers/metrics.hpp
  src/license/license_sender.cpp
  src/query/interpreter.cpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/storage.hpp
  src/telemetry/collectors.cpp
  src/utils/stat.hpp
  tests/e2e/configuration/storage_info.py
  tests/stress/memory_limit.py
  tests/stress/memory_tracker.py
  tests/unit/database_get_info.cpp
  tests/unit/storage_v2_get_info.cpp
Labels: Docs needed

#1409 Fix Kafka flaky unit test
  src/integrations/kafka/consumer.cpp
  tests/unit/integrations_kafka_consumer.cpp
Labels: infrastructure, Docs unnecessary

#1461 Revert license sender info
  src/license/license_sender.cpp
Labels: Docs unnecessary

#1385 Delete corrupted snapshots
  src/dbms/inmemory/storage_helper.hpp
  src/query/interpreter.cpp
  src/storage/v2/durability/snapshot.cpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/storage.cpp
  src/storage/v2/storage.hpp
  src/utils/file.cpp
  tests/unit/storage_v2_storage_mode.cpp
Labels: bug, Severity - S1, Docs - changelog only

#1348 Fix cached plan not getting invalidated
  src/dbms/database.cpp
  src/dbms/database.hpp
  src/query/cypher_query_interpreter.cpp
  src/query/cypher_query_interpreter.hpp
  src/query/interpreter.cpp
  src/query/trigger.cpp
  src/query/trigger.hpp
  src/utils/lru_cache.hpp
  tests/e2e/configuration/default_config.py
  tests/unit/CMakeLists.txt
  tests/unit/interpreter.cpp
  tests/unit/lru_cache.cpp
Labels: bug, memory, Docs needed

#1443 Use extent hooks for memory procedure limit
  src/memory/global_memory_control.cpp
  src/memory/query_memory_control.cpp
  src/memory/query_memory_control.hpp
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  src/query/plan/rule_based_planner.hpp
  src/utils/CMakeLists.txt
  src/utils/memory.hpp
  src/utils/memory_tracker.cpp
  src/utils/memory_tracker.hpp
  src/utils/query_memory_tracker.cpp
  src/utils/query_memory_tracker.hpp
  tests/e2e/memory/CMakeLists.txt
  tests/e2e/memory/procedure_memory_limit.cpp
  tests/e2e/memory/procedure_memory_limit_multi_proc.cpp
  tests/e2e/memory/procedures/CMakeLists.txt
  tests/e2e/memory/procedures/proc_memory_limit.cpp
  tests/e2e/memory/workloads.yaml
  tests/unit/query_plan_read_write_typecheck.cpp
Labels: memory, Docs - changelog only

#1319 Fix compare results in mgbench
  tests/mgbench/compare_results.py
Labels: Ready for review

#1380 Fix accessing a variable bound to a list within BFS function
  src/query/frame_change.hpp
  src/query/interpret/eval.hpp
  tests/gql_behave/tests/memgraph_V1/features/memgraph_bfs.feature
Labels: bug, Ship it, Docs - changelog only

#1468 Fix race condition and arena tracking bug
  src/memory/global_memory_control.cpp
  src/memory/query_memory_control.cpp
  src/memory/query_memory_control.hpp
  src/utils/memory_tracker.hpp
Labels: memory, Docs unnecessary, customer

#1496 Fix hash join expression matching
  src/query/plan/operator.cpp
  src/query/plan/rewrite/join.hpp
  tests/gql_behave/tests/memgraph_V1/features/cartesian.feature
Labels: Docs unnecessary

#1479 Fix parallel index loading
  src/storage/v2/durability/durability.cpp
Labels: Docs - changelog only

#1478 Add fix indexed join crash
  src/query/plan/rewrite/join.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/queries/CMakeLists.txt
  tests/e2e/queries/common.py
  tests/e2e/queries/queries.py
  tests/e2e/queries/workloads.yaml
Labels: Severity - S1, Docs - changelog only

#1494 Fix for in list segmentation fault
  src/query/frame_change.hpp
  src/query/interpret/eval.hpp
  src/query/interpreter.cpp
  tests/gql_behave/tests/memgraph_V1/features/list_operations.feature
Labels: Severity - S1, Docs - changelog only

#1482 Fix empty aggregation returns null
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  tests/e2e/replication/show_while_creating_invalid_state.py
  tests/gql_behave/tests/memgraph_V1/features/aggregations.feature
  tests/gql_behave/tests/memgraph_V1_on_disk/features/aggregations.feature
  tests/unit/query_plan_accumulate_aggregate.cpp
Labels: bug

#1471 Fix garbage collection not working properly and add periodic jemalloc purge
  CMakeLists.txt
  src/flags/general.cpp
  src/memory/CMakeLists.txt
  src/storage/v2/CMakeLists.txt
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/garbage_collection/CMakeLists.txt
  tests/e2e/garbage_collection/common.py
  tests/e2e/garbage_collection/conftest.py
  tests/e2e/garbage_collection/gc_periodic.py
  tests/e2e/garbage_collection/workloads.yaml
Labels: bug, community, Severity - S1, memory, Docs needed

#1480 Add granular index and constraint recovery info
  src/dbms/inmemory/replication_handlers.cpp
  src/storage/v2/durability/durability.cpp
  src/storage/v2/durability/durability.hpp
Labels: Importance - I3, Effort - Low, Severity - S1, Docs - changelog only

#1506 Remove default memory limit on procedures
  src/query/frontend/ast/cypher_main_visitor.cpp
  tests/unit/cypher_main_visitor.cpp
Labels: Docs needed, customer

#1524 Prepare for 2.12.1 patch release
  CMakeLists.txt
  licenses/BSL.txt
Labels: Docs unnecessary

#1521 Fix flaky gc test
  tests/e2e/garbage_collection/gc_periodic.py
Labels: tests, Docs unnecessary

#1531 Aggregations return empty result when used with group by
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  tests/gql_behave/tests/memgraph_V1/features/aggregations.feature
  tests/gql_behave/tests/memgraph_V1_on_disk/features/aggregations.feature
  tests/unit/query_plan_accumulate_aggregate.cpp
Labels: Ready for review, Docs - changelog only

#1485 Add support for schema.assert
  include/_mgp.hpp
  include/mg_procedure.h
  include/mgp.hpp
  query_modules/schema.cpp
  src/query/db_accessor.cpp
  src/query/db_accessor.hpp
  src/query/interpreter.cpp
  src/query/procedure/mg_procedure_impl.cpp
  src/storage/v2/inmemory/storage.cpp
  tests/e2e/query_modules/schema_test.py
  tests/e2e/query_modules/workloads.yaml
Labels: feature, Docs needed

#1507 Add Package memgraph workflow
  .github/workflows/package_all.yaml
  .github/workflows/package_memgraph.yaml
Labels: Docs unnecessary

#1465 Handle exception when using init-file flag
  src/memgraph.cpp
  src/query/exceptions.hpp
  src/query/interpreter.cpp
  tests/integration/CMakeLists.txt
  tests/integration/init_file/CMakeLists.txt
  tests/integration/init_file/auth.cypherl
  tests/integration/init_file/runner.py
  tests/integration/init_file/tester.cpp
Labels: bug, Docs needed

#1539 Implement short circuiting of exists evaluation
  src/glue/communication.cpp
  src/query/common.cpp
  src/query/interpret/awesome_memgraph_functions.cpp
  src/query/interpret/eval.hpp
  src/query/plan/operator.cpp
  src/query/plan/rule_based_planner.cpp
  src/query/procedure/mg_procedure_impl.cpp
  src/query/typed_value.cpp
  src/query/typed_value.hpp
  tests/unit/formatters.hpp
  tests/unit/query_expression_evaluator.cpp
  tests/unit/query_plan.cpp
  tests/unit/query_plan_checker.hpp
Labels: Docs - changelog only, customer

#1491 Fix frame change collector pmr type error
  src/query/frame_change.hpp
Labels: Importance - I2, Effort - Medium, Severity - S3, Docs unnecessary
