Repository memgraph/memgraph, pull requests merged in 2023-05, with the labels that each got.

#903 [Master < ] Fix metodology links
  tests/mgbench/README.md
Labels: Ready for review, benchmarking

#928 Fix mgbench typo.
  tests/mgbench/.gitignore
  tests/mgbench/benchmark.py
Labels: Ready for review, benchmarking

#931 [T1254 < T1255] All-properties lookup
  src/query/frontend/ast/ast.cpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/ast_visitor.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/pretty_print.cpp
  src/query/frontend/opencypher/grammar/Cypher.g4
  src/query/interpret/eval.hpp
  src/query/plan/preprocess.hpp
  src/query/plan/rule_based_planner.cpp
  src/utils/typeinfo.hpp
  tests/benchmark/query/eval.cpp
  tests/gql_behave/tests/memgraph_V1/features/map_projection.feature
  tests/unit/cypher_main_visitor.cpp
  tests/unit/query_common.hpp
  tests/unit/query_expression_evaluator.cpp
  tests/unit/query_plan.cpp
  tests/unit/query_pretty_print.cpp
  tests/unit/stripped.cpp
Labels: enhancement, community, Ready for review

#922 [T1253 < T1254] Map projection planning and execution logic
  src/query/frontend/ast/ast.cpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/ast_visitor.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/pretty_print.cpp
  src/query/frontend/opencypher/grammar/Cypher.g4
  src/query/interpret/eval.hpp
  src/query/plan/preprocess.hpp
  src/query/plan/rule_based_planner.cpp
  src/utils/typeinfo.hpp
  tests/benchmark/query/eval.cpp
  tests/gql_behave/tests/memgraph_V1/features/map_projection.feature
  tests/unit/cypher_main_visitor.cpp
  tests/unit/query_common.hpp
  tests/unit/query_expression_evaluator.cpp
  tests/unit/query_plan.cpp
  tests/unit/query_pretty_print.cpp
  tests/unit/stripped.cpp
Labels: enhancement, community, Ready for review

#895 [E219 < T1253] Map projection Cypher grammar & AST
  src/query/frontend/ast/ast.cpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/ast_visitor.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/ast/pretty_print.cpp
  src/query/frontend/opencypher/grammar/Cypher.g4
  src/query/interpret/eval.hpp
  src/query/plan/preprocess.hpp
  src/query/plan/rule_based_planner.cpp
  src/utils/typeinfo.hpp
  tests/benchmark/query/eval.cpp
  tests/gql_behave/tests/memgraph_V1/features/map_projection.feature
  tests/unit/cypher_main_visitor.cpp
  tests/unit/query_common.hpp
  tests/unit/query_expression_evaluator.cpp
  tests/unit/query_plan.cpp
  tests/unit/query_pretty_print.cpp
  tests/unit/stripped.cpp
Labels: enhancement, community, Ready for review

#894 [master <] Add BUILD INFO query
  CMakeLists.txt
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/opencypher/grammar/Cypher.g4
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/frontend/opencypher/grammar/MemgraphCypherLexer.g4
  src/query/frontend/semantic/required_privileges.cpp
  src/query/frontend/stripped_lexer_constants.hpp
  src/query/interpreter.cpp
  src/utils/CMakeLists.txt
  src/utils/build_info.cpp
  src/utils/build_info.hpp
Labels: enhancement

#933 [master < T891] (UN)LOCK query enhancement
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/frontend/opencypher/grammar/MemgraphCypherLexer.g4
  src/query/frontend/stripped_lexer_constants.hpp
  src/query/interpreter.cpp
  src/storage/v2/replication/replication_client.cpp
  src/storage/v2/storage.cpp
  src/storage/v2/storage.hpp
  src/utils/file_locker.cpp
  src/utils/file_locker.hpp
  tests/unit/cypher_main_visitor.cpp
  tests/unit/utils_file_locker.cpp
Labels: enhancement

#892 [master < E219] Map projection
  src/query/frontend/ast/ast.cpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/ast_visitor.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/ast/pretty_print.cpp
  src/query/frontend/opencypher/grammar/Cypher.g4
  src/query/interpret/eval.hpp
  src/query/plan/preprocess.hpp
  src/query/plan/rule_based_planner.cpp
  src/utils/typeinfo.hpp
  tests/benchmark/query/eval.cpp
  tests/gql_behave/tests/memgraph_V1/features/map_projection.feature
  tests/unit/cypher_main_visitor.cpp
  tests/unit/query_common.hpp
  tests/unit/query_expression_evaluator.cpp
  tests/unit/query_plan.cpp
  tests/unit/query_pretty_print.cpp
  tests/unit/stripped.cpp
Labels: enhancement, community, Ready for review, epic

#945 [master < T945] Handle user-defined metadata and expose it with SHOW TRANSACTIONS
  .clang-format
  .pre-commit-config.yaml
  src/communication/bolt/v1/session.hpp
  src/communication/bolt/v1/states/handlers.hpp
  src/memgraph.cpp
  src/query/interpreter.cpp
  src/query/interpreter.hpp
  tests/drivers/csharp/v4_1/Metadata/Metadata.csproj
  tests/drivers/csharp/v4_1/Metadata/Program.cs
  tests/drivers/go/v4/metadata.go
  tests/drivers/go/v4/run.sh
  tests/drivers/java/v1/Basic.java
  tests/drivers/java/v4_1/Metadata.java
  tests/drivers/java/v4_1/run.sh
  tests/drivers/node/v4_1/metadata.js
  tests/drivers/node/v4_1/run.sh
  tests/drivers/python/v4_1/metadata.py
  tests/drivers/python/v4_1/run.sh
  tests/unit/bolt_session.cpp
Labels: enhancement, bolt
