Repository memgraph/memgraph, pull requests merged in 2023-02, with the labels that each got.

#746 Try to add simplest mgbench dataset
  tests/mgbench/benchmark.py
  tests/mgbench/datasets.py
  tests/mgbench/helpers.py
  tests/mgbench/runners.py
Labels: infrastructure

#787 [master < MG-build-fedora] Build memgraph for fedora-36
  .github/workflows/package_all.yaml
  environment/os/fedora-36.sh
  environment/toolchain/v4.sh
  init
  release/CMakeLists.txt
  release/package/docker-compose.yml
  release/package/fedora-36/Dockerfile
  release/package/run.sh
  release/rpm/memgraph.spec.in
  release/rpm/rpmlintrc
Labels: infrastructure

#775 [master < T576-FL] Update pull request template
  .github/pull_request_template.md
Labels: Ready for review

#774 [master < T585-FL] Improve Visit performance
  src/query/frontend/ast/ast.lcp
  src/query/interpret/eval.hpp
  tests/unit/query_expression_evaluator.cpp
Labels: Ready for review

#760 [master < ] Update mgbench c++ client
  tests/mgbench/client.cpp
  tests/mgbench/runners.py
Labels: Ready for review, benchmarking

#788 [master < T591-FL] Enhance performance of Property Store on node creation
  src/query/common.hpp
  src/query/db_accessor.hpp
  src/query/plan/operator.cpp
  src/storage/v2/edge_accessor.cpp
  src/storage/v2/edge_accessor.hpp
  src/storage/v2/property_store.cpp
  src/storage/v2/property_store.hpp
  src/storage/v2/vertex_accessor.cpp
  src/storage/v2/vertex_accessor.hpp
  tests/gql_behave/tests/memgraph_V1/features/functions.feature
  tests/unit/storage_v2_property_store.cpp
Labels: Ready for review
