Repository memgraph/memgraph, pull requests merged in 2023-08, with the labels that each got.

#1086 [master < T1086] Log if replica cannot recover using curr wal file
  src/storage/v2/replication/replication_client.cpp
  src/storage/v2/replication/replication_client.hpp
  src/storage/v2/replication/replication_server.cpp
  src/storage/v2/replication/replication_server.hpp
  tests/jepsen/resources/node-config.edn
Labels: enhancement

#1126 [master < T595-MAGE] Add remove label on c api
  include/_mgp.hpp
  include/mgp.hpp
Labels: Ship it

#1127 [master < T600] Implement << operator for mgp::Value
  include/mgp.hpp
  tests/unit/cpp_api.cpp
Labels: Ship it

#1128 [master < T1128] Implement RemoveProperty for node cpp api
  include/mgp.hpp
  tests/unit/cpp_api.cpp
Labels: Ship it

#1089 [master < T1089] Improve RestoreReplicationRole
  src/storage/v2/inmemory/storage.cpp
Labels: enhancement

#1109 [master < ]Cache user to speed up PullPlan
  src/glue/auth_checker.cpp
  src/glue/auth_checker.hpp
  src/query/interpreter.cpp
Labels: optimization

#1067 [master <] Bugfix: Throw if user was created without a license
  src/auth/models.cpp
Labels: bug

#1134 [master < T1134] Fix bug with on-disk triggers
  src/query/interpreter.cpp
  tests/e2e/triggers/workloads.yaml
Labels: bug, Ship it

#1139 [master < T1139] Improve disk indices
  src/storage/v2/disk/label_index.cpp
  src/storage/v2/disk/label_property_index.cpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/disk/unique_constraints.cpp
  tests/unit/storage_v2_indices.cpp
Labels: enhancement

#1145 [master < T1145] Filter deleted edges during edge prefetch
  src/storage/v2/disk/rocksdb_storage.cpp
  src/storage/v2/disk/rocksdb_storage.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/utils/rocksdb_serialization.hpp
  tests/e2e/triggers/workloads.yaml
Labels: bug, Ship it

#1115 [master < T1115] Improve performance on set properties
  src/query/common.hpp
  src/query/db_accessor.hpp
  src/query/plan/operator.cpp
  src/storage/v2/delta.hpp
  src/storage/v2/edge_accessor.cpp
  src/storage/v2/edge_accessor.hpp
  src/storage/v2/property_store.cpp
  src/storage/v2/property_store.hpp
  src/storage/v2/vertex_accessor.cpp
  src/storage/v2/vertex_accessor.hpp
  tests/unit/query_plan_create_set_remove_delete.cpp
Labels: Ready for review

#1132 [master < T1132] Optimize import of edges on disk
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/utils/rocksdb_serialization.hpp
Labels: enhancement

#1155 Optimize splitting keys from on-disk storage
  libs/setup.sh
  src/utils/rocksdb_serialization.hpp
  src/utils/string.hpp
  tests/unit/storage_rocks.cpp
Labels: Ship it, optimization

#1181 [master <] Fix typo threashold -> threshold
  src/storage/v2/inmemory/indices_utils.hpp
  src/storage/v2/vertex_accessor.cpp
  src/storage/v2/vertex_info_cache.cpp
  src/storage/v2/vertex_info_cache.hpp
  tests/e2e/configuration/default_config.py
Labels: bug

#1174 [master < T1174] Bump PyYAML version
  tests/gql_behave/requirements.txt
  tests/gql_behave/steps/test_parameters.py
  tests/integration/ldap/requirements.txt
  tests/setup.sh
Labels: bug

#1159 [master < T1159] Optimize index and constraint update
  src/storage/v2/inmemory/label_property_index.cpp
  src/storage/v2/inmemory/label_property_index.hpp
  src/storage/v2/inmemory/unique_constraints.cpp
  src/storage/v2/inmemory/unique_constraints.hpp
Labels: enhancement, Ready for review

#1156 [master < T1156] Add Relationship.RemoveProperty in C++ API
  include/mgp.hpp
  tests/unit/cpp_api.cpp
Labels: enhancement, Status - In Progress

#1154 [master < T1154] Improve concurrency control for on-disk storage
  src/storage/v2/disk/storage.cpp
Labels: enhancement, on disk

#1153 [master < T1153] Disk storage improvements
  src/mg_import_csv.cpp
  src/query/interpreter.cpp
  src/query/interpreter.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/storage.hpp
Labels: enhancement, on disk

#1179 Add timestamp to DELETE_DESERIALIZED_OBJECT delta at which this object was created.
  src/storage/v2/delta.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/mvcc.hpp
  src/utils/disk_utils.hpp
Labels: Ready for review, on disk

#1146 [master < T1146] Add deterministic disk vertex_count and edge_count
  src/storage/v2/disk/rocksdb_storage.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/storage.hpp
  tests/e2e/disk_storage/CMakeLists.txt
  tests/e2e/disk_storage/create_edge_from_indices.py
  tests/e2e/disk_storage/storage_info.py
  tests/e2e/disk_storage/workloads.yaml
  tests/unit/CMakeLists.txt
  tests/unit/storage_v2_show_storage_info.cpp
Labels: bug

#1140 [master < T1140] Add ToString for mgp::Value and all mgp types
  include/mgp.hpp
  tests/unit/cpp_api.cpp
Labels: Ship it

#1202 [master < T1107] Add disk storage to e2e tests FIXED MERGE
  tests/e2e/batched_procedures/workloads.yaml
  tests/e2e/configuration/workloads.yaml
  tests/e2e/fine_grained_access/workloads.yaml
  tests/e2e/init_file_flags/workloads.yaml
  tests/e2e/isolation_levels/workloads.yaml
  tests/e2e/lba_procedures/workloads.yaml
  tests/e2e/load_csv/workloads.yaml
  tests/e2e/magic_functions/workloads.yaml
  tests/e2e/memgraph.py
  tests/e2e/memory/workloads.yaml
  tests/e2e/mock_api/workloads.yaml
  tests/e2e/module_file_manager/workloads.yaml
  tests/e2e/python_query_modules_reloading/workloads.yaml
  tests/e2e/streams/workloads.yaml
  tests/e2e/temporal_types/workloads.yaml
  tests/e2e/transaction_queue/workloads.yaml
  tests/e2e/triggers/workloads.yaml
  tests/e2e/write_procedures/workloads.yaml
Labels: on disk

#1171 [master < T1171] Add supernode performance workload
  .github/workflows/daily_benchmark.yaml
  tests/mgbench/workloads/supernode.py
Labels: benchmarking

#1172 [T1171 < T1172] Add high write set property workload
  .github/workflows/daily_benchmark.yaml
  tests/mgbench/workloads/high_write_set_property.py
Labels: benchmarking
