Repository memgraph/memgraph, pull requests merged in 2023-12, with the labels that each got.

#1434 [master < T1434] Filter variable-length expressions by path
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/opencypher/grammar/Cypher.g4
  src/query/frontend/semantic/symbol_generator.cpp
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  src/query/plan/preprocess.cpp
  src/query/plan/rewrite/index_lookup.hpp
  src/query/plan/rule_based_planner.hpp
  src/query/plan/variable_start_planner.cpp
  tests/gql_behave/tests/memgraph_V1/features/match.feature
  tests/gql_behave/tests/memgraph_V1/features/memgraph_allshortest.feature
  tests/gql_behave/tests/memgraph_V1/features/memgraph_bfs.feature
  tests/gql_behave/tests/memgraph_V1/features/memgraph_wshortest.feature
  tests/gql_behave/tests/memgraph_V1/graphs/graph_edges.cypher
  tests/gql_behave/tests/memgraph_V1/graphs/graph_index.cypher
  tests/unit/cypher_main_visitor.cpp
Labels: feature, Docs needed

#1481 Remove filter profile info
  src/query/plan/rewrite/index_lookup.hpp
  src/query/plan/rewrite/join.hpp
  src/query/plan/rule_based_planner.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/analyze_graph/optimize_indexes.py
  tests/e2e/filter_info/CMakeLists.txt
  tests/e2e/filter_info/common.py
  tests/e2e/filter_info/filter_info.py
  tests/e2e/filter_info/workloads.yaml
  tests/e2e/index_hints/index_hints.py
Labels: Importance - I1, Effort - Low, Severity - S2, Docs needed

#1555 Fix three match cartesian sequential scanning
  src/query/plan/rule_based_planner.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/query_planning/CMakeLists.txt
  tests/e2e/query_planning/common.py
  tests/e2e/query_planning/query_planning_cartesian.py
  tests/e2e/query_planning/workloads.yaml
Labels: bug, Docs - changelog only

#1395 Handle analytical mode in community_detection during parallel changes
  include/_mgp.hpp
  include/mg_procedure.h
  include/mgp.hpp
  src/dbms/database.hpp
  src/query/db_accessor.cpp
  src/query/db_accessor.hpp
  src/query/interpret/eval.hpp
  src/query/plan/operator.cpp
  src/query/procedure/mg_procedure_impl.cpp
  src/query/procedure/mg_procedure_impl.hpp
  src/query/procedure/py_module.cpp
  src/query/stream/streams.cpp
  src/query/typed_value.cpp
  src/query/typed_value.hpp
  src/storage/v2/edge_accessor.cpp
  src/storage/v2/edge_accessor.hpp
  src/storage/v2/storage.cpp
  src/storage/v2/storage.hpp
  src/storage/v2/storage_mode.cpp
  src/storage/v2/storage_mode.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/query_modules_storage_modes/CMakeLists.txt
  tests/e2e/query_modules_storage_modes/common.py
  tests/e2e/query_modules_storage_modes/query_modules/CMakeLists.txt
  tests/e2e/query_modules_storage_modes/query_modules/c_api.cpp
  tests/e2e/query_modules_storage_modes/query_modules/cpp_api.cpp
  tests/e2e/query_modules_storage_modes/query_modules/python_api.py
  tests/e2e/query_modules_storage_modes/test_query_modules_storage_modes.py
  tests/e2e/query_modules_storage_modes/workloads.yaml
  tests/gql_behave/continuous_integration
  tests/unit/cpp_api.cpp
  tests/unit/query_procedure_mgp_type.cpp
  tests/unit/query_procedure_py_module.cpp
  tests/unit/query_procedures_mgp_graph.cpp
Labels: bug, Ready for review, Docs needed

#1545 Implement parallel constraints recovery
  config/flags.yaml
  src/dbms/inmemory/replication_handlers.cpp
  src/flags/general.cpp
  src/flags/general.hpp
  src/memgraph.cpp
  src/storage/v2/config.hpp
  src/storage/v2/constraints/existence_constraints.cpp
  src/storage/v2/constraints/existence_constraints.hpp
  src/storage/v2/constraints/utils.hpp
  src/storage/v2/disk/edge_import_mode_cache.cpp
  src/storage/v2/disk/edge_import_mode_cache.hpp
  src/storage/v2/disk/label_property_index.hpp
  src/storage/v2/durability/durability.cpp
  src/storage/v2/durability/durability.hpp
  src/storage/v2/durability/metadata.hpp
  src/storage/v2/durability/recovery_type.hpp
  src/storage/v2/indices/indices_utils.hpp
  src/storage/v2/inmemory/label_index.cpp
  src/storage/v2/inmemory/label_index.hpp
  src/storage/v2/inmemory/label_property_index.cpp
  src/storage/v2/inmemory/label_property_index.hpp
  src/storage/v2/inmemory/replication/recovery.cpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/inmemory/unique_constraints.cpp
  src/storage/v2/inmemory/unique_constraints.hpp
  tests/e2e/configuration/configuration_check.py
  tests/e2e/configuration/default_config.py
  tests/unit/storage_v2_durability_inmemory.cpp
Labels: customer

#1492 Relax condition on dealloc mg assert
  src/utils/memory.cpp
Labels: memory, Docs - changelog only

#1397 Fix failing e2e tests in relwithdebinfo mode
  src/query/frontend/ast/cypher_main_visitor.cpp
Labels: Docs unnecessary

#1394 Fix stress test tracker too early failure
  tests/stress/memory_tracker.py
Labels: bug, Docs unnecessary

#1584 Cleanup filesystem after e2e tests
  tests/e2e/interactive_mg_runner.py
  tests/e2e/memgraph.py
  tests/e2e/runner.py
Labels: Docs unnecessary

#1577 Fix java drivers test
  tests/drivers/java/v5_8/run.sh
Labels: Docs unnecessary

#1579 Fix unresolved host errors
  libs/setup.sh
Labels: bug, Docs unnecessary

#1570 Fix memory typo Alloc vs. Free
  src/memory/global_memory_control.cpp
Labels: bug, Docs unnecessary

#1566 Fix memgraph crash on telemetry server and no file permissions
  src/telemetry/telemetry.cpp
  src/utils/stat.hpp
Labels: Docs - changelog only

#1589 Add atomic memory block around unsafe code blocks
  src/storage/v2/edge_accessor.cpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/storage.cpp
  src/storage/v2/vertex_accessor.cpp
  src/utils/atomic_memory_block.hpp
  src/utils/memory_tracker.cpp
  src/utils/memory_tracker.hpp
  tests/stress/memory_limit.py
Labels: memory, Docs - changelog only

#1554 Remove usage of RTLD_DEEPBIND and add PIC
  src/CMakeLists.txt
  src/memgraph.cpp
  src/query/procedure/module.hpp
Labels: bug

#1558 Fix slow python QM (Python GC changes)
  src/flags/general.cpp
  src/flags/general.hpp
  src/memgraph.cpp
  src/query/procedure/py_module.cpp
  src/query/procedure/py_module.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  tests/e2e/configuration/default_config.py
Labels: bug, Ready for review, memory, Docs needed
