Repository memgraph/memgraph, pull requests merged in 2023-01, with the labels that each got.

#730 [master < T1201] Run mgbench diff under 30 min
  tests/mgbench/benchmark.py
  tests/mgbench/graph_bench.py
Labels: infrastructure

#699 [:pineapple: < T1191-MG] Implement CreateExpand with multiframe
  libs/setup.sh
  src/query/v2/multiframe.cpp
  src/query/v2/multiframe.hpp
  src/query/v2/plan/operator.cpp
  src/query/v2/request_router.hpp
  tests/unit/CMakeLists.txt
  tests/unit/mock_helpers.hpp
  tests/unit/query_v2_create_expand_multiframe.cpp
  tests/unit/utils_settings.cpp
Labels: :pineapple:

#717 [master < T517] On delete triggers invalid edge reference
  src/storage/v2/edge_accessor.cpp
  tests/e2e/triggers/CMakeLists.txt
  tests/e2e/triggers/common.py
  tests/e2e/triggers/triggers_properties_false.py
  tests/e2e/triggers/workloads.yaml
Labels: bug, In Progress, v2.5.1

#721 [master < T523-FL] Adding qid in bolt
  src/communication/bolt/client.cpp
  src/communication/bolt/v1/states/handlers.hpp
  tests/integration/transactions/tester.cpp
Labels: v2.5.1

#732 [master < T1220-MG] Fix bug on properties in c++ api
  include/_mgp.hpp
  include/mgp.hpp
  tests/unit/cpp_api.cpp
Labels: bug, v2.5.2

#736 [master < T565-FL] Use indexes in optional match and foreach
  src/query/plan/rewrite/index_lookup.hpp
  src/query/plan/rule_based_planner.hpp
  tests/unit/query_plan.cpp
Labels: bug, In Progress, v2.5.2

#710 [:pineapple: < T1190MG] Implement scan all and scan all by label with multi frame
  src/query/v2/interpreter.cpp
  src/query/v2/multiframe.hpp
  src/query/v2/plan/operator.cpp
Labels: :pineapple:

#737 [master < T569-FL] Allshortest bugfix
  src/query/plan/operator.cpp
  tests/gql_behave/tests/memgraph_V1/features/memgraph_allshortest.feature
Labels: bug, v2.5.2

#743 [master < T323-MAGE] Fix C++ API memory leak on Relationships()
  include/mgp.hpp
  tests/unit/cpp_api.cpp
Labels: bug, v2.5.2, Ready for review

#725 [master < T521-FL] Fix nested FOREACH variable shadowing bug
  src/query/frontend/semantic/symbol_generator.cpp
  src/query/frontend/semantic/symbol_generator.hpp
  tests/gql_behave/tests/memgraph_V1/features/foreach.feature
  tests/unit/query_semantic.cpp
Labels: bug, v2.5.2

#720 [master < T534-FL-torch-mg-load-fix] torch and igraph removing from sys cache
  src/query/procedure/module.cpp
Labels: bug, v2.5.3

#756 [master < T583] Change start time of daily build
  .github/workflows/daily_benchmark.yaml
  .github/workflows/release_centos8.yaml
  .github/workflows/release_debian10.yaml
  .github/workflows/release_ubuntu2004.yaml
Labels: infrastructure
