Repository memgraph/memgraph, pull requests merged in 2023-06, with the labels that each got.

#1015 Add SHOW TRANSACTIONS MultiDB test
  tests/e2e/interactive_mg_runner.py
  tests/e2e/memgraph.py
  tests/e2e/transaction_queue/common.py
  tests/e2e/transaction_queue/test_transaction_queue.py
  tests/setup.sh
Labels: tests

#1016 Refactor tests/integration/run.sh
  .github/workflows/diff.yaml
  .github/workflows/release_centos8.yaml
  .github/workflows/release_debian10.yaml
  .github/workflows/release_ubuntu2004.yaml
  tests/integration/audit/.gitignore
  tests/integration/run.sh
Labels: infrastructure

#773 [master < ] Add cypherl transform script
  import/mglogs2cypherl.sh
  import/n2mg_cypherl.sh
Labels: import

#982 [master < T982] Add mgp any type to C++ query module wrapper
  include/mgp.hpp
Labels: enhancement, Ready for review

#974 [master < T974] Fix init file startup in community edition
  src/CMakeLists.txt
  src/memgraph.cpp
  tests/e2e/CMakeLists.txt
  tests/e2e/init_file_flags/CMakeLists.txt
  tests/e2e/init_file_flags/init_data_file_setup.py
  tests/e2e/init_file_flags/init_file.cypherl
  tests/e2e/init_file_flags/init_file_setup.py
  tests/e2e/init_file_flags/workloads.yaml
  tests/setup.sh
Labels: bug, Ready for review

#916 [master < T916] Fix MATCH + LOAD CSV to load csv only once
  src/query/plan/operator.cpp
  src/query/plan/pretty_print.cpp
  src/query/plan/rewrite/index_lookup.hpp
  src/utils/csv_parsing.cpp
  src/utils/csv_parsing.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/load_csv/CMakeLists.txt
  tests/e2e/load_csv/load_csv.py
  tests/e2e/load_csv/simple.csv
  tests/e2e/load_csv/workloads.yaml
  tests/setup.sh
  tests/unit/utils_csv_parsing.cpp
Labels: bug, enhancement, Status - In Progress

#914 [master < T914] Add command NULLIF for identifying nulls in LOAD CSV
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/frontend/opencypher/grammar/MemgraphCypherLexer.g4
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  src/query/plan/pretty_print.cpp
  src/query/plan/rule_based_planner.hpp
  tests/e2e/load_csv/CMakeLists.txt
  tests/e2e/load_csv/load_csv_nullif.py
  tests/e2e/load_csv/nullif.csv
  tests/e2e/load_csv/workloads.yaml
Labels: enhancement, Status - In Progress

#791 [master < T597] Add restoring of replication roles upon database startup
  src/memgraph.cpp
  src/query/constants.hpp
  src/query/interpreter.cpp
  src/storage/v2/config.hpp
  src/storage/v2/replication/enums.hpp
  src/storage/v2/replication/replication_persistence_helper.cpp
  src/storage/v2/replication/replication_persistence_helper.hpp
  src/storage/v2/storage.cpp
  src/storage/v2/storage.hpp
  src/utils/frame_change_id.hpp
  tests/e2e/replication/show_while_creating_invalid_state.py
  tests/unit/replication_persistence_helper.cpp
  tests/unit/storage_v2_replication.cpp
Labels: bug, Ready for review

#862 Update dependencies under `environment/os`
  environment/README.md
  environment/os/.gitignore
  environment/os/amzn-2.sh
  environment/os/centos-7.sh
  environment/os/centos-9.sh
  environment/os/debian-10.sh
  environment/os/debian-11-arm.sh
  environment/os/debian-11.sh
  environment/os/fedora-36.sh
  environment/os/run.sh
  environment/os/template.sh
  environment/os/ubuntu-18.04.sh
  environment/os/ubuntu-20.04.sh
  environment/os/ubuntu-22.04-arm.sh
  environment/os/ubuntu-22.04.sh
  environment/util.sh
  init
  release/package/run.sh
Labels: infrastructure

#863 Improve libstdc++ dependency
  config/generate.py
  libs/CMakeLists.txt
  release/CMakeLists.txt
  src/query/procedure/module.hpp
Labels: bug

#1032 Update release/docker/package_docker
  release/docker/package_docker
Labels: infrastructure

#966 [Master < Issue 925] Add check for opening snapshots
  src/storage/v2/durability/durability.cpp
  src/storage/v2/durability/snapshot.cpp
  src/utils/file.cpp
  src/utils/file.hpp
Labels: Ready for review

#930 [master <] Fix replica exception message
  src/query/exceptions.hpp
Labels: documentation, Ready for review, high-availability

#816 [master<] Adding information about CSV import tool errors
  docs/csv-import-tool/README.md
Labels: Ready for review

#1040 Fix package workflow
  environment/os/debian-11-arm.sh
  environment/os/ubuntu-22.04-arm.sh
Labels: infrastructure

#1038 Improve build setup when memgraph is a git submodule
  CMakeLists.txt
  init
Labels: infrastructure

#964 [master < ] Add python & cpp batching
  include/_mgp.hpp
  include/mg_procedure.h
  include/mgp.hpp
  include/mgp.py
  src/query/interpreter.cpp
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  src/query/procedure/mg_procedure_impl.cpp
  src/query/procedure/mg_procedure_impl.hpp
  src/query/procedure/py_module.cpp
  tests/e2e/CMakeLists.txt
  tests/e2e/batched_procedures/CMakeLists.txt
  tests/e2e/batched_procedures/__init__.py
  tests/e2e/batched_procedures/common.py
  tests/e2e/batched_procedures/conftest.py
  tests/e2e/batched_procedures/procedures/CMakeLists.txt
  tests/e2e/batched_procedures/procedures/batch_c_read.cpp
  tests/e2e/batched_procedures/procedures/batch_py_read.py
  tests/e2e/batched_procedures/procedures/batch_py_write.py
  tests/e2e/batched_procedures/procedures/common/CMakeLists.txt
  tests/e2e/batched_procedures/procedures/common/shared.py
  tests/e2e/batched_procedures/simple_read.py
  tests/e2e/batched_procedures/workloads.yaml
Labels: Ready for review

#1027 [master < T0849] Add HTTP+GZIP support to LOAD CSV
  CMakeLists.txt
  libs/CMakeLists.txt
  libs/setup.sh
  src/CMakeLists.txt
  src/csv/CMakeLists.txt
  src/csv/fuzz/CMakeLists.txt
  src/csv/fuzz/fuzz_reader.cpp
  src/csv/include/csv/parsing.hpp
  src/csv/parsing.cpp
  src/query/CMakeLists.txt
  src/query/interpreter.cpp
  src/query/plan/operator.cpp
  src/requests/CMakeLists.txt
  src/requests/requests.cpp
  src/requests/requests.hpp
  src/utils/CMakeLists.txt
  src/utils/on_scope_exit.hpp
  tests/unit/CMakeLists.txt
  tests/unit/csv_csv_parsing.cpp
  tests/unit/interpreter.cpp
Labels: enhancement

#1012 [master < T1012] Close connection in e2e tests after setup queries
  tests/e2e/interactive_mg_runner.py
  tests/e2e/memgraph.py
  tests/e2e/runner.py
Labels: bug

#1039 [master < T1039] Fix map at operator returning null from a map
  include/mgp.hpp
Labels: bug, Ready for review

#1030 [master < I953 ] Improve replication logging.
  src/storage/v2/replication/replication_client.cpp
  src/storage/v2/replication/replication_server.cpp
  src/storage/v2/storage.cpp
Labels: Ready for review, high-availability

#1026 [master < T1026] Add vertex degree to index statistics
  src/query/constants.hpp
  src/query/db_accessor.hpp
  src/query/frontend/semantic/symbol_generator.cpp
  src/query/frontend/semantic/symbol_generator.hpp
  src/query/interpreter.cpp
  src/query/plan/cost_estimator.hpp
  src/query/plan/planner.hpp
  src/query/plan/rewrite/index_lookup.hpp
  src/query/plan/vertex_count_cache.hpp
  src/storage/v2/indices.cpp
  src/storage/v2/indices.hpp
  src/storage/v2/storage.hpp
  tests/benchmark/query/planner.cpp
  tests/e2e/analyze_graph/common.py
  tests/e2e/analyze_graph/optimize_indexes.py
  tests/manual/interactive_planning.cpp
  tests/unit/query_cost_estimator.cpp
  tests/unit/query_plan_checker.hpp
  tests/unit/query_semantic.cpp
Labels: enhancement, Status - In Progress
