Repository memgraph/memgraph, pull requests merged in 2023-07, with the labels that each got.

#1061 Fix Jepsen replication test issue
  .github/workflows/diff.yaml
  .github/workflows/release_centos8.yaml
  .github/workflows/release_debian10.yaml
  .github/workflows/release_ubuntu2004.yaml
  src/memgraph.cpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/replication/replication_client.cpp
  tests/e2e/README.md
  tests/e2e/configuration/default_config.py
  tests/e2e/interactive_mg_runner.py
  tests/e2e/memgraph.py
  tests/e2e/replication/show_while_creating_invalid_state.py
  tests/e2e/run.sh
  tests/e2e/run_e2e.sh
  tests/e2e/transaction_queue/workloads.yaml
  tests/jepsen/README.md
  tests/jepsen/jepsen_0.3.0.patch
  tests/jepsen/project.clj
  tests/jepsen/run.sh
  tests/jepsen/src/jepsen/memgraph/core.clj
  tests/jepsen/src/jepsen/memgraph/nemesis.clj
  tests/jepsen/src/jepsen/memgraph/support.clj
Labels: bug, infrastructure, tests

#1079 [master<] Proposed exceptions and warnings for on-disk mode
  src/query/exceptions.hpp
  src/query/interpreter.cpp
Labels: enhancement

#1077 [master < T1077] Fix flaky tx-queue-multiple test
  tests/unit/transaction_queue_multiple.cpp
Labels: bug

#1044 Fix custom maven setup
  environment/os/amzn-2.sh
  environment/os/centos-7.sh
  environment/os/centos-9.sh
  environment/os/debian-10.sh
  environment/os/debian-11-arm.sh
  environment/os/debian-11.sh
  environment/os/fedora-36.sh
  environment/os/ubuntu-18.04.sh
  environment/os/ubuntu-20.04.sh
  environment/os/ubuntu-22.04-arm.sh
  environment/os/ubuntu-22.04.sh
  environment/util.sh
Labels: infrastructure

#1096 [master <] Improve init script logging
  libs/setup.sh
Labels: infrastructure

#1060 Add package/release/run.sh build v4 debian-10
  release/package/amzn-2/Dockerfile
  release/package/centos-7/Dockerfile
  release/package/centos-9/Dockerfile
  release/package/debian-10/Dockerfile
  release/package/debian-11-arm/Dockerfile
  release/package/debian-11/Dockerfile
  release/package/fedora-36/Dockerfile
  release/package/run.sh
  release/package/ubuntu-18.04/Dockerfile
  release/package/ubuntu-20.04/Dockerfile
  release/package/ubuntu-22.04-arm/Dockerfile
  release/package/ubuntu-22.04/Dockerfile
Labels: infrastructure

#1098 Add macOS support under environment/util.sh:operating_system
  environment/util.sh
  release/package/ubuntu-22.04/Dockerfile
Labels: infrastructure

#866 [master < ] Add standalone upload to S3 workflow
  .github/workflows/package_all.yaml
  .github/workflows/upload_to_s3.yaml
Labels: infrastructure

#1080 [master < T1080] overload << operator for mgp::Type
  include/mgp.hpp
  tests/unit/cpp_api.cpp
Labels: Ship it

#1094 [master < T1094] Extend insert on record to accept mgp::Value
  include/mgp.hpp
Labels: Ship it

#1093 [master < T570] Implement hash on mgp::Value
  include/_mgp.hpp
  include/mgp.hpp
  tests/unit/cpp_api.cpp
Labels: enhancement, Ship it

#1090 [master < T1090] Add overload for operator< in mgp::Value
  include/mgp.hpp
  tests/unit/cpp_api.cpp
Labels: Ship it

#1099 [master < T1099] Add non-const mgp::Value return type for C++ API
  include/mgp.hpp
Labels: Ship it

#1102 [master < T1102] Fix flaky e2e tx queue test
  tests/e2e/transaction_queue/test_transaction_queue.py
Labels: bug, infrastructure

#1108 [master < ] Bugfix: Path generation ignores edge's element_id
  src/communication/bolt/v1/value.hpp
  tests/drivers/python/v5_8/path.py
  tests/drivers/python/v5_8/run.sh
Labels: bug, bolt

#1111 [master < T1111] Fix local buffer serialization
  src/storage/v2/property_store.cpp
  tests/unit/storage_rocks.cpp
Labels: bug

#1088 [master < T1088] Set explicit node config for jepsen tests
  tests/jepsen/resources/node-config.edn
  tests/jepsen/src/jepsen/memgraph/core.clj
Labels: enhancement

#1082 [master < T1082] Jepsen - pause nemesis work until replica registration is done
  src/storage/v2/replication/replication_server.cpp
  tests/jepsen/run.sh
  tests/jepsen/src/jepsen/memgraph/nemesis.clj
Labels: enhancement, infrastructure, tests

#1103 [master < T577] Add mgp::map erase and update
  include/_mgp.hpp
  include/mg_procedure.h
  include/mgp.hpp
  src/query/procedure/mg_procedure_impl.cpp
  tests/unit/cpp_api.cpp
Labels: enhancement, Ready for review

#1046 [master <] Handle partial results on timeout
  .gitignore
  include/_mgp.hpp
  include/mg_procedure.h
  include/mgp.hpp
  src/communication/bolt/v1/codes.hpp
  src/communication/bolt/v1/session.hpp
  src/communication/bolt/v1/states/executing.hpp
  src/communication/bolt/v1/states/handlers.hpp
  src/memgraph.cpp
  src/query/context.hpp
  src/query/exceptions.hpp
  src/query/interpreter.cpp
  src/query/interpreter.hpp
  src/query/plan/operator.cpp
  src/query/procedure/mg_procedure_impl.cpp
  src/query/trigger.cpp
  tests/manual/js/transaction_timeout/README.md
  tests/manual/js/transaction_timeout/auto-transaction.ts
  tests/manual/js/transaction_timeout/explicit-transaction.ts
  tests/manual/js/transaction_timeout/package.json
  tests/unit/bolt_session.cpp
Labels: enhancement

#981 [master < T981] Reduce all shortest paths memory usage
  src/query/cypher_query_interpreter.cpp
  src/query/cypher_query_interpreter.hpp
  src/query/interpret/eval.hpp
  src/query/interpreter.cpp
  tests/unit/cpp_api.cpp
Labels: enhancement, benchmarking

#1112 Fix a bunch of spelling mistakes (1/n)
  CMakeLists.txt
  release/CMakeLists.txt
  src/query/db_accessor.hpp
  src/query/interpret/awesome_memgraph_functions.cpp
  src/query/stream/streams.hpp
  src/utils/file_locker.hpp
  src/utils/memory_tracker.cpp
  src/utils/temporal.cpp
  tests/e2e/interactive_mg_runner.py
  tests/manual/interactive_planning.cpp
  tests/mgbench/benchmark.py
  tests/mgbench/client.cpp
  tests/stress/durability
  tests/unit/cypher_main_visitor.cpp
  tests/unit/formatters.hpp
  tests/unit/query_plan.cpp
  tests/unit/storage_v2_replication.cpp
  tools/github/cppcheck_and_clang_format
Labels: Impact - LOW, Effort - LOW

#771 [master < ] Add more info to the query modules error messages
  include/mg_exceptions.hpp
  include/mgp.hpp
Labels: community

#1091 [master < T1091] Remove node argument from start-stop functions
  tests/jepsen/src/jepsen/memgraph/support.clj
Labels: enhancement
