Repository memgraph/memgraph, pull requests merged in 2023-03, with the labels that each got.

#810 [master < MG-ubuntu-22.04] Support ubuntu 22.04 arm
  .github/workflows/package_all.yaml
  environment/os/ubuntu-22.04-arm.sh
  environment/toolchain/v4.sh
  environment/util.sh
  release/package/arm-builders.yml
  release/package/run.sh
  release/package/ubuntu-22.04-arm/Dockerfile
Labels: infrastructure

#811 [T1238 < T1247] Add exceptions for unimplemented EXISTS query parts
  src/query/frontend/semantic/symbol_generator.cpp
  src/query/frontend/semantic/symbol_generator.hpp
  src/query/plan/rule_based_planner.cpp
  tests/gql_behave/tests/memgraph_V1/features/memgraph_exists.feature
Labels: enhancement, Ship it

#803 [T1236 < T1238] Make where exists insensitive to variable positions and multihop
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/pretty_print.cpp
  src/query/frontend/semantic/symbol_generator.cpp
  src/query/frontend/semantic/symbol_generator.hpp
  src/query/plan/operator.cpp
  src/query/plan/pretty_print.cpp
  src/query/plan/pretty_print.hpp
  src/query/plan/rewrite/index_lookup.hpp
  src/query/plan/rule_based_planner.cpp
  src/query/plan/rule_based_planner.hpp
  src/query/plan/variable_start_planner.cpp
  src/query/plan/variable_start_planner.hpp
  tests/gql_behave/tests/memgraph_V1/features/memgraph_exists.feature
  tests/unit/cypher_main_visitor.cpp
  tests/unit/plan_pretty_print.cpp
  tests/unit/query_plan_checker.hpp
  tests/unit/query_semantic.cpp
Labels: enhancement, Ship it

#764 [T1234 < T1236] Add filtering support to WHERE EXISTS
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/pretty_print.cpp
  src/query/frontend/semantic/symbol_generator.cpp
  src/query/frontend/semantic/symbol_generator.hpp
  src/query/plan/operator.cpp
  src/query/plan/operator.lcp
  src/query/plan/preprocess.cpp
  src/query/plan/preprocess.hpp
  src/query/plan/pretty_print.cpp
  src/query/plan/pretty_print.hpp
  src/query/plan/rewrite/index_lookup.hpp
  src/query/plan/rule_based_planner.cpp
  src/query/plan/rule_based_planner.hpp
  src/query/plan/variable_start_planner.cpp
  src/query/plan/variable_start_planner.hpp
  tests/gql_behave/tests/memgraph_V1/features/memgraph_exists.feature
  tests/unit/cypher_main_visitor.cpp
  tests/unit/plan_pretty_print.cpp
  tests/unit/query_cost_estimator.cpp
  tests/unit/query_plan.cpp
  tests/unit/query_plan_checker.hpp
  tests/unit/query_plan_create_set_remove_delete.cpp
  tests/unit/query_plan_match_filter_return.cpp
  tests/unit/query_plan_read_write_typecheck.cpp
  tests/unit/query_semantic.cpp
Labels: enhancement, Ship it

#819 Remove noexcept from functions that may throw
  src/query/procedure/mg_procedure_impl.hpp
  tests/unit/cpp_api.cpp
Labels: bug, Ready for review

#786 [master < ] Update incompatible epoch_id error
  src/storage/v2/replication/replication_client.cpp
Labels: documentation, enhancement

#765 [T1233 < T1234] Add execution logic of WHERE EXISTS
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/pretty_print.cpp
  src/query/frontend/semantic/symbol_generator.cpp
  src/query/frontend/semantic/symbol_generator.hpp
  src/query/interpret/eval.hpp
  src/query/plan/operator.cpp
  src/query/plan/operator.lcp
  src/query/plan/preprocess.cpp
  src/query/plan/preprocess.hpp
  src/query/plan/pretty_print.cpp
  src/query/plan/pretty_print.hpp
  src/query/plan/rewrite/index_lookup.hpp
  src/query/plan/rule_based_planner.cpp
  src/query/plan/rule_based_planner.hpp
  src/query/plan/variable_start_planner.cpp
  src/query/plan/variable_start_planner.hpp
  tests/gql_behave/tests/memgraph_V1/features/memgraph_exists.feature
  tests/unit/cypher_main_visitor.cpp
  tests/unit/plan_pretty_print.cpp
  tests/unit/query_cost_estimator.cpp
  tests/unit/query_plan.cpp
  tests/unit/query_plan_checker.hpp
  tests/unit/query_plan_create_set_remove_delete.cpp
  tests/unit/query_plan_match_filter_return.cpp
  tests/unit/query_plan_read_write_typecheck.cpp
  tests/unit/query_semantic.cpp
Labels: enhancement, Ship it

#818 [master < E214] WHERE Exists feature
  src/query/frontend/ast/ast.lcp
  src/query/frontend/ast/ast_visitor.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/ast/pretty_print.cpp
  src/query/frontend/opencypher/grammar/Cypher.g4
  src/query/frontend/semantic/symbol_generator.cpp
  src/query/frontend/semantic/symbol_generator.hpp
  src/query/frontend/semantic/symbol_table.hpp
  src/query/interpret/eval.hpp
  src/query/plan/operator.cpp
  src/query/plan/operator.lcp
  src/query/plan/preprocess.cpp
  src/query/plan/preprocess.hpp
  src/query/plan/pretty_print.cpp
  src/query/plan/pretty_print.hpp
  src/query/plan/rewrite/index_lookup.hpp
  src/query/plan/rule_based_planner.cpp
  src/query/plan/rule_based_planner.hpp
  src/query/plan/variable_start_planner.cpp
  src/query/plan/variable_start_planner.hpp
  src/utils/event_counter.cpp
  tests/gql_behave/tests/memgraph_V1/features/memgraph_exists.feature
  tests/unit/cypher_main_visitor.cpp
  tests/unit/plan_pretty_print.cpp
  tests/unit/query_common.hpp
  tests/unit/query_cost_estimator.cpp
  tests/unit/query_plan.cpp
  tests/unit/query_plan_checker.hpp
  tests/unit/query_plan_create_set_remove_delete.cpp
  tests/unit/query_plan_match_filter_return.cpp
  tests/unit/query_plan_read_write_typecheck.cpp
  tests/unit/query_pretty_print.cpp
  tests/unit/query_semantic.cpp
Labels: enhancement, In Progress

#757 [master < E056-MAGE] Mock graph APIs
  include/_mgp_mock.py
  include/mgp_mock.py
  src/CMakeLists.txt
  tests/e2e/CMakeLists.txt
  tests/e2e/mock_api/CMakeLists.txt
  tests/e2e/mock_api/common.py
  tests/e2e/mock_api/procedures/CMakeLists.txt
  tests/e2e/mock_api/procedures/edge.py
  tests/e2e/mock_api/procedures/edge_type.py
  tests/e2e/mock_api/procedures/graph.py
  tests/e2e/mock_api/procedures/label.py
  tests/e2e/mock_api/procedures/path.py
  tests/e2e/mock_api/procedures/properties.py
  tests/e2e/mock_api/procedures/record.py
  tests/e2e/mock_api/procedures/test_utils.py
  tests/e2e/mock_api/procedures/vertex.py
  tests/e2e/mock_api/procedures/vertices.py
  tests/e2e/mock_api/test_compare_mock.py
  tests/e2e/mock_api/workloads.yaml
  tests/setup.sh
  tools/requirements.txt
Labels: enhancement, Ready for review

#805 Time depended execution mgbench client
  tests/mgbench/client.cpp
Labels: Ready for review, benchmarking

#747 [master < T1177-MG] Add bigger dataset LDBC
  tests/mgbench/README.md
  tests/mgbench/benchmark.py
  tests/mgbench/benchmark_context.py
  tests/mgbench/client.cpp
  tests/mgbench/compare_results.py
  tests/mgbench/cypher/__init__.py
  tests/mgbench/cypher/ldbc_to_cypher.py
  tests/mgbench/graph_bench.py
  tests/mgbench/helpers.py
  tests/mgbench/log.py
  tests/mgbench/runners.py
  tests/mgbench/validation.py
  tests/mgbench/workloads/__init__.py
  tests/mgbench/workloads/base.py
  tests/mgbench/workloads/demo.py
  tests/mgbench/workloads/importers/__init__.py
  tests/mgbench/workloads/importers/importer_ldbc_bi.py
  tests/mgbench/workloads/importers/importer_ldbc_interactive.py
  tests/mgbench/workloads/importers/importer_pokec.py
  tests/mgbench/workloads/ldbc_bi.py
  tests/mgbench/workloads/ldbc_interactive.py
  tests/mgbench/workloads/pokec.py
Labels: benchmarking

#820 [T1245 < T1248] Add subquery planner and execution
  src/query/frontend/ast/ast.lcp
  src/query/frontend/ast/ast_visitor.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/frontend/semantic/required_privileges.cpp
  src/query/frontend/semantic/symbol_generator.cpp
  src/query/frontend/semantic/symbol_generator.hpp
  src/query/plan/cost_estimator.hpp
  src/query/plan/operator.cpp
  src/query/plan/operator.lcp
  src/query/plan/planner.hpp
  src/query/plan/preprocess.cpp
  src/query/plan/preprocess.hpp
  src/query/plan/pretty_print.cpp
  src/query/plan/pretty_print.hpp
  src/query/plan/rewrite/index_lookup.hpp
  src/query/plan/rule_based_planner.cpp
  src/query/plan/rule_based_planner.hpp
  src/query/plan/variable_start_planner.hpp
  src/utils/event_counter.cpp
  tests/benchmark/query/planner.cpp
  tests/gql_behave/tests/memgraph_V1/features/subqueries.feature
  tests/manual/interactive_planning.cpp
  tests/unit/cypher_main_visitor.cpp
  tests/unit/query_common.hpp
  tests/unit/query_cost_estimator.cpp
  tests/unit/query_plan.cpp
  tests/unit/query_plan_checker.hpp
  tests/unit/query_plan_match_filter_return.cpp
  tests/unit/query_semantic.cpp
  tests/unit/query_variable_start_planner.cpp
Labels: enhancement, In Progress

#840 Upgrade pre-commit hook
  .pre-commit-config.yaml
  init
Labels: infrastructure

#838 #557: Add CPU architecture detection to CMake
  CMakeLists.txt
Labels: infrastructure

#790 [master < T577] Transactional queue
  include/mgp.hpp
  src/auth/models.cpp
  src/auth/models.hpp
  src/glue/auth.cpp
  src/glue/auth_checker.cpp
  src/glue/auth_checker.hpp
  src/memgraph.cpp
  src/query/auth_checker.hpp
  src/query/context.hpp
  src/query/exceptions.hpp
  src/query/frontend/ast/ast.cpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/ast.lcp
  src/query/frontend/ast/ast_visitor.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/frontend/opencypher/grammar/MemgraphCypherLexer.g4
  src/query/frontend/semantic/required_privileges.cpp
  src/query/interpreter.cpp
  src/query/interpreter.hpp
  src/query/stream/streams.cpp
  src/query/trigger.cpp
  src/query/trigger.hpp
  src/storage/v2/constraints.cpp
  src/storage/v2/mvcc.hpp
  src/storage/v2/storage.cpp
  src/storage/v2/storage.hpp
  src/storage/v2/transaction.hpp
  src/utils/typeinfo.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/lba_procedures/show_privileges.py
  tests/e2e/transaction_queue/CMakeLists.txt
  tests/e2e/transaction_queue/common.py
  tests/e2e/transaction_queue/procedures/CMakeLists.txt
  tests/e2e/transaction_queue/procedures/infinite_query.py
  tests/e2e/transaction_queue/test_transaction_queue.py
  tests/e2e/transaction_queue/workloads.yaml
  tests/unit/CMakeLists.txt
  tests/unit/interpreter.cpp
  tests/unit/interpreter_faker.hpp
  tests/unit/query_trigger.cpp
  tests/unit/transaction_queue.cpp
  tests/unit/transaction_queue_multiple.cpp
Labels: enhancement, Ship it

#831 [🍍 < ] Add id to Frame
  src/expr/interpret/eval.hpp
  src/expr/interpret/frame.hpp
  src/query/v2/plan/operator.cpp
  src/query/v2/plan/operator.lcp
  tests/unit/query_v2_create_expand_multiframe.cpp
Labels: :pineapple:

#719 [:pineapple: < MG-T1149] Implement shard split on storage side
  src/coordinator/hybrid_logical_clock.hpp
  src/query/v2/requests.hpp
  src/storage/v3/CMakeLists.txt
  src/storage/v3/config.hpp
  src/storage/v3/delta.hpp
  src/storage/v3/indices.cpp
  src/storage/v3/indices.hpp
  src/storage/v3/mvcc.hpp
  src/storage/v3/shard.cpp
  src/storage/v3/shard.hpp
  src/storage/v3/shard_rsm.hpp
  src/storage/v3/splitter.cpp
  src/storage/v3/splitter.hpp
  src/storage/v3/transaction.hpp
  tests/benchmark/CMakeLists.txt
  tests/benchmark/storage_v3_split.cpp
  tests/benchmark/storage_v3_split_1.cpp
  tests/benchmark/storage_v3_split_2.cpp
  tests/unit/CMakeLists.txt
  tests/unit/storage_v3_shard_split.cpp
Labels: :pineapple:

#832 [master < T606-FL] Fix AllShortest multiple edges between nodes
  src/query/plan/operator.cpp
  tests/gql_behave/tests/memgraph_V1/features/memgraph_allshortest.feature
Labels: bug, In Progress

#794 [E216 < T1245] Add subqueries
  src/query/frontend/ast/ast.cpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/ast.lcp
  src/query/frontend/ast/ast_visitor.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/frontend/opencypher/grammar/MemgraphCypherLexer.g4
  src/query/frontend/semantic/required_privileges.cpp
  src/query/frontend/semantic/symbol_generator.cpp
  src/query/frontend/semantic/symbol_generator.hpp
  src/query/plan/cost_estimator.hpp
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  src/query/plan/operator.lcp
  src/query/plan/operator_type_info.cpp
  src/query/plan/planner.hpp
  src/query/plan/preprocess.cpp
  src/query/plan/preprocess.hpp
  src/query/plan/pretty_print.cpp
  src/query/plan/pretty_print.hpp
  src/query/plan/rewrite/index_lookup.hpp
  src/query/plan/rule_based_planner.cpp
  src/query/plan/rule_based_planner.hpp
  src/query/plan/variable_start_planner.hpp
  src/utils/event_counter.cpp
  src/utils/typeinfo.hpp
  tests/benchmark/query/planner.cpp
  tests/gql_behave/tests/memgraph_V1/features/subqueries.feature
  tests/manual/interactive_planning.cpp
  tests/unit/cypher_main_visitor.cpp
  tests/unit/query_common.hpp
  tests/unit/query_cost_estimator.cpp
  tests/unit/query_plan.cpp
  tests/unit/query_plan_checker.hpp
  tests/unit/query_plan_match_filter_return.cpp
  tests/unit/query_semantic.cpp
  tests/unit/query_variable_start_planner.cpp
Labels: enhancement, Ready for review

#851 [master < E216] Add subqueries
  src/query/frontend/ast/ast.cpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/ast.lcp
  src/query/frontend/ast/ast_visitor.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/frontend/opencypher/grammar/MemgraphCypherLexer.g4
  src/query/frontend/semantic/required_privileges.cpp
  src/query/frontend/semantic/symbol_generator.cpp
  src/query/frontend/semantic/symbol_generator.hpp
  src/query/plan/cost_estimator.hpp
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  src/query/plan/operator.lcp
  src/query/plan/operator_type_info.cpp
  src/query/plan/planner.hpp
  src/query/plan/preprocess.cpp
  src/query/plan/preprocess.hpp
  src/query/plan/pretty_print.cpp
  src/query/plan/pretty_print.hpp
  src/query/plan/rewrite/index_lookup.hpp
  src/query/plan/rule_based_planner.cpp
  src/query/plan/rule_based_planner.hpp
  src/query/plan/variable_start_planner.hpp
  src/utils/event_counter.cpp
  src/utils/typeinfo.hpp
  tests/benchmark/query/planner.cpp
  tests/gql_behave/tests/memgraph_V1/features/subqueries.feature
  tests/manual/interactive_planning.cpp
  tests/unit/cypher_main_visitor.cpp
  tests/unit/query_common.hpp
  tests/unit/query_cost_estimator.cpp
  tests/unit/query_plan.cpp
  tests/unit/query_plan_checker.hpp
  tests/unit/query_plan_match_filter_return.cpp
  tests/unit/query_semantic.cpp
  tests/unit/query_variable_start_planner.cpp
Labels: enhancement, Ready for review
