Repository memgraph/memgraph, pull requests merged in 2023-09, with the labels that each got.

#1187 [master <] Introduce a reader writer spin lock
  src/glue/communication.cpp
  src/storage/v2/durability/snapshot.cpp
  src/storage/v2/durability/wal.cpp
  src/storage/v2/edge.hpp
  src/storage/v2/edge_accessor.cpp
  src/storage/v2/indices/indices_utils.hpp
  src/storage/v2/inmemory/replication/replication_server.cpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/unique_constraints.cpp
  src/storage/v2/vertex.hpp
  src/storage/v2/vertex_accessor.cpp
  src/utils/rw_spin_lock.hpp
Labels: enhancement, benchmarking

#1131 [master < T1131] Set properties C API extension
  include/_mgp.hpp
  include/mg_procedure.h
  include/mgp.hpp
  include/mgp.py
  src/query/db_accessor.hpp
  src/query/procedure/mg_procedure_impl.cpp
  src/query/procedure/py_module.cpp
  tests/e2e/CMakeLists.txt
  tests/e2e/set_properties/CMakeLists.txt
  tests/e2e/set_properties/common.py
  tests/e2e/set_properties/procedures/CMakeLists.txt
  tests/e2e/set_properties/procedures/set_properties_module.py
  tests/e2e/set_properties/set_properties.py
  tests/e2e/set_properties/workloads.yaml
  tests/unit/cpp_api.cpp
Labels: enhancement, Ready for review

#1085 [master < T1085] Remove double scan with expand from the planner
  src/query/plan/rewrite/index_lookup.hpp
  tests/unit/query_plan.cpp
Labels: enhancement

#1157 [master < T1157] Edge import mode
  src/query/exceptions.hpp
  src/query/frontend/ast/ast.cpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/ast_visitor.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/frontend/opencypher/grammar/MemgraphCypherLexer.g4
  src/query/frontend/semantic/required_privileges.cpp
  src/query/frontend/stripped_lexer_constants.hpp
  src/query/interpreter.cpp
  src/storage/v2/CMakeLists.txt
  src/storage/v2/disk/edge_import_mode_cache.cpp
  src/storage/v2/disk/edge_import_mode_cache.hpp
  src/storage/v2/disk/label_index.cpp
  src/storage/v2/disk/label_index.hpp
  src/storage/v2/disk/label_property_index.cpp
  src/storage/v2/disk/label_property_index.hpp
  src/storage/v2/disk/rocksdb_storage.cpp
  src/storage/v2/disk/rocksdb_storage.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/edge_accessor.cpp
  src/storage/v2/edge_accessor.hpp
  src/storage/v2/edge_import_mode.hpp
  src/storage/v2/indices/indices.cpp
  src/storage/v2/indices/indices.hpp
  src/storage/v2/indices/label_index.hpp
  src/storage/v2/indices/label_property_index.hpp
  src/storage/v2/inmemory/label_index.cpp
  src/storage/v2/inmemory/label_index.hpp
  src/storage/v2/inmemory/label_property_index.cpp
  src/storage/v2/inmemory/label_property_index.hpp
  src/storage/v2/inmemory/replication/replication_server.cpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/modified_edge.hpp
  src/storage/v2/mvcc.hpp
  src/storage/v2/storage.cpp
  src/storage/v2/transaction.hpp
  src/storage/v2/vertex_accessor.cpp
  src/utils/disk_utils.hpp
  src/utils/rocksdb_serialization.hpp
  src/utils/typeinfo.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/import_mode/CMakeLists.txt
  tests/e2e/import_mode/common.py
  tests/e2e/import_mode/test_command.py
  tests/e2e/import_mode/workloads.yaml
  tests/unit/storage_v2_wal_file.cpp
Labels: enhancement, on disk

#1147 [master < T1147 ] Improve NameToId mapper on set properties
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
Labels: Ready for review

#1129 [master < T1129] Improve performance of delta creation
  src/query/stream/streams.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/inmemory/unique_constraints.cpp
  src/storage/v2/mvcc.hpp
  src/storage/v2/storage.cpp
  src/storage/v2/transaction.hpp
  src/utils/bond.hpp
  src/utils/memory_tracker.cpp
  src/utils/temporal.cpp
  tests/unit/formatters.hpp
  tests/unit/storage_v2_wal_file.cpp
Labels: memory

#1054 Remove repeated log lines from TRACE log level.
  src/storage/v2/durability/snapshot.cpp
Labels: Ready for review

#1217 [master < T1217] Implement InDegree and OutDegree in O(1)
  include/_mgp.hpp
  include/mg_procedure.h
  include/mgp.hpp
  src/query/db_accessor.hpp
  src/query/procedure/mg_procedure_impl.cpp
  tests/unit/cpp_api.cpp
Labels: Ready for review

#1225 [master < T1225] Fix bug on mgp dispatcher guard
  include/mgp.hpp
Labels: bug, Ready for review

#1210 [master < T367-MAGE] Add traits under list iterator
  include/mgp.hpp
Labels: Ready for review

#1221 [master < T1219] Implement changing from and to vertices in relationships
  include/_mgp.hpp
  include/mg_procedure.h
  include/mgp.hpp
  src/query/db_accessor.cpp
  src/query/db_accessor.hpp
  src/query/procedure/mg_procedure_impl.cpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/storage.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/transaction_rollback/CMakeLists.txt
  tests/e2e/transaction_rollback/common.py
  tests/e2e/transaction_rollback/conftest.py
  tests/e2e/transaction_rollback/procedures/CMakeLists.txt
  tests/e2e/transaction_rollback/procedures/procedures.cpp
  tests/e2e/transaction_rollback/transaction.py
  tests/e2e/transaction_rollback/workloads.yaml
  tests/unit/cpp_api.cpp
Labels: enhancement, Ship it

#1209 [master < T1209] Fix API bug on accessing deleted object
  src/query/db_accessor.hpp
  src/query/procedure/mg_procedure_impl.cpp
  src/storage/v2/edge_accessor.cpp
  src/storage/v2/edge_accessor.hpp
  tests/e2e/triggers/on_delete_triggers.cpp
  tests/e2e/triggers/procedures/write.py
Labels: bug

#1175 [master < ] Fix segfault based on issue #874
  src/query/plan/operator.cpp
Labels: bug, Ready for review

#1119 [master < T1119] Return NULL on map projection from a null value
  src/query/frontend/ast/ast.hpp
  src/query/interpret/eval.hpp
  src/query/plan/rule_based_planner.cpp
  tests/gql_behave/tests/memgraph_V1/features/map_projection.feature
Labels: bug, Ready for review

#1142 [master <] Optimise RemoveObsoleteEntries
  src/storage/v2/indices/indices_utils.hpp
  src/storage/v2/inmemory/unique_constraints.cpp
  src/storage/v2/property_store.cpp
Labels: optimization

#1227 [master < T1227] Optimise iteration
  src/query/db_accessor.hpp
  src/query/plan/operator.cpp
  src/storage/v2/all_vertices_iterable.cpp
  src/storage/v2/all_vertices_iterable.hpp
  src/storage/v2/inmemory/label_index.hpp
  src/storage/v2/inmemory/label_property_index.hpp
  src/storage/v2/vertex_accessor.cpp
  src/storage/v2/vertex_accessor.hpp
  src/storage/v2/vertices_iterable.cpp
  src/storage/v2/vertices_iterable.hpp
Labels: optimization

#1078 Improve bulk detach delete
  .github/workflows/diff.yaml
  .pre-commit-config.yaml
  src/query/db_accessor.hpp
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/edge_ref.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/storage.cpp
  src/storage/v2/storage.hpp
  tests/gql_behave/tests/memgraph_V1/features/delete.feature
  tests/stress/bipartite.py
  tests/stress/common.py
  tests/stress/continuous_integration
  tests/stress/create_match.py
  tests/stress/detach_delete.py
  tests/stress/durability
  tests/stress/long_running.cpp
  tests/stress/parser.cpp
  tests/stress/requirements.txt
  tests/stress/test_config.py
  tests/unit/interpreter.cpp
  tests/unit/query_plan_create_set_remove_delete.cpp
Labels: enhancement, Status - In Progress

#1178 [master < T1178] Sort SHOW INDEX INFO
  src/query/interpreter.cpp
  tests/e2e/CMakeLists.txt
  tests/e2e/show_index_info/CMakeLists.txt
  tests/e2e/show_index_info/common.py
  tests/e2e/show_index_info/test_show_index_info.py
  tests/e2e/show_index_info/workloads.yaml
Labels: enhancement, Ready for review

#1168 [master < T1168] Property lookup caching
  src/query/context.hpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/semantic/symbol_generator.cpp
  src/query/frontend/semantic/symbol_generator.hpp
  src/query/interpret/eval.hpp
  tests/gql_behave/tests/memgraph_V1/features/map.feature
  tests/unit/query_plan_create_set_remove_delete.cpp
  tests/unit/query_semantic.cpp
Labels: enhancement, Ship it

#1204 [master < T1204] Add detailed operator info to PROFILE and EXPLAIN
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  src/query/plan/pretty_print.cpp
  src/query/plan/profile.cpp
  src/query/plan/profile.hpp
  src/query/plan/scoped_profile.hpp
  src/utils/algorithm.hpp
  tests/unit/CMakeLists.txt
  tests/unit/interpreter.cpp
  tests/unit/query_plan_operator_to_string.cpp
Labels: enhancement, Ready for review

#1243 Ensure libkrb5 macros don't leak into our code
  src/communication/client.hpp
  src/communication/context.hpp
  src/communication/session.hpp
  src/query/db_accessor.hpp
  src/requests/CMakeLists.txt
  src/requests/requests.hpp
Labels: bug

#1203 [master <] Add --query-callable-mappings-path package default
  config/flags.yaml
  config/mappings.json
  release/debian/conffiles
  release/rpm/memgraph.spec.in
  src/CMakeLists.txt
Labels: community

#1245 Remove gqlalchemy from stress tests
  tests/stress/common.py
  tests/stress/detach_delete.py
  tests/stress/requirements.txt
Labels: infrastructure

#1239 Add manual performance benchmark execution
  .github/workflows/performance_benchmarks.yaml
Labels: benchmarking, Docs unnecessary

#1240 Add dependency check for e2e tests
  .github/workflows/diff.yaml
  tests/e2e/dependency_check.sh
Labels: infrastructure, Docs unnecessary

#1249 [master < T1249] Add Path.pop to C++ API
  include/_mgp.hpp
  include/_mgp_mock.py
  include/mg_procedure.h
  include/mgp.hpp
  include/mgp.py
  include/mgp_mock.py
  src/query/procedure/mg_procedure_impl.cpp
  src/query/procedure/py_module.cpp
  tests/e2e/mock_api/procedures/path.py
  tests/e2e/mock_api/test_compare_mock.py
  tests/unit/cpp_api.cpp
Labels: enhancement, Ship it, Docs needed

#1266 [master < T1266] Improve deserialization performance
  src/storage/v2/constraints/existence_constraints.cpp
  src/storage/v2/disk/label_index.cpp
  src/storage/v2/disk/label_property_index.cpp
  src/storage/v2/disk/name_id_mapper.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/unique_constraints.cpp
  src/storage/v2/id_types.hpp
  src/storage/v2/mvcc.hpp
  src/utils/exceptions.hpp
  src/utils/rocksdb_serialization.hpp
  src/utils/string.hpp
Labels: enhancement

#1280 [ master < T1280 ] Refactor mgbench
  tests/mgbench/benchmark.py
  tests/mgbench/benchmark_context.py
  tests/mgbench/graph_bench.py
  tests/mgbench/helpers.py
  tests/mgbench/workload_mode.py
Labels: benchmarking
