Repository memgraph/memgraph, pull requests merged in 2023-04, with the labels that each got.

#839 [master < T614] Add SHA256 password encryption
  src/auth/CMakeLists.txt
  src/auth/crypto.cpp
  src/auth/crypto.hpp
  src/memgraph.cpp
  src/utils/enum.hpp
  tests/e2e/configuration/default_config.py
  tests/mgbench/client.cpp
  tests/unit/auth.cpp
Labels: bug, enhancement, Ready for review

#837 [master < T613] Ommit label based access control for users with global graph visibility
  src/query/interpreter.cpp
Labels: enhancement, Ship it

#772 [master< T589-FL] Introduce analytics mode
  src/auth/models.cpp
  src/auth/models.hpp
  src/glue/auth.cpp
  src/query/exceptions.hpp
  src/query/frontend/ast/ast.cpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/ast_visitor.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/frontend/opencypher/grammar/MemgraphCypherLexer.g4
  src/query/frontend/semantic/required_privileges.cpp
  src/query/frontend/stripped_lexer_constants.hpp
  src/query/interpreter.cpp
  src/storage/v2/edge_accessor.cpp
  src/storage/v2/mvcc.hpp
  src/storage/v2/storage.cpp
  src/storage/v2/storage.hpp
  src/storage/v2/storage_mode.hpp
  src/storage/v2/transaction.hpp
  src/storage/v2/vertex_accessor.cpp
  src/utils/typeinfo.hpp
  tests/e2e/lba_procedures/show_privileges.py
  tests/integration/CMakeLists.txt
  tests/integration/storage_mode/CMakeLists.txt
  tests/integration/storage_mode/runner.py
  tests/integration/storage_mode/tester.cpp
  tests/unit/CMakeLists.txt
  tests/unit/storage_test_utils.cpp
  tests/unit/storage_test_utils.hpp
  tests/unit/storage_v2_storage_mode.cpp
  tests/unit/storage_v2_wal_file.cpp
Labels: enhancement, Ready for review

#853 [master < ] Change docker credentials
  .github/workflows/release_docker.yaml
Labels: infrastructure

#845 [master < ] Add upload to S3 job to Package All workflow
  .github/workflows/package_all.yaml
  init
Labels: infrastructure

#881 Add benchgraph.sh under mgbench
  libs/setup.sh
  tests/mgbench/.gitignore
  tests/mgbench/benchgraph.sh
Labels: infrastructure, benchmarking

#836 [master < ] Add MgBench tutorial
  .github/workflows/diff.yaml
  .github/workflows/release_mgbench_client.yaml
  libs/setup.sh
  licenses/third-party/ldbc/LICENSE
  tests/mgbench/.gitignore
  tests/mgbench/Dockerfile.mgbench_client
  tests/mgbench/README.md
  tests/mgbench/benchgraph.sh
  tests/mgbench/benchmark.py
  tests/mgbench/benchmark_context.py
  tests/mgbench/compare_results.py
  tests/mgbench/cypher/ldbc_to_cypher.py
  tests/mgbench/graph_bench.py
  tests/mgbench/how_to_use_benchgraph.md
  tests/mgbench/log.py
  tests/mgbench/runners.py
  tests/mgbench/setup.py
  tests/mgbench/validation.py
  tests/mgbench/workloads/__init__.py
  tests/mgbench/workloads/base.py
  tests/mgbench/workloads/demo.py
  tests/mgbench/workloads/importers/importer_ldbc_bi.py
  tests/mgbench/workloads/importers/importer_ldbc_interactive.py
  tests/mgbench/workloads/importers/importer_pokec.py
  tests/mgbench/workloads/ldbc_bi.py
  tests/mgbench/workloads/ldbc_interactive.py
  tests/mgbench/workloads/pokec.py
  tests/mgbench/zip_benchgraph.py
Labels: Ready for review, benchmarking

#877 [master < T620-FL] Fix max block size bug
  src/query/interpreter.cpp
  src/query/interpreter.hpp
Labels: Ready for review

#893 [master < ] Upgrade Jepsen setup
  tests/jepsen/run.sh
Labels: infrastructure

#888 [master < MG] `AccumulateCursor` with `utils::pmr::deque`
  src/query/plan/operator.cpp
  src/utils/pmr/deque.hpp
Labels: optimization

#899 [master < ] Update benchgraph methodology
  tests/mgbench/README.md
Labels: Ready for review, benchmarking
