Repository memgraph/memgraph, pull requests merged in 2024-08, with the labels that each got.

#2102 Add property compression
  src/storage/v2/property_store.cpp
  src/storage/v2/property_store.hpp
  src/utils/CMakeLists.txt
  src/utils/compressor.cpp
  src/utils/compressor.hpp
  src/utils/logging.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/configuration/default_config.py
  tests/e2e/durability/CMakeLists.txt
  tests/e2e/durability/common.py
  tests/e2e/durability/conftest.py
  tests/e2e/durability/durability_with_property_compression_used.py
  tests/e2e/durability/workloads.yaml
  tests/e2e/replication/CMakeLists.txt
  tests/e2e/replication/replication_with_property_compression_used.py
  tests/e2e/replication/workloads.yaml
  tests/mgbench/helpers.py
  tests/unit/CMakeLists.txt
  tests/unit/storage_v2_property_store.cpp
  tests/unit/utils_compressor.cpp
Labels: feature, Docs needed, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=release -test=core, CI -build=release -test=e2e, CI -build=release -test=benchmark

#2140 Added hiding sensitive informations- passwords in this case, added un…
  src/communication/bolt/v1/states/handlers.hpp
  src/utils/logging.hpp
  tests/unit/CMakeLists.txt
  tests/unit/utils_mask_sensitive_information.cpp
Labels: feature, enterprise, Docs needed, customer, CI -build=release -test=core

#2182 Periodic commit syntax
  src/query/frontend/ast/ast.cpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/frontend/opencypher/grammar/MemgraphCypherLexer.g4
  src/query/frontend/semantic/symbol_generator.cpp
  src/query/frontend/semantic/symbol_generator.hpp
  src/query/interpret/eval.cpp
  src/query/interpret/eval.hpp
  src/query/interpreter.cpp
  src/query/plan/planner.hpp
  src/utils/typeinfo.hpp
  tests/gql_behave/tests/memgraph_V1/features/periodic_commit.feature
  tests/gql_behave/tests/memgraph_V1_on_disk/features/periodic_commit.feature
  tests/unit/cypher_main_visitor.cpp
Labels: feature, Docs needed, customer, CI -build=debug -test=core

#2194 Periodic commit query planning
  .github/workflows/diff_release.yaml
  src/query/context.hpp
  src/query/frontend/semantic/symbol_generator.cpp
  src/query/frontend/semantic/symbol_generator.hpp
  src/query/interpret/eval.cpp
  src/query/interpret/eval.hpp
  src/query/interpreter.cpp
  src/query/plan/hint_provider.hpp
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  src/query/plan/operator_type_info.cpp
  src/query/plan/planner.hpp
  src/query/plan/preprocess.cpp
  src/query/plan/preprocess.hpp
  src/query/plan/pretty_print.cpp
  src/query/plan/pretty_print.hpp
  src/query/plan/rewrite/edge_type_index_lookup.hpp
  src/query/plan/rewrite/index_lookup.hpp
  src/query/plan/rewrite/join.hpp
  src/query/plan/rule_based_planner.cpp
  src/query/plan/rule_based_planner.hpp
  src/utils/event_counter.cpp
  src/utils/typeinfo.hpp
  tests/benchmark/query/planner.cpp
  tests/e2e/show_metrics/show_metrics.py
  tests/manual/interactive_planning.cpp
  tests/unit/query_common.hpp
  tests/unit/query_plan.cpp
  tests/unit/query_plan_checker.hpp
  tests/unit/query_semantic.cpp
  tests/unit/query_variable_start_planner.cpp
Labels: feature, Docs needed, customer, CI -build=community -test=core, CI -build=debug -test=core, CI -build=release -test=e2e

#2196 Periodic commit operator logic
  src/query/db_accessor.hpp
  src/query/interpret/eval.cpp
  src/query/interpret/eval.hpp
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/storage.hpp
Labels: feature, Docs needed, customer

#2197 Periodic commit delete planning
  src/query/frontend/semantic/symbol_generator.cpp
  src/query/interpret/eval.cpp
  src/query/interpret/eval.hpp
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  src/query/plan/planner.hpp
  src/query/plan/rewrite/periodic_delete.hpp
  tests/unit/query_plan.cpp
  tests/unit/query_semantic.cpp
Labels: feature, Docs needed, customer

#2183 Show active users
  src/communication/bolt/v1/session.hpp
  src/glue/SessionHL.cpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/opencypher/grammar/Cypher.g4
  src/query/frontend/semantic/required_privileges.cpp
  src/query/interpreter.cpp
  src/query/interpreter.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/show_active_users_info/CMakeLists.txt
  tests/e2e/show_active_users_info/common.py
  tests/e2e/show_active_users_info/test_show_active_users_info.py
  tests/e2e/show_active_users_info/workloads.yaml
Labels: feature, Docs needed, customer

#2252 Better error messages in OIDC SSO
  src/auth/reference_modules/oidc.py
  tests/e2e/sso/test_oidc.py
Labels: enterprise, Docs unnecessary, Code improvements, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=jepsen -test=core, CI -build=debug -test=core, CI -build=debug -test=integration, CI -build=release -test=core, CI -build=release -test=e2e, CI -build=release -test=stress, CI -build=release -test=benchmark

#2167 Implements Time-to-live feature
  src/dbms/database.cpp
  src/dbms/database.hpp
  src/dbms/database_handler.hpp
  src/dbms/dbms_handler.cpp
  src/dbms/dbms_handler.hpp
  src/dbms/handler.hpp
  src/memgraph.cpp
  src/query/CMakeLists.txt
  src/query/exceptions.hpp
  src/query/frontend/ast/ast.cpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/ast_visitor.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/frontend/opencypher/grammar/MemgraphCypherLexer.g4
  src/query/frontend/semantic/required_privileges.cpp
  src/query/frontend/stripped_lexer_constants.hpp
  src/query/interpreter.cpp
  src/query/metadata.cpp
  src/query/metadata.hpp
  src/query/stream/streams.cpp
  src/query/stream/streams.hpp
  src/query/time_to_live/time_to_live.cpp
  src/query/time_to_live/time_to_live.hpp
  src/replication_handler/include/replication_handler/replication_handler.hpp
  src/replication_handler/replication_handler.cpp
  src/utils/event_counter.cpp
  src/utils/pmr/map.hpp
  src/utils/scheduler.hpp
  src/utils/typeinfo.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/high_availability/single_coordinator.py
  tests/e2e/replication/CMakeLists.txt
  tests/e2e/replication/ttl.py
  tests/e2e/replication/workloads.yaml
  tests/e2e/show_metrics/show_metrics.py
  tests/e2e/time_to_live/CMakeLists.txt
  tests/e2e/time_to_live/common.py
  tests/e2e/time_to_live/multitenancy.py
  tests/e2e/time_to_live/workloads.yaml
  tests/unit/CMakeLists.txt
  tests/unit/cypher_main_visitor.cpp
  tests/unit/ttl.cpp
  tests/unit/utils_scheduler.cpp
Labels: feature, Docs needed

#2148 Allow user to define a password directly via its hash
  src/auth/auth.cpp
  src/auth/crypto.cpp
  src/auth/crypto.hpp
  src/auth/models.cpp
  src/auth/models.hpp
  tests/e2e/auth/auth_queries.py
  tests/e2e/auth/common.py
  tests/unit/auth.cpp
Labels: feature, security, Docs needed, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=debug -test=core, CI -build=release -test=e2e

#2217 Periodic commit transaction logic
  .github/workflows/diff_debug.yaml
  src/query/context.hpp
  src/query/cypher_query_interpreter.hpp
  src/query/database_access.hpp
  src/query/interpreter.cpp
  src/query/plan/operator.cpp
  src/query/plan/read_write_type_checker.cpp
  src/query/plan/read_write_type_checker.hpp
  src/query/plan/rule_based_planner.hpp
  src/query/trigger.cpp
  src/query/trigger.hpp
  src/storage/v2/indices/indices_utils.hpp
  src/storage/v2/inmemory/edge_type_index.cpp
  src/storage/v2/inmemory/edge_type_property_index.cpp
  src/storage/v2/inmemory/label_index.cpp
  src/storage/v2/inmemory/label_property_index.cpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/mvcc.hpp
  src/storage/v2/transaction.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/periodic_commit/CMakeLists.txt
  tests/e2e/periodic_commit/common.py
  tests/e2e/periodic_commit/periodic_commit.py
  tests/e2e/periodic_commit/workloads.yaml
  tests/e2e/replication/CMakeLists.txt
  tests/e2e/replication/replicate_enum.py
  tests/e2e/replication/replicate_periodic_commit.py
  tests/e2e/replication/workloads.yaml
  tests/gql_behave/tests/memgraph_V1/features/periodic_commit.feature
  tests/gql_behave/tests/memgraph_V1/features/periodic_delete.feature
Labels: feature, Docs needed, customer

#2261 Add telemetry for property compression
  .github/workflows/diff_release.yaml
  src/dbms/dbms_handler.hpp
  src/memgraph.cpp
  src/storage/v2/config.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/storage.hpp
  src/utils/compressor.cpp
  src/utils/compressor.hpp
Labels: Docs unnecessary

#2268 [BUGFIX] incorrect cache of pull plan with mixed builtin + user functions
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  src/storage/v2/durability/wal.cpp
  src/storage/v2/transaction.hpp
  src/utils/bond.hpp
Labels: bug, Docs - changelog only

#2273 [BUGFIX] incorrect size representations properties when using on disk
  src/storage/v2/property_store.cpp
  src/utils/memory.cpp
  src/utils/skip_list.hpp
  tests/e2e/interactive_mg_runner.py
  tests/e2e/memgraph.py
  tests/gql_behave/continuous_integration
  tests/unit/utils_memory.cpp
Labels: bug, Docs unnecessary

#2272 Bring benchmarks back on in CI
  .github/workflows/diff.yaml
Labels: Docs unnecessary, CI -build=release -test=benchmark

#2270 Fix header paths
  src/query/dump.cpp
  src/query/procedure/mg_procedure_impl.cpp
Labels: Docs unnecessary

#2275 Improve the error handling of the HA driver tests
  tests/drivers/run_cluster.sh
Labels: Docs unnecessary

#2248 Execute state check on becoming leader
  src/coordination/coordinator_instance.cpp
  src/coordination/coordinator_state.cpp
  src/coordination/include/coordination/coordinator_instance.hpp
  src/coordination/include/coordination/coordinator_state.hpp
  src/coordination/include/coordination/register_main_replica_coordinator_status.hpp
  src/coordination/include/coordination/replication_instance_connector.hpp
  src/coordination/replication_instance_connector.cpp
  src/dbms/coordinator_handler.cpp
  src/dbms/coordinator_handler.hpp
  src/query/interpreter.cpp
  src/query/metadata.cpp
  tests/e2e/high_availability/coord_cluster_registration.py
  tests/e2e/high_availability/distributed_coords.py
Labels: high-availability, CI -build=jepsen -test=core, CI -build=release -test=core, CI -build=release -test=e2e

#2241 Fix issues on recovery of log store and state machine
  src/coordination/coordinator_log_store.cpp
  src/coordination/coordinator_state_machine.cpp
  src/coordination/include/coordination/coordinator_communication_config.hpp
  src/coordination/include/coordination/coordinator_exceptions.hpp
  src/coordination/include/nuraft/constants_log_durability.hpp
  src/coordination/include/nuraft/coordinator_log_store.hpp
  src/coordination/include/nuraft/coordinator_state_machine.hpp
  src/coordination/raft_state.cpp
  tests/e2e/high_availability/distributed_coords.py
  tests/unit/coordinator_state_machine.cpp
Labels: bug, high-availability, Docs - changelog only, CI -build=jepsen -test=core, CI -build=release -test=core, CI -build=release -test=e2e

#2281 Order IP version resolution in endpoint
  src/io/network/endpoint.cpp
Labels: tests, high-availability, Docs - changelog only, CI -build=release -test=e2e

#2288 Bugfix: Deadlock while destroying database with streams
  src/query/stream/streams.cpp
Labels: bug, Docs - changelog only

#2282 More detailed TTL trace logs
  src/query/time_to_live/time_to_live.cpp
Labels: Docs unnecessary, Code improvements

#2294 Correct label+property index entry insertion
  src/storage/v2/inmemory/label_property_index.cpp
  tests/unit/storage_v2_indices.cpp
Labels: bug, Docs - changelog only

#2279 Improve fine grained access e2e tests
  tests/e2e/fine_grained_access/common.py
  tests/e2e/fine_grained_access/create_delete_filtering_tests.py
Labels: tests, Docs unnecessary, CI -build=release -test=e2e
