Repository memgraph/memgraph, pull requests merged in 2024-01, with the labels that each got.

#1604 Improve e2e Kafka and Pulsar testing
  .github/workflows/diff.yaml
  tests/e2e/streams/kafka/docker-compose.yml
  tests/e2e/streams/pulsar/docker-compose.yml
Labels: infrastructure

#1609 Fix storage mode flag
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
Labels: bug, Docs - changelog only

#1620 Extend ToBoolean function so it casts "t" to true and "f" to false.
  src/query/interpret/awesome_memgraph_functions.cpp
  tests/gql_behave/tests/memgraph_V1/features/functions.feature
Labels: community, Docs needed

#1610 Add support for triggers in database dump
  src/query/dump.cpp
  src/query/dump.hpp
  src/query/interpreter.cpp
  tests/unit/query_dump.cpp
Labels: Docs needed

#1619 Fix flaky GC test
  tests/e2e/garbage_collection/gc_periodic.py
Labels: tests, Docs unnecessary

#1629 Fix using path in property value after CREATE
  src/query/plan/rule_based_planner.hpp
  tests/gql_behave/tests/memgraph_V1/features/match.feature
Labels: bug, Docs - changelog only

#1602 Add query params for labels
  src/query/cypher_query_interpreter.cpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/opencypher/grammar/Cypher.g4
  tests/benchmark/query/execution.cpp
  tests/gql_behave/tests/memgraph_V1/features/parameters.feature
  tests/manual/expression_pretty_printer.cpp
  tests/manual/interactive_planning.cpp
  tests/unit/cypher_main_visitor.cpp
Labels: feature, Docs needed

#1606 Fix index hints
  src/query/plan/cost_estimator.hpp
  src/query/plan/planner.hpp
  src/query/plan/rewrite/index_lookup.hpp
  tests/benchmark/query/planner.cpp
  tests/e2e/index_hints/index_hints.py
  tests/manual/interactive_planning.cpp
  tests/unit/query_cost_estimator.cpp
Labels: bug, Docs - changelog only

#1588 Add List Pattern Comprehension grammar.
  src/query/frontend/ast/ast.cpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/ast_visitor.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/ast/pretty_print.cpp
  src/query/frontend/opencypher/grammar/Cypher.g4
  src/query/frontend/semantic/symbol_generator.hpp
  src/query/frontend/semantic/symbol_table.hpp
  src/query/interpret/eval.hpp
  src/query/plan/preprocess.hpp
  src/query/plan/rule_based_planner.cpp
  src/utils/typeinfo.hpp
  tests/gql_behave/tests/memgraph_V1/features/list_operations.feature
  tests/gql_behave/tests/memgraph_V1/graphs/graph_keanu.cypher
Labels: draft, Docs needed

#1576 ToString function now returns double values with precision 15
  src/query/interpret/awesome_memgraph_functions.cpp
  src/utils/string.hpp
  tests/unit/query_expression_evaluator.cpp
  tests/unit/utils_string.cpp
Labels: Docs - changelog only

#1633 Add Tantivy ADR
  ADRs/001_tantivy.md
Labels: Docs unnecessary

#1631 Improve memory tracking
  src/memory/query_memory_control.cpp
  src/memory/query_memory_control.hpp
Labels: memory, Docs unnecessary

#1643 Add changes made to kafka in diff.yml to daily debian10 and ubuntu 20.04 builds
  .github/workflows/release_debian10.yaml
  .github/workflows/release_ubuntu2004.yaml
Labels: infrastructure, Docs unnecessary

#1634 Add NuRaft ADR
  ADRs/002_nuraft.md
Labels: Docs unnecessary

#1656 Prepare for 2.14 release
  licenses/BSL.txt
Labels: Docs unnecessary

#1657 Bugfix don't use _Py_IsFinalizing
  src/query/procedure/py_module.cpp
Labels: Docs unnecessary

#1635 Fix skip list cpp
  src/utils/skip_list.hpp
  tests/e2e/interactive_mg_runner.py
  tests/unit/skip_list.cpp
Labels: Docs unnecessary

#1654 Add support for query params in return limit
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/opencypher/grammar/Cypher.g4
  tests/gql_behave/tests/memgraph_V1/features/parameters.feature
Labels: Docs needed

#1572 Performance tuning based on stress test
  src/query/common.hpp
  src/query/frontend/ast/ast.hpp
  src/query/interpret/eval.hpp
  src/query/plan/preprocess.cpp
  src/query/plan/preprocess.hpp
  src/query/plan/rewrite/index_lookup.hpp
  src/query/plan/rule_based_planner.hpp
  src/query/typed_value.cpp
  src/storage/v2/durability/snapshot.cpp
  src/storage/v2/edge_accessor.cpp
  src/storage/v2/edge_accessor.hpp
  src/storage/v2/indices/indices.cpp
  src/storage/v2/indices/indices.hpp
  src/storage/v2/indices/indices_utils.hpp
  src/storage/v2/inmemory/label_index.cpp
  src/storage/v2/inmemory/label_index.hpp
  src/storage/v2/inmemory/label_property_index.cpp
  src/storage/v2/inmemory/label_property_index.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/inmemory/unique_constraints.cpp
  src/storage/v2/inmemory/unique_constraints.hpp
  src/storage/v2/property_value.hpp
  src/utils/counter.hpp
  src/utils/file.cpp
  src/utils/skip_list.hpp
Labels: Docs unnecessary

#1667 Add step to refresh jepsen cluster before test
  .github/workflows/diff.yaml
  tests/jepsen/run.sh
Labels: Docs unnecessary

#1658 Make release CI predictable
  .github/workflows/release_debian10.yaml
  .github/workflows/release_ubuntu2004.yaml
  .github/workflows/stress_test_large.yaml
Labels: Docs unnecessary

#1644 Change auth durability to store hash algorithm
  src/auth/auth.cpp
  src/auth/crypto.cpp
  src/auth/crypto.hpp
  src/auth/models.cpp
  src/auth/models.hpp
  src/utils/enum.hpp
  tests/unit/auth.cpp
  tests/unit/auth_handler.cpp
Labels: Docs - changelog only

#1677 Disable e2e tests in all workflows
  .github/workflows/diff.yaml
  .github/workflows/release_debian10.yaml
  .github/workflows/release_ubuntu2004.yaml
Labels: Docs unnecessary

#1673 Upgrade deprecated github actions
  .github/workflows/daily_benchmark.yaml
  .github/workflows/diff.yaml
  .github/workflows/full_clang_tidy.yaml
  .github/workflows/package_memgraph.yaml
  .github/workflows/performance_benchmarks.yaml
  .github/workflows/release_debian10.yaml
  .github/workflows/release_docker.yaml
  .github/workflows/release_mgbench_client.yaml
  .github/workflows/release_ubuntu2004.yaml
  .github/workflows/stress_test_large.yaml
  .github/workflows/upload_to_s3.yaml
Labels: Docs unnecessary

#1683 Update release CI job timeouts
  .github/workflows/release_debian10.yaml
  .github/workflows/release_ubuntu2004.yaml
  .github/workflows/stress_test_large.yaml
Labels: Docs unnecessary
