Repository memgraph/memgraph, pull requests merged in 2024-04, with the labels that each got.

#1881 Restore sonarcloud quality checks
  .sonarcloud.properties
Labels: bug, Docs unnecessary

#1841 Implement automatic index creation
  config/flags.yaml
  src/flags/general.cpp
  src/flags/general.hpp
  src/memgraph.cpp
  src/storage/v2/config.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/storage.hpp
  src/storage/v2/transaction.hpp
  src/storage/v2/vertex_accessor.cpp
  tests/e2e/CMakeLists.txt
  tests/e2e/configuration/default_config.py
  tests/e2e/index_auto_creation/CMakeLists.txt
  tests/e2e/index_auto_creation/common.py
  tests/e2e/index_auto_creation/index_auto_creation.py
  tests/e2e/index_auto_creation/workloads.yaml
Labels: Docs needed

#1890 Fix edge-type index garbage collection
  src/storage/v2/inmemory/storage.cpp
Labels: Docs unnecessary

#1891 Fix managing coordinators in HA
  src/coordination/coordinator_cluster_state.cpp
  src/coordination/coordinator_instance.cpp
  src/coordination/coordinator_state_machine.cpp
  src/coordination/coordinator_state_manager.cpp
  src/coordination/include/coordination/coordinator_instance.hpp
  src/coordination/include/coordination/raft_state.hpp
  src/coordination/include/nuraft/coordinator_cluster_state.hpp
  src/coordination/include/nuraft/coordinator_state_machine.hpp
  src/coordination/include/nuraft/coordinator_state_manager.hpp
  src/coordination/include/nuraft/raft_log_action.hpp
  src/coordination/raft_state.cpp
  tests/e2e/high_availability/coord_cluster_registration.py
  tests/unit/coordinator_cluster_state.cpp
  tests/unit/coordinator_instance.cpp
  tests/unit/coordinator_state_machine.cpp
  tests/unit/raft_state.cpp
Labels: bug, Docs unnecessary

#1723 Drop graph functionality
  src/query/db_accessor.hpp
  src/query/exceptions.hpp
  src/query/frontend/ast/ast.cpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/ast_visitor.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/frontend/semantic/required_privileges.cpp
  src/query/interpreter.cpp
  src/query/trigger.cpp
  src/query/trigger.hpp
  src/storage/v2/constraints/constraints.cpp
  src/storage/v2/constraints/constraints.hpp
  src/storage/v2/constraints/existence_constraints.cpp
  src/storage/v2/constraints/existence_constraints.hpp
  src/storage/v2/disk/edge_type_index.cpp
  src/storage/v2/disk/edge_type_index.hpp
  src/storage/v2/disk/label_index.hpp
  src/storage/v2/disk/label_property_index.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/indices/edge_type_index.hpp
  src/storage/v2/indices/indices.cpp
  src/storage/v2/indices/indices.hpp
  src/storage/v2/indices/label_index.hpp
  src/storage/v2/indices/label_property_index.hpp
  src/storage/v2/inmemory/edge_type_index.cpp
  src/storage/v2/inmemory/edge_type_index.hpp
  src/storage/v2/inmemory/label_index.cpp
  src/storage/v2/inmemory/label_index.hpp
  src/storage/v2/inmemory/label_property_index.cpp
  src/storage/v2/inmemory/label_property_index.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/inmemory/unique_constraints.cpp
  src/storage/v2/inmemory/unique_constraints.hpp
  src/storage/v2/storage.hpp
  src/utils/typeinfo.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/drop_graph/CMakeLists.txt
  tests/e2e/drop_graph/common.py
  tests/e2e/drop_graph/drop_graph.py
  tests/e2e/drop_graph/workloads.yaml
Labels: feature, Status - In Progress, Docs needed

#1868 Pass toolchain's root into ExternalProject
  CMakeLists.txt
  libs/CMakeLists.txt
Labels: bug, infrastructure, Docs unnecessary

#1790 Extend min() and max() to temporal types
  src/query/plan/operator.cpp
  tests/gql_behave/tests/memgraph_V1/features/aggregations.feature
  tests/gql_behave/tests/memgraph_V1_on_disk/features/aggregations.feature
  tests/unit/typed_value.cpp
Labels: Ready for review, Docs needed

#1783 Better EXISTS handling
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/opencypher/grammar/Cypher.g4
  tests/gql_behave/tests/memgraph_V1/features/memgraph_exists.feature
  tests/gql_behave/tests/memgraph_V1_on_disk/features/memgraph_exists.feature
  tests/unit/cypher_main_visitor.cpp
Labels: Docs needed, cypher

#1835 Bugfix: Runing periodic snapshot even if in analytical mode
  src/memgraph.cpp
Labels: bug, Docs - changelog only

#1784 Allow query with a write subquery to omit RETURN
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  tests/gql_behave/tests/memgraph_V1/features/create.feature
Labels: Docs - changelog only

#1874 Add multiple pattern comprehensions handling in Return clause.
  src/query/frontend/semantic/symbol_generator.cpp
  src/query/frontend/semantic/symbol_generator.hpp
  src/query/plan/operator.cpp
  src/query/plan/rule_based_planner.cpp
  src/query/plan/rule_based_planner.hpp
  tests/gql_behave/tests/memgraph_V1/features/list_operations.feature
Labels: feature, Docs needed

#1900 Fix text search module name & e2e tests
  query_modules/CMakeLists.txt
  tests/e2e/CMakeLists.txt
  tests/e2e/text_search/CMakeLists.txt
  tests/e2e/text_search_modules/CMakeLists.txt
  tests/e2e/text_search_modules/common.py
  tests/e2e/text_search_modules/test_text_search.py
  tests/e2e/text_search_modules/test_text_search_disabled.py
  tests/e2e/text_search_modules/workloads.yaml
Labels: bug, Docs unnecessary

#1899 Add missing workloads
  tests/e2e/awesome_functions/CMakeLists.txt
  tests/e2e/concurrency/CMakeLists.txt
  tests/e2e/drop_graph/CMakeLists.txt
  tests/e2e/filter_info/CMakeLists.txt
  tests/e2e/index_auto_creation/CMakeLists.txt
  tests/e2e/metadata_queries/CMakeLists.txt
  tests/e2e/query_modules_storage_modes/CMakeLists.txt
Labels: bug, Docs unnecessary

#1901 Improve mgbuild for local development
  .github/workflows/reusable_package.yaml
  release/package/mgbuild.sh
  tools/bench-graph-client/main.py
Labels: Docs unnecessary

#1869 Update validation.py
  tests/mgbench/client.cpp
  tests/mgbench/validation.py
Labels: benchmarking, Docs unnecessary

#1903 Add support for pattern comprehensions in WITH clause.
  src/query/frontend/semantic/symbol_generator.cpp
  src/query/plan/preprocess.cpp
  tests/gql_behave/tests/memgraph_V1/features/list_operations.feature
Labels: feature, Docs needed

#1773 Query execution in mage
  include/_mgp.hpp
  include/mg_procedure.h
  include/mgp.hpp
  src/memgraph.cpp
  src/query/context.hpp
  src/query/db_accessor.hpp
  src/query/interpreter.cpp
  src/query/interpreter_context.cpp
  src/query/interpreter_context.hpp
  src/query/procedure/mg_procedure_impl.cpp
  src/query/procedure/mg_procedure_impl.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/execution_query_modules/CMakeLists.txt
  tests/e2e/execution_query_modules/__init__.py
  tests/e2e/execution_query_modules/common.py
  tests/e2e/execution_query_modules/conftest.py
  tests/e2e/execution_query_modules/procedures/CMakeLists.txt
  tests/e2e/execution_query_modules/procedures/execution_module.cpp
  tests/e2e/execution_query_modules/verify_behaviour.py
  tests/e2e/execution_query_modules/workloads.yaml
Labels: feature, Docs needed

#1810 Forbid merge with null properties on a graph entity
  src/query/context.hpp
  src/query/plan/operator.cpp
  tests/gql_behave/tests/memgraph_V1/features/merge.feature
  tests/gql_behave/tests/memgraph_V1_on_disk/features/merge.feature
Labels: bug, Docs needed

#1875 Improve Jepsen setup
  .github/workflows/diff.yaml
  src/coordination/include/coordination/instance_status.hpp
  tests/jepsen/.gitignore
  tests/jepsen/README.md
  tests/jepsen/resources/cluster.edn
  tests/jepsen/run.sh
  tests/jepsen/src/jepsen/memgraph/bank.clj
  tests/jepsen/src/jepsen/memgraph/basic.clj
  tests/jepsen/src/jepsen/memgraph/client.clj
  tests/jepsen/src/jepsen/memgraph/core.clj
  tests/jepsen/src/jepsen/memgraph/large.clj
  tests/jepsen/src/jepsen/memgraph/nemesis.clj
  tests/jepsen/src/jepsen/memgraph/support.clj
  tests/jepsen/src/jepsen/memgraph/utils.clj
Labels: bug, Docs unnecessary

#1897 Add durable coordinator cluster config
  src/coordination/coordinator_instance.cpp
  src/coordination/coordinator_log_store.cpp
  src/coordination/coordinator_state_machine.cpp
  src/coordination/coordinator_state_manager.cpp
  src/coordination/include/coordination/coordinator_communication_config.hpp
  src/coordination/include/nuraft/coordinator_state_manager.hpp
  src/memgraph.cpp
  tests/e2e/high_availability/distributed_coords.py
  tests/unit/coordination_utils.cpp
  tests/unit/coordinator_instance.cpp
  tests/unit/high_availability_cluster_setup.cpp
  tests/unit/raft_state.cpp
Labels: bug, Docs - changelog only

#1904 Fix bug in fmt usage by text search
  query_modules/text_search_module.cpp
Labels: bug, Docs unnecessary

#1910 Enable merge queues
  .github/workflows/diff.yaml
Labels: Docs unnecessary

#1907 Update exception message when dropping graph
  src/query/interpreter.cpp
Labels: bug, Docs unnecessary

#1905 Fixes issues identified by Sonar
  src/storage/v2/edge_accessor.cpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/storage.cpp
  src/storage/v2/vertex_accessor.cpp
  src/utils/atomic_memory_block.hpp
Labels: bug, Docs unnecessary

#1896 Add GitHub action for running benchmark on large dataset manually
  .github/workflows/benchmark_on_pokec_large.yaml
  release/package/mgbuild.sh
Labels: Docs unnecessary

#1902 Fix HA unit tests
  tests/jepsen/.gitignore
  tests/jepsen/src/jepsen/memgraph/support.clj
  tests/unit/CMakeLists.txt
  tests/unit/coordinator_cluster_setup.cpp
  tests/unit/coordinator_cluster_state.cpp
  tests/unit/coordinator_instance.cpp
  tests/unit/coordinator_raft_log_serialization.cpp
  tests/unit/coordinator_raft_state.cpp
  tests/unit/coordinator_state_machine.cpp
  tests/unit/coordinator_utils.cpp
Labels: bug, Docs unnecessary

#1860 Extend mgbench to improve memory tracking on TCO project
  tests/mgbench/benchmark.py
  tests/mgbench/constants.py
Labels: benchmarking, Docs unnecessary

#1911 Add option to register replica after main in HA
  src/coordination/coordinator_cluster_state.cpp
  src/coordination/coordinator_handlers.cpp
  src/coordination/coordinator_instance.cpp
  src/coordination/coordinator_rpc.cpp
  src/coordination/coordinator_state_machine.cpp
  src/coordination/include/coordination/coordinator_handlers.hpp
  src/coordination/include/coordination/coordinator_rpc.hpp
  src/coordination/include/coordination/raft_state.hpp
  src/coordination/include/coordination/replication_instance_client.hpp
  src/coordination/include/coordination/replication_instance_connector.hpp
  src/coordination/include/nuraft/coordinator_cluster_state.hpp
  src/coordination/include/nuraft/coordinator_state_machine.hpp
  src/coordination/raft_state.cpp
  src/coordination/replication_instance_client.cpp
  src/coordination/replication_instance_connector.cpp
  src/replication/include/replication/state.hpp
  src/utils/typeinfo.hpp
  tests/e2e/high_availability/distributed_coords.py
Labels: feature, Docs needed

#1917 Fix clang tidy
  tests/code_analysis/clang_tidy.sh
  tools/github/clang-tidy/grep_error_lines.sh
Labels: bug, Docs unnecessary

#1913 Fix build logs in CI
  .github/workflows/diff.yaml
Labels: Docs unnecessary

#1912 Fix Jepsen large test
  .github/workflows/diff.yaml
  tests/jepsen/src/jepsen/memgraph/large.clj
  tests/jepsen/src/jepsen/memgraph/nemesis.clj
  tests/jepsen/src/jepsen/memgraph/support.clj
Labels: bug, Docs unnecessary

#1918 Fix MT test bug
  tests/e2e/replication_experimental/multitenancy.py
Labels: bug, Docs unnecessary

#1921 Drop graph reset edge count
  src/storage/v2/inmemory/storage.cpp
  tests/e2e/drop_graph/drop_graph.py
Labels: bug, Docs - changelog only

#1914 Fix jepsen bank test
  .github/workflows/diff.yaml
  tests/jepsen/README.md
  tests/jepsen/resources/cluster.edn
  tests/jepsen/resources/node-config.edn
  tests/jepsen/resources/replication-config.edn
  tests/jepsen/run.sh
  tests/jepsen/src/jepsen/memgraph/bank.clj
  tests/jepsen/src/jepsen/memgraph/client.clj
  tests/jepsen/src/jepsen/memgraph/core.clj
  tests/jepsen/src/jepsen/memgraph/large.clj
  tests/jepsen/src/jepsen/memgraph/nemesis.clj
  tests/jepsen/src/jepsen/memgraph/support.clj
Labels: bug, Docs unnecessary

#1930 install_deps.sh auto downloads and extracts toolchain archive
  environment/os/install_deps.sh
Labels: infrastructure, Effort - Low, Docs unnecessary

#1933 Change build and test status badge target in README
  README.md
Labels: Docs unnecessary

#1850 Add zoned datetime to utils::temporal
  src/utils/temporal.cpp
  src/utils/temporal.hpp
  tests/e2e/temporal_types/roundtrip.cpp
  tests/unit/utils_temporal.cpp
Labels: feature, Ready for review, Docs unnecessary

#1932 Discard request leadership on follower
  src/coordination/coordinator_instance.cpp
  src/coordination/coordinator_state.cpp
  src/coordination/include/coordination/coordinator_instance.hpp
  src/coordination/include/coordination/coordinator_state.hpp
  src/coordination/include/coordination/raft_state.hpp
  src/coordination/raft_state.cpp
  src/dbms/coordinator_handler.cpp
  src/dbms/coordinator_handler.hpp
  src/query/interpreter.cpp
  tests/e2e/high_availability/distributed_coords.py
Labels: bug, feature, Docs - changelog only

#1937 Update nuraft to master
  libs/.gitignore
  libs/nuraft.patch
  libs/nuraft2.1.0.patch
  libs/setup.sh
Labels: Docs unnecessary

#1939 Refactor diff workflow
  .github/workflows/diff.yaml
  .github/workflows/diff_community.yaml
  .github/workflows/diff_coverage.yaml
  .github/workflows/diff_debug.yaml
  .github/workflows/diff_jepsen.yaml
  .github/workflows/diff_release.yaml
  release/package/mgbuild.sh
Labels: Docs unnecessary

#1944 Fix same port bug on HA unit tests
  .github/workflows/diff_release.yaml
  tests/unit/coordinator_instance.cpp
Labels: bug, tests, Docs unnecessary

#1940 Add unit tests for pattern comprehensions in Return and With clauses
  src/query/plan/pretty_print.cpp
  src/query/plan/pretty_print.hpp
  tests/unit/cypher_main_visitor.cpp
  tests/unit/plan_pretty_print.cpp
  tests/unit/query_plan.cpp
  tests/unit/query_plan_checker.hpp
  tests/unit/query_semantic.cpp
Labels: tests, Docs unnecessary

#1938 Optional diff tests with manual execution
  .github/workflows/diff.yaml
Labels: Docs unnecessary

#1936 Add empty Jepsen HA test
  .github/workflows/diff_jepsen.yaml
  tests/jepsen/README.md
  tests/jepsen/run.sh
  tests/jepsen/src/jepsen/memgraph/bank.clj
  tests/jepsen/src/jepsen/memgraph/client.clj
  tests/jepsen/src/jepsen/memgraph/core.clj
  tests/jepsen/src/jepsen/memgraph/haclient.clj
  tests/jepsen/src/jepsen/memgraph/haempty.clj
  tests/jepsen/src/jepsen/memgraph/hanemesis.clj
  tests/jepsen/src/jepsen/memgraph/nemesis.clj
  tests/jepsen/src/jepsen/memgraph/support.clj
  tests/jepsen/src/jepsen/memgraph/utils.clj
Labels: feature, Docs unnecessary

#1948 Fix nuRaft init script issue
  libs/setup.sh
Labels: bug, Docs unnecessary

#1943 Run tests with specific labels on PR
  .github/pull_request_template.md
  .github/workflows/diff.yaml
  .github/workflows/diff_community.yaml
  .github/workflows/diff_coverage.yaml
  .github/workflows/diff_jepsen.yaml
Labels: Docs unnecessary, CI -build=community -test=core, CI -build=release -test=stress

#1949 Add exit on coordinator state ctor error
  src/flags/all.hpp
  src/memgraph.cpp
Labels: bug, Docs unnecessary

#1960 Change replication server ports in coordinator_cluster_setup
  tests/unit/coordinator_cluster_setup.cpp
Labels: bug, Docs unnecessary, CI -build=release -test=core

#1950 Check coordinator validity before adding it to cluster
  src/coordination/coordinator_instance.cpp
  src/coordination/coordinator_state.cpp
  src/coordination/include/coordination/coordinator_instance.hpp
  src/coordination/include/coordination/coordinator_state.hpp
  src/coordination/include/coordination/register_main_replica_coordinator_status.hpp
  src/coordination/raft_state.cpp
  src/dbms/coordinator_handler.cpp
  src/dbms/coordinator_handler.hpp
  src/query/interpreter.cpp
  tests/e2e/high_availability/coord_cluster_registration.py
Labels: feature, Docs unnecessary, CI -build=release -test=e2e

#1962 Refactor tests/util.sh
  tests/util.sh
Labels: Docs unnecessary

#1952 Skip running automated tests on workflow changes
  .github/workflows/diff.yaml
  tools/diff_setup.py
Labels: Docs unnecessary

#1926 Auto index creation fixes
  src/memgraph.cpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/vertex_accessor.cpp
Labels: bug, Docs - changelog only

#1971 Refactor creating Clojure client
  tests/jepsen/src/jepsen/memgraph/bank.clj
  tests/jepsen/src/jepsen/memgraph/client.clj
  tests/jepsen/src/jepsen/memgraph/core.clj
  tests/jepsen/src/jepsen/memgraph/haempty.clj
  tests/jepsen/src/jepsen/memgraph/large.clj
Labels: feature, Docs unnecessary, CI -build=jepsen -test=core

#1968 Fix index lookup rewrite in case of pattern comprehension
  src/query/plan/rewrite/index_lookup.hpp
  tests/gql_behave/tests/memgraph_V1/features/list_operations.feature
Labels: Docs - changelog only

#1951 Add env variables for HA k8 cluster setup
  src/coordination/coordinator_state.cpp
  src/coordination/include/coordination/coordinator_instance.hpp
  src/coordination/include/coordination/coordinator_state.hpp
  src/dbms/inmemory/replication_handlers.cpp
  src/flags/CMakeLists.txt
  src/flags/coord_flag_env_handler.cpp
  src/flags/coord_flag_env_handler.hpp
  src/flags/experimental.cpp
  src/flags/experimental.hpp
  src/memgraph.cpp
  src/query/interpreter.cpp
  src/replication/state.cpp
  src/replication_handler/include/replication_handler/replication_handler.hpp
  src/storage/v2/config.hpp
  src/storage/v2/replication/replication_client.cpp
  tests/e2e/high_availability/coord_cluster_registration.py
  tests/e2e/interactive_mg_runner.py
  tests/e2e/memgraph.py
Labels: feature, Docs needed

#1974 Fix unit tests warnings about deprecated typed tests defines
  src/storage/v2/disk/label_index.cpp
  src/storage/v2/disk/label_property_index.cpp
  src/storage/v2/vertex.hpp
  src/storage/v2/vertex_info_cache.hpp
  tests/unit/auth_checker.cpp
  tests/unit/bfs_fine_grained.cpp
  tests/unit/bfs_single_node.cpp
  tests/unit/cpp_api.cpp
  tests/unit/csv_csv_parsing.cpp
  tests/unit/cypher_main_visitor.cpp
  tests/unit/database_get_info.cpp
  tests/unit/interpreter.cpp
  tests/unit/plan_pretty_print.cpp
  tests/unit/query_dump.cpp
  tests/unit/query_expression_evaluator.cpp
  tests/unit/query_plan.cpp
  tests/unit/query_plan_accumulate_aggregate.cpp
  tests/unit/query_plan_bag_semantics.cpp
  tests/unit/query_plan_create_set_remove_delete.cpp
  tests/unit/query_plan_edge_cases.cpp
  tests/unit/query_plan_match_filter_return.cpp
  tests/unit/query_plan_operator_to_string.cpp
  tests/unit/query_plan_read_write_typecheck.cpp
  tests/unit/query_plan_v2_create_set_remove_delete.cpp
  tests/unit/query_pretty_print.cpp
  tests/unit/query_procedure_mgp_type.cpp
  tests/unit/query_procedure_py_module.cpp
  tests/unit/query_procedures_mgp_graph.cpp
  tests/unit/query_semantic.cpp
  tests/unit/query_streams.cpp
  tests/unit/query_trigger.cpp
  tests/unit/query_variable_start_planner.cpp
  tests/unit/storage_v2.cpp
  tests/unit/storage_v2_constraints.cpp
  tests/unit/storage_v2_durability_inmemory.cpp
  tests/unit/storage_v2_edge_inmemory.cpp
  tests/unit/storage_v2_edge_ondisk.cpp
  tests/unit/storage_v2_get_info.cpp
  tests/unit/storage_v2_indices.cpp
  tests/unit/storage_v2_isolation_level.cpp
  tests/unit/storage_v2_storage_mode.cpp
  tests/unit/storage_v2_wal_file.cpp
  tests/unit/transaction_queue.cpp
  tests/unit/transaction_queue_multiple.cpp
  tests/unit/typed_value.cpp
  tests/unit/utils_file_locker.cpp
  tests/unit/utils_memory.cpp
Labels: tests, Docs unnecessary, CI -build=debug -test=core

#1984 Remove coord cluster setup unit test
  tests/unit/CMakeLists.txt
  tests/unit/coordinator_cluster_setup.cpp
Labels: bug, Docs unnecessary

#1986 Fix asio download from cache
  libs/setup.sh
Labels: Docs unnecessary, CI -build=community -test=core

#1985 Add last_succ_resp_ms to SHOW INSTANCES output
  src/coordination/coordinator_communication_config.cpp
  src/coordination/coordinator_instance.cpp
  src/coordination/include/coordination/coordinator_communication_config.hpp
  src/coordination/include/coordination/coordinator_instance.hpp
  src/coordination/include/coordination/instance_status.hpp
  src/coordination/include/coordination/raft_state.hpp
  src/coordination/include/coordination/replication_instance_connector.hpp
  src/coordination/raft_state.cpp
  src/coordination/replication_instance_connector.cpp
  src/query/interpreter.cpp
  tests/e2e/high_availability/common.py
  tests/e2e/high_availability/coord_cluster_registration.py
  tests/e2e/high_availability/coordinator.py
  tests/e2e/high_availability/disable_writing_on_main_after_restart.py
  tests/e2e/high_availability/distributed_coords.py
  tests/e2e/high_availability/not_replicate_from_old_main.py
  tests/e2e/high_availability/single_coordinator.py
Labels: feature, Docs needed

#1988 Move HA e2e logs to separate folders
  tests/e2e/high_availability/coord_cluster_registration.py
  tests/e2e/high_availability/disable_writing_on_main_after_restart.py
  tests/e2e/high_availability/distributed_coords.py
  tests/e2e/high_availability/manual_setting_replicas.py
  tests/e2e/high_availability/not_replicate_from_old_main.py
  tests/e2e/high_availability/single_coordinator.py
  tests/e2e/high_availability/workloads.yaml
Labels: feature, Docs unnecessary, CI -build=release -test=e2e

#1981 Expose coordinator's internal functionality to manage cluster
  src/coordination/coordinator_instance.cpp
  src/coordination/coordinator_state.cpp
  src/coordination/include/coordination/coordinator_instance.hpp
  src/coordination/include/coordination/coordinator_state.hpp
  src/coordination/include/coordination/register_main_replica_coordinator_status.hpp
  src/dbms/coordinator_handler.cpp
  src/dbms/coordinator_handler.hpp
  src/dbms/dbms_handler.cpp
  src/memgraph.cpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/ast_visitor.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/frontend/opencypher/grammar/MemgraphCypherLexer.g4
  src/query/frontend/stripped_lexer_constants.hpp
  src/query/interpreter.cpp
  src/query/interpreter.hpp
  src/query/metadata.cpp
  src/query/metadata.hpp
  src/replication/replication_client.cpp
  src/utils/thread_pool.cpp
  src/utils/thread_pool.hpp
  tests/e2e/high_availability/distributed_coords.py
  tests/e2e/mg_utils.py
Labels: feature, Docs needed

#1991 Replicate only durable commits to replicas during recovery
  src/dbms/inmemory/replication_handlers.cpp
  src/storage/v2/durability/serialization.hpp
  src/storage/v2/inmemory/replication/recovery.cpp
  src/storage/v2/replication/replication_client.cpp
  src/utils/file.hpp
  tests/jepsen/src/jepsen/memgraph/bank.clj
Labels: bug, Docs needed, CI -build=coverage -test=core, CI -build=jepsen -test=core, CI -build=release -test=e2e
