Repository memgraph/memgraph, pull requests merged in 2024-02, with the labels that each got.

#1672 HA: Support restart of instances
  src/coordination/CMakeLists.txt
  src/coordination/coordinator_client.cpp
  src/coordination/coordinator_data.cpp
  src/coordination/coordinator_instance.cpp
  src/coordination/coordinator_rpc.cpp
  src/coordination/coordinator_state.cpp
  src/coordination/include/coordination/coordinator_client.hpp
  src/coordination/include/coordination/coordinator_config.hpp
  src/coordination/include/coordination/coordinator_data.hpp
  src/coordination/include/coordination/coordinator_exceptions.hpp
  src/coordination/include/coordination/coordinator_instance.hpp
  src/coordination/include/coordination/coordinator_rpc.hpp
  src/coordination/include/coordination/coordinator_state.hpp
  src/coordination/include/coordination/failover_status.hpp
  src/coordination/include/coordination/register_main_replica_coordinator_status.hpp
  src/dbms/coordinator_handler.hpp
  src/dbms/coordinator_handlers.cpp
  src/dbms/coordinator_handlers.hpp
  src/dbms/utils.hpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/interpreter.cpp
  src/storage/v2/config.hpp
  src/storage/v2/replication/replication_client.cpp
  src/utils/on_scope_exit.hpp
  tests/e2e/high_availability_experimental/CMakeLists.txt
  tests/e2e/high_availability_experimental/automatic_failover.py
  tests/e2e/high_availability_experimental/common.py
  tests/e2e/high_availability_experimental/conftest.py
  tests/e2e/high_availability_experimental/coordinator.py
Labels: Docs needed

#1659 Add RocksDB ADR
  ADRs/003_rocksdb.md
Labels: Docs unnecessary

#1688 Improve memory handling of Deltas
  libs/setup.sh
  src/storage/v2/delta.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/durability/wal.cpp
  src/storage/v2/edge_accessor.cpp
  src/storage/v2/id_types.hpp
  src/storage/v2/indices/indices_utils.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/inmemory/unique_constraints.cpp
  src/storage/v2/mvcc.hpp
  src/storage/v2/property_value.hpp
  src/storage/v2/transaction.hpp
  src/storage/v2/vertex_info_helpers.hpp
  src/utils/disk_utils.hpp
  src/utils/string.hpp
  tests/unit/storage_v2_property_store.cpp
  tests/unit/storage_v2_wal_file.cpp
Labels: memory, Docs - changelog only

#1642 Fix accumulated path evaluation in builtin algorithms.
  src/query/path.hpp
  src/query/plan/operator.cpp
  tests/gql_behave/tests/memgraph_V1/features/match.feature
  tests/gql_behave/tests/memgraph_V1/features/memgraph_allshortest.feature
  tests/gql_behave/tests/memgraph_V1/features/memgraph_bfs.feature
  tests/gql_behave/tests/memgraph_V1/features/memgraph_wshortest.feature
  tests/gql_behave/tests/memgraph_V1/graphs/graph_edges.cypher
Labels: Docs - changelog only

#1687 Organize coordinator group
  .clang-tidy
  CMakeLists.txt
  src/coordination/CMakeLists.txt
  src/coordination/coordinator_data.cpp
  src/coordination/coordinator_instance.cpp
  src/coordination/coordinator_log_store.cpp
  src/coordination/coordinator_state.cpp
  src/coordination/coordinator_state_machine.cpp
  src/coordination/coordinator_state_manager.cpp
  src/coordination/include/coordination/coordinator_client.hpp
  src/coordination/include/coordination/coordinator_data.hpp
  src/coordination/include/coordination/coordinator_exceptions.hpp
  src/coordination/include/coordination/coordinator_handlers.hpp
  src/coordination/include/coordination/coordinator_instance.hpp
  src/coordination/include/coordination/coordinator_state.hpp
  src/coordination/include/coordination/instance_status.hpp
  src/coordination/include/coordination/replication_instance.hpp
  src/coordination/include/nuraft/coordinator_log_store.hpp
  src/coordination/include/nuraft/coordinator_state_machine.hpp
  src/coordination/include/nuraft/coordinator_state_manager.hpp
  src/coordination/replication_instance.cpp
  src/dbms/coordinator_handler.cpp
  src/dbms/coordinator_handler.hpp
  src/flags/replication.cpp
  src/flags/replication.hpp
  src/io/network/endpoint.cpp
  src/io/network/endpoint.hpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/frontend/opencypher/grammar/MemgraphCypherLexer.g4
  src/query/frontend/stripped_lexer_constants.hpp
  src/query/interpreter.cpp
  src/query/interpreter.hpp
  src/query/metadata.cpp
  src/query/metadata.hpp
  tests/e2e/configuration/default_config.py
  tests/e2e/high_availability_experimental/CMakeLists.txt
  tests/e2e/high_availability_experimental/automatic_failover.py
  tests/e2e/high_availability_experimental/coordinator.py
  tests/e2e/high_availability_experimental/distributed_coordinators.py
  tests/e2e/high_availability_experimental/workloads.yaml
  tests/unit/cypher_main_visitor.cpp
Labels: Docs needed

#1700 Fix primary urls for deps
  libs/setup.sh
Labels: Docs unnecessary

#1703 Revert e2e tests and remove flaky ones
  .github/workflows/diff.yaml
  tests/e2e/CMakeLists.txt
  tests/e2e/lba_procedures/workloads.yaml
  tests/e2e/memory/workloads.yaml
  tests/e2e/query_modules/workloads.yaml
  tests/e2e/streams/workloads.yaml
Labels: Docs unnecessary

#1708 Fix go driver tests
  tests/drivers/go/v4/metadata.go
Labels: tests, Docs unnecessary

#1653 Add support for query params in load csv
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/plan/rule_based_planner.hpp
  tests/e2e/load_csv/load_csv.py
  tests/gql_behave/tests/memgraph_V1/features/functions.feature
Labels: Docs needed

#1651 Fix memory tracker counting wrong after OOM
  src/memory/global_memory_control.cpp
  src/memory/query_memory_control.cpp
Labels: Docs - changelog only

#1707 Revert replication tests
  .github/workflows/diff.yaml
  src/dbms/inmemory/replication_handlers.cpp
  src/dbms/rpc.cpp
  src/replication/state.cpp
  src/replication_handler/replication_handler.cpp
  tests/e2e/CMakeLists.txt
  tests/e2e/memgraph.py
  tests/e2e/replication/show_while_creating_invalid_state.py
  tests/e2e/replication_experimental/multitenancy.py
Labels: tests, Docs unnecessary

#1710 Fix unbound variable causing crash inside subquery
  src/query/frontend/semantic/symbol_generator.cpp
  tests/gql_behave/tests/memgraph_V1/features/subqueries.feature
Labels: bug, Docs - changelog only

#1722 Add rules for rc workflows
  .github/workflows/release_debian10.yaml
  .github/workflows/release_ubuntu2004.yaml
  .github/workflows/stress_test_large.yaml
Labels: Docs unnecessary

#1725 Turn e2e tests back on for release build workflows
  .github/workflows/release_debian10.yaml
  .github/workflows/release_ubuntu2004.yaml
Labels: Docs unnecessary

#1711 HA: Coordinator replica flow polishing
  src/coordination/CMakeLists.txt
  src/coordination/coordinator_client.cpp
  src/coordination/coordinator_handlers.cpp
  src/coordination/coordinator_instance.cpp
  src/coordination/coordinator_rpc.cpp
  src/coordination/include/coordination/coordinator_client.hpp
  src/coordination/include/coordination/coordinator_config.hpp
  src/coordination/include/coordination/coordinator_handlers.hpp
  src/coordination/include/coordination/coordinator_rpc.hpp
  src/coordination/include/coordination/replication_instance.hpp
  src/coordination/include/coordination/rpc_errors.hpp
  src/coordination/replication_instance.cpp
  src/flags/replication.cpp
  src/flags/replication.hpp
  src/memgraph.cpp
  src/query/config.hpp
  src/query/interpreter.cpp
  src/query/interpreter.hpp
  src/query/replication_query_handler.hpp
  src/replication/state.cpp
  src/replication_handler/include/replication_handler/replication_handler.hpp
  src/replication_handler/replication_handler.cpp
  src/utils/typeinfo.hpp
  tests/e2e/configuration/default_config.py
  tests/e2e/high_availability_experimental/not_replicate_from_old_main.py
  tests/e2e/high_availability_experimental/single_coordinator.py
  tests/unit/storage_v2_replication.cpp
Labels: Docs - changelog only

#1730 Remove default assignees from issue-bug template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Docs unnecessary

#1715 Fixup memory e2e tests
  src/memory/global_memory_control.cpp
  src/memory/new_delete.cpp
  src/memory/query_memory_control.cpp
  src/memory/query_memory_control.hpp
  src/query/procedure/mg_procedure_impl.cpp
  src/utils/exceptions.hpp
  src/utils/memory_tracker.cpp
  src/utils/memory_tracker.hpp
  src/utils/query_memory_tracker.cpp
  src/utils/query_memory_tracker.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/memory/CMakeLists.txt
  tests/e2e/memory/memory_control.cpp
  tests/e2e/memory/memory_limit_global_multi_thread_proc_create.cpp
  tests/e2e/memory/procedures/CMakeLists.txt
  tests/e2e/memory/procedures/global_memory_limit_multi_thread_create_proc.cpp
  tests/e2e/memory/procedures/query_memory_limit_proc_multi_thread.cpp
  tests/e2e/memory/query_memory_limit_proc_multi_thread.cpp
  tests/e2e/memory/workloads.yaml
  tests/unit/utils_memory_tracker.cpp
Labels: bug, tests, Docs - changelog only

#1557 Add function for property sizes
  src/query/db_accessor.hpp
  src/query/interpret/awesome_memgraph_functions.cpp
  src/storage/v2/edge_accessor.cpp
  src/storage/v2/edge_accessor.hpp
  src/storage/v2/name_id_mapper.hpp
  src/storage/v2/property_store.cpp
  src/storage/v2/property_store.hpp
  src/storage/v2/storage.hpp
  src/storage/v2/vertex_accessor.cpp
  src/storage/v2/vertex_accessor.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/awesome_functions/CMakeLists.txt
  tests/e2e/awesome_functions/awesome_functions.py
  tests/e2e/awesome_functions/common.py
  tests/e2e/awesome_functions/workloads.yaml
Labels: Docs needed

#1733 Patch NuRaft for clang-17 compilation
  libs/.gitignore
  libs/nuraft2.1.0.patch
  libs/setup.sh
Labels: Docs unnecessary

#1720 Add --experimental-enabled=high-availability
  .github/workflows/diff.yaml
  CMakeLists.txt
  src/coordination/CMakeLists.txt
  src/coordination/coordinator_handlers.cpp
  src/coordination/coordinator_instance.cpp
  src/coordination/include/coordination/constants.hpp
  src/flags/experimental.cpp
  src/flags/experimental.hpp
  src/query/interpreter.cpp
  src/query/replication_query_handler.hpp
  src/replication_handler/include/replication_handler/replication_handler.hpp
  src/replication_handler/replication_handler.cpp
  src/storage/v2/name_id_mapper.hpp
  src/utils/functional.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/configuration/default_config.py
  tests/e2e/high_availability/CMakeLists.txt
  tests/e2e/high_availability/common.py
  tests/e2e/high_availability/coord_cluster_registration.py
  tests/e2e/high_availability/coordinator.py
  tests/e2e/high_availability/disable_writing_on_main_after_restart.py
  tests/e2e/high_availability/distributed_coords.py
  tests/e2e/high_availability/manual_setting_replicas.py
  tests/e2e/high_availability/not_replicate_from_old_main.py
  tests/e2e/high_availability/single_coordinator.py
  tests/e2e/high_availability/workloads.yaml
  tests/e2e/high_availability_experimental/CMakeLists.txt
  tests/e2e/interactive_mg_runner.py
  tests/e2e/replication/show_while_creating_invalid_state.py
  tests/unit/storage_v2_replication.cpp
Labels: Docs needed

#1741 Push successful RC builds to S3
  .github/workflows/release_build_test.yaml
  .github/workflows/release_debian10.yaml
  .github/workflows/release_ubuntu2004.yaml
Labels: Docs unnecessary

#1745 In BFS expansion filter by path we should shrink path to restore state prior to expansion only if the path was changed.
  src/query/plan/operator.cpp
  tests/gql_behave/tests/memgraph_V1/features/match.feature
  tests/gql_behave/tests/memgraph_V1/features/memgraph_bfs.feature
  tests/gql_behave/tests/memgraph_V1/features/memgraph_wshortest.feature
  tests/gql_behave/tests/memgraph_V1/graphs/graph_edges.cypher
Labels: bug

#1699 Better auth user/role handling
  src/auth/auth.cpp
  src/auth/auth.hpp
  src/auth/models.cpp
  src/auth/models.hpp
  src/auth/module.cpp
  src/auth/module.hpp
  src/auth/rpc.cpp
  src/communication/websocket/auth.cpp
  src/communication/websocket/auth.hpp
  src/communication/websocket/session.cpp
  src/glue/CMakeLists.txt
  src/glue/SessionHL.cpp
  src/glue/SessionHL.hpp
  src/glue/auth_checker.cpp
  src/glue/auth_checker.hpp
  src/glue/auth_handler.cpp
  src/glue/auth_handler.hpp
  src/glue/query_user.cpp
  src/glue/query_user.hpp
  src/memgraph.cpp
  src/query/CMakeLists.txt
  src/query/auth_checker.hpp
  src/query/auth_query_handler.hpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/interpreter.cpp
  src/query/interpreter.hpp
  src/query/interpreter_context.cpp
  src/query/interpreter_context.hpp
  src/query/query_user.cpp
  src/query/query_user.hpp
  src/query/stream/streams.cpp
  src/query/stream/streams.hpp
  src/query/trigger.cpp
  src/query/trigger.hpp
  src/replication_handler/replication_handler.cpp
  tests/benchmark/expansion.cpp
  tests/e2e/configuration/default_config.py
  tests/e2e/fine_grained_access/create_delete_filtering_tests.py
  tests/e2e/fine_grained_access/edge_type_filtering_tests.py
  tests/e2e/fine_grained_access/path_filtering_tests.py
  tests/e2e/fine_grained_access/workloads.yaml
  tests/e2e/lba_procedures/read_permission_queries.py
  tests/e2e/replication_experimental/auth.py
  tests/e2e/transaction_queue/test_transaction_queue.py
  tests/integration/auth/runner.py
  tests/integration/ldap/runner.py
  tests/integration/ldap/schema.ldif
  tests/integration/ldap/tester.cpp
  tests/manual/single_query.cpp
  tests/unit/auth.cpp
  tests/unit/auth_checker.cpp
  tests/unit/interpreter_faker.hpp
  tests/unit/monitoring.cpp
  tests/unit/query_dump.cpp
  tests/unit/query_plan_edge_cases.cpp
  tests/unit/query_streams.cpp
  tests/unit/query_trigger.cpp
Labels: security, Docs needed

#1621 Removed force dir in the GetInfo functions
  src/dbms/database.hpp
  src/dbms/dbms_handler.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/storage.hpp
  tests/unit/database_get_info.cpp
  tests/unit/storage_v2_get_info.cpp
Labels: Docs unnecessary

#1630 Correctly call driver v1 tests
  tests/drivers/run.sh
Labels: Docs unnecessary

#1735 Introduce multi-tenancy to SHOW REPLICAS
  src/query/frontend/ast/ast.hpp
  src/query/interpreter.cpp
  src/query/interpreter.hpp
  src/query/replication_query_handler.hpp
  src/replication/include/replication/replication_client.hpp
  src/replication_handler/include/replication_handler/replication_handler.hpp
  src/replication_handler/replication_handler.cpp
  src/storage/v2/replication/global.hpp
  src/storage/v2/replication/replication_client.cpp
  src/storage/v2/replication/replication_storage_state.hpp
  src/system/include/system/system.hpp
  tests/e2e/high_availability/coord_cluster_registration.py
  tests/e2e/high_availability/distributed_coords.py
  tests/e2e/high_availability/not_replicate_from_old_main.py
  tests/e2e/high_availability/single_coordinator.py
  tests/e2e/mg_utils.py
  tests/e2e/replication/edge_delete.py
  tests/e2e/replication/show.py
  tests/e2e/replication/show_while_creating_invalid_state.py
  tests/e2e/replication_experimental/multitenancy.py
Labels: high-availability, Docs needed, multi-tenancy

#1765 Add jobs for pushing ARM packages
  .github/workflows/release_build_test.yaml
Labels: Docs unnecessary

#1747 Compact Delta 80B -> 56B
  src/memory/global_memory_control.cpp
  src/mg_import_csv.cpp
  src/query/procedure/mg_procedure_impl.cpp
  src/storage/v2/delta.hpp
  src/utils/disk_utils.hpp
  src/utils/string.hpp
Labels: memory, Docs needed

#1718 Fix schema.node_type_properties() and schema.rel_type_properties()
  query_modules/schema.cpp
  tests/e2e/query_modules/schema_test.py
Labels: bug, Docs needed

#1771 Add openssl to MEMGRAPH_BUILD_DEPS for amzn-2 and centos-7
  environment/os/amzn-2.sh
  environment/os/centos-7.sh
Labels: Docs unnecessary
