Repository memgraph/memgraph, pull requests merged in 2024-03, with the labels that each got.

#1743 Ensure replication works on HA cluster in different scenarios
  src/coordination/coordinator_client.cpp
  src/coordination/coordinator_instance.cpp
  src/coordination/include/coordination/coordinator_instance.hpp
  src/dbms/dbms_handler.cpp
  src/dbms/dbms_handler.hpp
  src/memgraph.cpp
  src/replication_handler/replication_handler.cpp
  src/storage/v2/durability/durability.cpp
  src/storage/v2/inmemory/replication/recovery.cpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/replication/replication_client.cpp
  tests/e2e/high_availability/single_coordinator.py
  tests/e2e/replication/show_while_creating_invalid_state.py
  tests/unit/coordination_utils.cpp
Labels: Docs - changelog only

#1728 Changing replication roles backed-up by RAFT
  src/coordination/CMakeLists.txt
  src/coordination/coordinator_client.cpp
  src/coordination/coordinator_cluster_state.cpp
  src/coordination/coordinator_instance.cpp
  src/coordination/coordinator_state.cpp
  src/coordination/coordinator_state_machine.cpp
  src/coordination/include/coordination/coordinator_client.hpp
  src/coordination/include/coordination/coordinator_config.hpp
  src/coordination/include/coordination/coordinator_exceptions.hpp
  src/coordination/include/coordination/coordinator_instance.hpp
  src/coordination/include/coordination/coordinator_state.hpp
  src/coordination/include/coordination/instance_status.hpp
  src/coordination/include/coordination/raft_state.hpp
  src/coordination/include/coordination/register_main_replica_coordinator_status.hpp
  src/coordination/include/coordination/replication_instance.hpp
  src/coordination/include/nuraft/coordinator_cluster_state.hpp
  src/coordination/include/nuraft/coordinator_state_machine.hpp
  src/coordination/include/nuraft/raft_log_action.hpp
  src/coordination/raft_state.cpp
  src/coordination/replication_instance.cpp
  src/dbms/coordinator_handler.cpp
  src/dbms/coordinator_handler.hpp
  src/dbms/inmemory/replication_handlers.cpp
  src/io/network/endpoint.cpp
  src/io/network/endpoint.hpp
  src/query/interpreter.cpp
  src/query/interpreter.hpp
  src/replication_coordination_glue/mode.hpp
  src/utils/CMakeLists.txt
  src/utils/string.hpp
  src/utils/uuid.cpp
  src/utils/uuid.hpp
  tests/e2e/high_availability/coord_cluster_registration.py
  tests/e2e/high_availability/coordinator.py
  tests/e2e/high_availability/disable_writing_on_main_after_restart.py
  tests/e2e/high_availability/distributed_coords.py
  tests/e2e/high_availability/not_replicate_from_old_main.py
  tests/e2e/high_availability/single_coordinator.py
  tests/e2e/mg_utils.py
Labels: Docs needed

#1778 Improve raft log serialization
  src/coordination/CMakeLists.txt
  src/coordination/coordinator_config.cpp
  src/coordination/coordinator_state_machine.cpp
  src/coordination/include/coordination/coordinator_config.hpp
  src/coordination/include/nuraft/coordinator_state_machine.hpp
  src/coordination/include/nuraft/raft_log_action.hpp
  src/replication_coordination_glue/mode.hpp
  tests/unit/CMakeLists.txt
  tests/unit/raft_log_serialization.cpp
Labels: Docs unnecessary

#1777 Add force sync REPLICA with MAIN
  src/coordination/coordinator_instance.cpp
  src/dbms/inmemory/replication_handlers.cpp
  src/dbms/inmemory/replication_handlers.hpp
  src/query/interpreter.cpp
  src/replication_handler/include/replication_handler/replication_handler.hpp
  src/replication_handler/replication_handler.cpp
  src/storage/v2/durability/durability.cpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/replication/replication_client.cpp
  src/storage/v2/replication/replication_client.hpp
  src/storage/v2/replication/rpc.cpp
  src/storage/v2/replication/rpc.hpp
  src/utils/functional.hpp
  src/utils/typeinfo.hpp
  tests/e2e/high_availability/single_coordinator.py
  tests/unit/coordination_utils.cpp
Labels: Docs needed

#1782 Improve (de)serialization of Raft log
  src/coordination/coordinator_client.cpp
  src/coordination/coordinator_cluster_state.cpp
  src/coordination/coordinator_instance.cpp
  src/coordination/include/coordination/coordinator_rpc.hpp
  src/coordination/include/coordination/raft_state.hpp
  src/coordination/include/nuraft/coordinator_cluster_state.hpp
  src/coordination/include/nuraft/raft_log_action.hpp
  src/coordination/raft_state.cpp
  src/io/network/endpoint.cpp
  src/io/network/endpoint.hpp
  src/query/interpreter.cpp
  src/query/metadata.cpp
  src/query/metadata.hpp
  src/replication_coordination_glue/role.hpp
  tests/e2e/replication/common.hpp
  tests/unit/CMakeLists.txt
  tests/unit/coordinator_cluster_state.cpp
Labels: Docs unnecessary

#1792 Fix bug prone add server to cluster behavior
  src/coordination/raft_state.cpp
  tests/e2e/high_availability/coord_cluster_registration.py
  tests/e2e/high_availability/distributed_coords.py
Labels: Docs - changelog only

#1686 List Pattern Comprehension planner
  src/query/frontend/ast/ast.hpp
  src/query/frontend/semantic/symbol_generator.cpp
  src/query/frontend/semantic/symbol_generator.hpp
  src/query/plan/hint_provider.hpp
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  src/query/plan/operator_type_info.cpp
  src/query/plan/preprocess.cpp
  src/query/plan/preprocess.hpp
  src/query/plan/pretty_print.cpp
  src/query/plan/pretty_print.hpp
  src/query/plan/rewrite/index_lookup.hpp
  src/query/plan/rewrite/join.hpp
  src/query/plan/rule_based_planner.cpp
  src/query/plan/rule_based_planner.hpp
  src/utils/typeinfo.hpp
  tests/gql_behave/tests/memgraph_V1/features/list_operations.feature
  tests/gql_behave/tests/memgraph_V1/graphs/graph_keanu.cypher
  tests/unit/cypher_main_visitor.cpp
  tests/unit/query_common.hpp
  tests/unit/query_semantic.cpp
Labels: Docs unnecessary

#1788 Fix snapshot creation in RSM and forbid multiple leaders
  src/coordination/coordinator_cluster_state.cpp
  src/coordination/coordinator_instance.cpp
  src/coordination/coordinator_log_store.cpp
  src/coordination/coordinator_state_machine.cpp
  src/coordination/include/nuraft/coordinator_state_machine.hpp
  src/coordination/raft_state.cpp
  src/query/interpreter.cpp
  tests/e2e/high_availability/coord_cluster_registration.py
  tests/e2e/high_availability/distributed_coords.py
Labels: bug, Docs unnecessary

#1794 Add test to verify log store works properly
  tests/e2e/high_availability/distributed_coords.py
Labels: Docs unnecessary

#1738 Fix early exit for OR expression
  src/query/interpret/eval.hpp
Labels: Ready for review, Docs - changelog only

#1798 Add new PR template
  .github/pull_request_template.md
Labels: Docs unnecessary

#1806 Fix build errors on toolchain-v5
  .clang-tidy
  .github/workflows/testflow.yml
  src/coordination/raft_state.cpp
  src/dbms/inmemory/replication_handlers.cpp
  src/storage/v2/replication/replication_client.cpp
  tests/e2e/module_file_manager/module_file_manager.cpp
  tools/github/clang-tidy/clang-tidy-diff.py
Labels: infrastructure, Ready for review, Docs unnecessary

#1809 Improve registration queries
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/interpreter.cpp
  tests/e2e/high_availability/coord_cluster_registration.py
  tests/e2e/high_availability/coordinator.py
  tests/e2e/high_availability/disable_writing_on_main_after_restart.py
  tests/e2e/high_availability/distributed_coords.py
  tests/e2e/high_availability/not_replicate_from_old_main.py
  tests/e2e/high_availability/single_coordinator.py
  tests/e2e/high_availability/workloads.yaml
  tests/unit/cypher_main_visitor.cpp
Labels: Docs needed

#1801 Pmr allocator unify
  CMakeLists.txt
  libs/setup.sh
  src/csv/include/csv/parsing.hpp
  src/csv/parsing.cpp
  src/glue/SessionHL.cpp
  src/query/interpret/eval.cpp
  src/query/interpret/eval.hpp
  src/query/interpreter.cpp
  src/query/interpreter.hpp
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  src/query/trigger.cpp
  src/query/trigger.hpp
  src/storage/v2/property_value.hpp
  src/utils/memory.cpp
  src/utils/memory.hpp
  src/utils/tag.hpp
  tests/benchmark/query/execution.cpp
  tests/benchmark/skip_list_vs_stl.cpp
  tests/e2e/memory/workloads.yaml
  tests/mgbench/runners.py
  tests/unit/property_value_v2.cpp
  tests/unit/utils_memory.cpp
Labels: memory, Docs - changelog only

#1816 Add RollUpApply operator support to edge type index rewrite.
  src/query/plan/rewrite/edge_type_index_lookup.hpp
Labels: feature, Docs unnecessary

#1791 Add behaviour of no updates if vertex is updated with same value
  src/flags/general.cpp
  src/flags/general.hpp
  src/memgraph.cpp
  src/query/frontend/stripped.cpp
  src/query/plan/operator.cpp
  src/storage/v2/config.hpp
  src/storage/v2/edge_accessor.cpp
  src/storage/v2/vertex_accessor.cpp
  src/utils/atomic_memory_block.hpp
  src/utils/on_scope_exit.hpp
  tests/e2e/CMakeLists.txt
  tests/e2e/concurrency/CMakeLists.txt
  tests/e2e/concurrency/common.py
  tests/e2e/concurrency/concurrency.py
  tests/e2e/concurrency/workloads.yaml
  tests/e2e/configuration/default_config.py
Labels: feature, Docs needed

#1825 Fix cargo not found when buidling in mgbuild container
  release/package/mgbuild.sh
Labels: infrastructure, Docs unnecessary

#1826 Make diff run on push to master again
  .github/workflows/diff.yaml
Labels: infrastructure, Docs unnecessary

#1739 Text search Phase 2 (expanded search capabilities)
  include/_mgp.hpp
  include/mg_procedure.h
  include/mgp.hpp
  libs/CMakeLists.txt
  query_modules/CMakeLists.txt
  query_modules/text_search_module.cpp
  src/query/db_accessor.hpp
  src/query/interpreter.cpp
  src/query/procedure/mg_procedure_impl.cpp
  src/storage/v2/CMakeLists.txt
  src/storage/v2/durability/durability.cpp
  src/storage/v2/durability/durability.hpp
  src/storage/v2/indices/text_index.cpp
  src/storage/v2/indices/text_index.hpp
  src/storage/v2/storage.cpp
  src/storage/v2/storage.hpp
  tests/e2e/text_search/common.py
  tests/e2e/text_search/test_text_search.py
  tests/e2e/text_search/test_text_search_disabled.py
Labels: experiment, Docs needed

#1820 Rename HA flags for cluster setup
  src/coordination/coordinator_state.cpp
  src/coordination/include/coordination/raft_state.hpp
  src/coordination/raft_state.cpp
  src/flags/replication.cpp
  src/flags/replication.hpp
  src/memgraph.cpp
  src/query/interpreter.cpp
  src/query/interpreter.hpp
  src/replication/state.cpp
  src/replication_handler/include/replication_handler/replication_handler.hpp
  src/storage/v2/config.hpp
  src/storage/v2/replication/replication_client.cpp
  tests/drivers/run_cluster.sh
  tests/e2e/configuration/default_config.py
  tests/e2e/high_availability/coord_cluster_registration.py
  tests/e2e/high_availability/disable_writing_on_main_after_restart.py
  tests/e2e/high_availability/distributed_coords.py
  tests/e2e/high_availability/manual_setting_replicas.py
  tests/e2e/high_availability/not_replicate_from_old_main.py
  tests/e2e/high_availability/single_coordinator.py
  tests/e2e/high_availability/workloads.yaml
Labels: feature, Docs needed

#1811 Fix timestamps saving on-disk
  src/storage/v2/disk/durable_metadata.cpp
  src/storage/v2/disk/durable_metadata.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  tests/unit/clearing_old_disk_data.cpp
Labels: on disk, Docs - changelog only

#1838 Fix and update mgbench
  tests/mgbench/benchmark.py
  tests/mgbench/graph_bench.py
  tests/mgbench/mg_ondisk_vs_neo4j_pokec.sh
  tests/mgbench/runners.py
  tests/mgbench/workloads/base.py
  tests/mgbench/workloads/disk_pokec.py
  tests/mgbench/workloads/importers/disk_importer_pokec.py
  tests/mgbench/workloads/pokec.py
Labels: benchmarking, Docs unnecessary

#1846 Fix jepsen nodes not starting up healthy
  tests/jepsen/run.sh
Labels: infrastructure, Docs unnecessary

#1819 HA: Add distributed locks
  src/coordination/coordinator_cluster_state.cpp
  src/coordination/coordinator_communication_config.cpp
  src/coordination/coordinator_instance.cpp
  src/coordination/coordinator_state_machine.cpp
  src/coordination/include/coordination/coordinator_communication_config.hpp
  src/coordination/include/coordination/coordinator_instance.hpp
  src/coordination/include/coordination/raft_state.hpp
  src/coordination/include/coordination/register_main_replica_coordinator_status.hpp
  src/coordination/include/coordination/replication_instance.hpp
  src/coordination/include/nuraft/coordinator_cluster_state.hpp
  src/coordination/include/nuraft/coordinator_state_machine.hpp
  src/coordination/include/nuraft/raft_log_action.hpp
  src/coordination/raft_state.cpp
  src/coordination/replication_instance.cpp
  src/query/interpreter.cpp
  src/replication/state.cpp
  src/utils/thread_pool.cpp
  tests/e2e/high_availability/coord_cluster_registration.py
  tests/e2e/high_availability/distributed_coords.py
  tests/unit/raft_log_serialization.cpp
Labels: feature, Docs needed

#1849 Fix CMake
  libs/CMakeLists.txt
Labels: bug

#1845 Bump googletest to 1.14
  libs/setup.sh
  tests/unit/bfs_fine_grained.cpp
  tests/unit/cypher_main_visitor.cpp
  tests/unit/storage_v2_durability_inmemory.cpp
  tests/unit/storage_v2_replication.cpp
  tests/unit/utils_settings.cpp
Labels: feature, Docs - changelog only

#1842 Forbid TSAN with Jemalloc
  CMakeLists.txt
Labels: bug, Docs unnecessary

#1736 Fix `valuetype` function on all data types
  src/query/interpret/awesome_memgraph_functions.cpp
  tests/e2e/awesome_functions/CMakeLists.txt
  tests/e2e/awesome_functions/property_size.py
  tests/e2e/awesome_functions/value_type.py
  tests/e2e/awesome_functions/workloads.yaml
Labels: bug, Docs needed

#1836 HA: Add force reset of cluster
  src/coordination/coordinator_client.cpp
  src/coordination/coordinator_cluster_state.cpp
  src/coordination/coordinator_instance.cpp
  src/coordination/coordinator_state_machine.cpp
  src/coordination/include/coordination/coordinator_client.hpp
  src/coordination/include/coordination/coordinator_instance.hpp
  src/coordination/include/coordination/raft_state.hpp
  src/coordination/include/coordination/register_main_replica_coordinator_status.hpp
  src/coordination/include/coordination/replication_instance.hpp
  src/coordination/include/nuraft/coordinator_cluster_state.hpp
  src/coordination/include/nuraft/coordinator_state_machine.hpp
  src/coordination/include/nuraft/raft_log_action.hpp
  src/coordination/raft_state.cpp
  src/coordination/replication_instance.cpp
  src/query/interpreter.cpp
  src/replication_coordination_glue/common.hpp
  src/replication_coordination_glue/role.hpp
  tests/drivers/run.sh
  tests/drivers/run_cluster.sh
  tests/e2e/high_availability/distributed_coords.py
Labels: feature, Docs needed

#1814 Modify package memgraph workflow to work in mgbuild containers
  .github/workflows/diff.yaml
  .github/workflows/package_memgraph.yaml
  .github/workflows/reusable_package.yaml
  environment/os/debian-12-arm.sh
  environment/os/debian-12.sh
  environment/os/fedora-38.sh
  environment/os/fedora-39.sh
  environment/os/run.sh
  environment/util.sh
  init
  libs/CMakeLists.txt
  libs/setup.sh
  licenses/third-party/tantivy/AUTHORS
  licenses/third-party/tantivy/LICENSE
  release/docker/package_docker
  release/docker/v4_deb.dockerfile
  release/docker/v5_deb.dockerfile
  release/package/amd-builders-v4.yml
  release/package/amd-builders-v5.yml
  release/package/amzn-2/Dockerfile
  release/package/arm-builders-v4.yml
  release/package/arm-builders-v5.yml
  release/package/centos-7/Dockerfile
  release/package/centos-9/Dockerfile
  release/package/debian-10/Dockerfile
  release/package/debian-11-arm/Dockerfile
  release/package/debian-11/Dockerfile
  release/package/debian-12-arm/Dockerfile
  release/package/debian-12/Dockerfile
  release/package/fedora-36/Dockerfile
  release/package/fedora-38/Dockerfile
  release/package/fedora-39/Dockerfile
  release/package/mgbuild.sh
  release/package/rocky-9.3/Dockerfile
  release/package/ubuntu-18.04/Dockerfile
  release/package/ubuntu-20.04/Dockerfile
  release/package/ubuntu-22.04-arm/Dockerfile
  release/package/ubuntu-22.04/Dockerfile
  release/rpm/rpmlintrc
  release/rpm/rpmlintrc_fedora
  tests/jepsen/run.sh
Labels: infrastructure, Docs needed

#1827 Implement execution part of one pattern comprehension in Return clause.
  src/query/interpret/eval.hpp
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  src/query/plan/preprocess.cpp
  src/query/plan/preprocess.hpp
  src/query/plan/rule_based_planner.cpp
  src/query/plan/rule_based_planner.hpp
  src/utils/event_counter.cpp
  tests/gql_behave/tests/memgraph_V1/features/list_operations.feature
Labels: feature, Docs needed

#1813 Add install_deps.sh to automate dependency installation
  environment/os/install_deps.sh
Labels: infrastructure, Docs unnecessary

#1808 Fetch edge by edge id
  config/flags.yaml
  src/dbms/inmemory/replication_handlers.cpp
  src/flags/general.cpp
  src/flags/general.hpp
  src/memgraph.cpp
  src/mg_import_csv.cpp
  src/query/db_accessor.hpp
  src/query/plan/hint_provider.hpp
  src/query/plan/operator.cpp
  src/query/plan/operator.hpp
  src/query/plan/operator_type_info.cpp
  src/query/plan/pretty_print.cpp
  src/query/plan/pretty_print.hpp
  src/query/plan/rewrite/edge_type_index_lookup.hpp
  src/storage/v2/config.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/durability/durability.cpp
  src/storage/v2/durability/durability.hpp
  src/storage/v2/durability/snapshot.cpp
  src/storage/v2/durability/snapshot.hpp
  src/storage/v2/edge.hpp
  src/storage/v2/edge_accessor.cpp
  src/storage/v2/edge_accessor.hpp
  src/storage/v2/edge_info_helpers.hpp
  src/storage/v2/inmemory/edge_type_index.cpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/storage.hpp
  src/utils/event_counter.cpp
  tests/e2e/configuration/default_config.py
  tests/unit/query_plan.cpp
  tests/unit/query_plan_checker.hpp
  tests/unit/storage_v2_durability_inmemory.cpp
Labels: Docs needed

#1847 Adapt release workflow to work with mgbuild based CI
  .github/workflows/release_build_test.yaml
  .github/workflows/release_debian10.yaml
  .github/workflows/release_ubuntu2004.yaml
  .github/workflows/reusable_release_tests.yaml
  .github/workflows/stress_test_large.yaml
  release/package/mgbuild.sh
Labels: infrastructure, Docs unnecessary

#1872 Fix compile issue under mgcxx > tantivy > zstd-sys
  libs/setup.sh
Labels: Docs unnecessary

#1863 Update MEL license
  licenses/MEL.txt
Labels: Docs unnecessary

#1876 Package and upload RC builds for ARM
  .github/workflows/release_build_test.yaml
Labels: infrastructure, Docs unnecessary

#1871 Fix OnScopeExit to allow exceptions
  src/utils/on_scope_exit.hpp
Labels: bug, Docs - changelog only

#1815 Fix on disk write-write conflicts
  src/storage/v2/disk/storage.cpp
  tests/e2e/CMakeLists.txt
  tests/e2e/concurrent_write/CMakeLists.txt
  tests/e2e/concurrent_write/workloads.yaml
  tests/e2e/concurrent_write/write.py
Labels: bug, on disk, Docs unnecessary

#1867 Fix saving coordinators in CoordinatorClusterState
  src/coordination/coordinator_cluster_state.cpp
  src/coordination/coordinator_instance.cpp
  src/coordination/coordinator_state_machine.cpp
  src/coordination/include/coordination/coordinator_instance.hpp
  src/coordination/include/coordination/instance_status.hpp
  src/coordination/include/coordination/raft_state.hpp
  src/coordination/include/nuraft/coordinator_cluster_state.hpp
  src/coordination/include/nuraft/coordinator_state_machine.hpp
  src/coordination/raft_state.cpp
  tests/e2e/high_availability/coord_cluster_registration.py
  tests/e2e/high_availability/distributed_coords.py
  tests/unit/coordinator_cluster_state.cpp
  tests/unit/coordinator_instance.cpp
  tests/unit/high_availability_cluster_setup.cpp
  tests/unit/raft_state.cpp
Labels: bug, Docs unnecessary

#1883 Update BSL license change date for 2.15.1
  licenses/BSL.txt
Labels: Docs unnecessary

#1882 Update release docker workflow to work with toolchain v5
  .github/workflows/release_docker.yaml
Labels: infrastructure, Docs unnecessary

#1885 Add debian-11-arm build with toolchain v5
  .github/workflows/package_memgraph.yaml
  release/package/arm-builders-v5.yml
  release/package/mgbuild.sh
Labels: infrastructure, Docs - changelog only

#1886 Freeze mgcxx deps properly
  libs/setup.sh
Labels: Docs unnecessary
