Repository memgraph/memgraph, pull requests merged in 2024-05, with the labels that each got.

#1866 Add the zoned datetime data type to Memgraph
  src/audit/log.cpp
  src/communication/bolt/v1/codes.hpp
  src/communication/bolt/v1/decoder/decoder.hpp
  src/communication/bolt/v1/encoder/base_encoder.hpp
  src/communication/bolt/v1/value.cpp
  src/communication/bolt/v1/value.hpp
  src/glue/communication.cpp
  src/query/common.hpp
  src/query/dump.cpp
  src/query/frontend/ast/pretty_print.cpp
  src/query/interpret/awesome_memgraph_functions.cpp
  src/query/interpret/eval.hpp
  src/query/plan/operator.cpp
  src/query/procedure/mg_procedure_impl.cpp
  src/query/serialization/property_value.cpp
  src/query/typed_value.cpp
  src/query/typed_value.hpp
  src/storage/v2/durability/marker.hpp
  src/storage/v2/durability/serialization.cpp
  src/storage/v2/durability/wal.cpp
  src/storage/v2/indices/text_index.cpp
  src/storage/v2/inmemory/label_property_index.cpp
  src/storage/v2/property_store.cpp
  src/storage/v2/property_value.hpp
  src/storage/v2/replication/slk.cpp
  src/storage/v2/temporal.cpp
  src/storage/v2/temporal.hpp
  src/utils/temporal.cpp
  src/utils/temporal.hpp
  tests/e2e/awesome_functions/property_size.py
  tests/e2e/awesome_functions/value_type.py
  tests/e2e/temporal_types/roundtrip.cpp
  tests/gql_behave/tests/memgraph_V1/features/match.feature
  tests/gql_behave/tests/memgraph_V1_on_disk/features/match.feature
  tests/unit/bolt_decoder.cpp
  tests/unit/bolt_encoder.cpp
  tests/unit/bolt_testdata.hpp
  tests/unit/formatters.hpp
  tests/unit/property_value_v2.cpp
  tests/unit/query_dump.cpp
  tests/unit/query_expression_evaluator.cpp
  tests/unit/query_pretty_print.cpp
  tests/unit/query_serialization_property_value.cpp
  tests/unit/slk_advanced.cpp
  tests/unit/storage_v2_decoder_encoder.cpp
  tests/unit/storage_v2_indices.cpp
  tests/unit/storage_v2_property_store.cpp
  tests/unit/typed_value.cpp
  tests/unit/utils_temporal.cpp
Labels: feature, Ready for review, Docs needed, CI -build=debug -test=core, CI -build=debug -test=integration, CI -build=release -test=core, CI -build=release -test=e2e

#1997 Add more verbose logging in coordinator
  src/coordination/coordinator_instance.cpp
  src/coordination/raft_state.cpp
Labels: bug, Docs unnecessary, CI -build=coverage -test=core

#1998 Remove the libc function inline clang tidy check
  .clang-tidy
Labels: tests, Docs unnecessary

#1992 Add support for ubuntu 24.04
  .github/workflows/package_memgraph.yaml
  .github/workflows/release_build_test.yaml
  .github/workflows/stress_test_large.yaml
  environment/os/ubuntu-24.04-arm.sh
  environment/os/ubuntu-24.04.sh
  release/package/amd-builders-v5.yml
  release/package/arm-builders-v5.yml
  release/package/mgbuild.sh
  release/package/ubuntu-24.04-arm/Dockerfile
  release/package/ubuntu-24.04/Dockerfile
Labels: infrastructure, Docs unnecessary

#2003 Bugfix: Replica now handles skipped transactions
  src/communication/buffer.cpp
  src/communication/buffer.hpp
  src/rpc/protocol.cpp
  src/storage/v2/inmemory/storage.cpp
Labels: bug, memory, Docs - changelog only

#2004 Add dns resolution on endpoint parsing
  src/communication/http/server.hpp
  src/communication/websocket/server.hpp
  src/coordination/coordinator_handlers.cpp
  src/coordination/coordinator_server.cpp
  src/coordination/include/coordination/coordinator_handlers.hpp
  src/coordination/include/coordination/coordinator_slk.hpp
  src/coordination/raft_state.cpp
  src/io/network/addrinfo.cpp
  src/io/network/endpoint.cpp
  src/io/network/endpoint.hpp
  src/io/network/socket.cpp
  src/query/interpreter.cpp
  src/replication/replication_client.cpp
  src/replication/replication_server.cpp
  src/replication/state.cpp
  src/replication_handler/replication_handler.cpp
  tests/concurrent/network_read_hang.cpp
  tests/concurrent/network_server.cpp
  tests/concurrent/network_session_leak.cpp
  tests/e2e/replication/common.hpp
  tests/e2e/replication/indices.cpp
  tests/unit/network_endpoint.cpp
  tests/unit/storage_v2_replication.cpp
Labels: feature, Docs - changelog only

#2013 Improve testing output of `SHOW INSTANCES`
  tests/e2e/high_availability/distributed_coords.py
  tests/e2e/mg_utils.py
Labels: bug, Docs unnecessary, CI -build=release -test=e2e

#2015 Fix setup_diff_workflow
  tools/diff_setup.py
Labels: bug, Docs unnecessary

#2016 Fix: Running show replicas on REPLICA in e2e test
  tests/e2e/high_availability/distributed_coords.py
Labels: tests, Docs unnecessary, CI -build=release -test=e2e

#2020 Add push to github input to package memgraph workflow
  .github/workflows/package_memgraph.yaml
  .github/workflows/reusable_package.yaml
  release/package/mgbuild.sh
Labels: Docs unnecessary

#1976 Extend min() and max() to zoned datetime
  src/query/plan/operator.cpp
  tests/gql_behave/tests/memgraph_V1/features/aggregations.feature
  tests/gql_behave/tests/memgraph_V1_on_disk/features/aggregations.feature
Labels: feature, Docs needed, CI -build=release -test=core

#2028 Fix missing break statement in type conversion
  src/query/procedure/mg_procedure_impl.cpp
Labels: bug, Docs unnecessary

#1970 small_vector used in Vertex, 24B reduction
  src/glue/auth_checker.cpp
  src/storage/v2/CMakeLists.txt
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/indices/text_index.cpp
  src/storage/v2/indices/text_index.hpp
  src/storage/v2/property_store.cpp
  src/storage/v2/property_store.hpp
  src/storage/v2/small_vector.hpp
  src/storage/v2/storage.cpp
  src/storage/v2/vertex.hpp
  src/storage/v2/vertex_accessor.cpp
  src/storage/v2/vertex_accessor.hpp
  src/storage/v2/vertex_info_cache.cpp
  src/storage/v2/vertex_info_cache.hpp
  src/storage/v2/vertex_info_helpers.hpp
  src/utils/rocksdb_serialization.hpp
  src/utils/small_vector.hpp
  tests/unit/CMakeLists.txt
  tests/unit/query_procedures_mgp_graph.cpp
  tests/unit/small_vector.cpp
Labels: feature, Docs - changelog only, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=debug -test=core, CI -build=debug -test=integration, CI -build=release -test=core, CI -build=release -test=e2e, CI -build=release -test=benchmark

#2027 Use aws cli to sync with S3
  .github/workflows/reusable_package.yaml
  .github/workflows/upload_to_s3.yaml
Labels: Docs unnecessary

#2014 Create releasable artifacts from rc
  .github/workflows/release_build_test.yaml
Labels: Docs unnecessary

#1953 Remove misc-include-cleaner from Clang-Tidy
  .clang-tidy
Labels: feature, Docs unnecessary

#2033 Fix release build test workflow syntax
  .github/workflows/release_build_test.yaml
Labels: Docs unnecessary

#1935 Count number of hops
  src/query/context.hpp
  src/query/interpreter.cpp
  src/query/plan/operator.cpp
  tests/e2e/CMakeLists.txt
  tests/e2e/hops_limit/CMakeLists.txt
  tests/e2e/hops_limit/count_hops.py
  tests/e2e/hops_limit/workloads.yaml
Labels: Docs unnecessary, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=debug -test=core, CI -build=release -test=core, CI -build=release -test=e2e

#2034 Harden the build, more warnings/asserts
  CMakeLists.txt
  src/communication/bolt/v1/decoder/chunked_decoder_buffer.hpp
  src/communication/websocket/auth.hpp
  src/coordination/coordinator_instance.cpp
  src/query/plan/operator.hpp
  src/query/query_user.hpp
  src/query/stream.hpp
  src/storage/v2/inmemory/edge_type_index.cpp
  src/storage/v2/inmemory/edge_type_index.hpp
  src/utils/visitor.hpp
Labels: Docs unnecessary, CI -build=debug -test=core, CI -build=debug -test=integration

#2035 Fix: ipv6 resolution in dns test
  tests/unit/network_endpoint.cpp
Labels: tests, Docs unnecessary, CI -build=debug -test=core

#2031 Set --replication-restore-state-at-startup to true by default
  src/flags/replication.cpp
  tests/e2e/configuration/default_config.py
Labels: feature, Docs needed, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=jepsen -test=core, CI -build=debug -test=core, CI -build=debug -test=integration, CI -build=release -test=core, CI -build=release -test=e2e, CI -build=release -test=stress, CI -build=release -test=benchmark

#2017 Improve Memgraph's startup process
  src/communication/http/listener.hpp
  src/communication/http/server.hpp
  src/communication/v2/listener.hpp
  src/communication/v2/server.hpp
  src/communication/websocket/listener.cpp
  src/communication/websocket/listener.hpp
  src/communication/websocket/server.cpp
  src/communication/websocket/server.hpp
  src/memgraph.cpp
  tests/e2e/interactive_mg_runner.py
  tests/e2e/memgraph.py
  tests/e2e/runner.py
Labels: bug, Docs needed, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=jepsen -test=core, CI -build=debug -test=core, CI -build=debug -test=integration, CI -build=release -test=core, CI -build=release -test=e2e, CI -build=release -test=stress, CI -build=release -test=benchmark

#2018 Fix: MVCC design on replica and replica stream isolation
  src/dbms/inmemory/replication_handlers.cpp
  src/dbms/inmemory/replication_handlers.hpp
  src/replication_handler/replication_handler.cpp
  src/storage/v2/CMakeLists.txt
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/replication/replication_client.cpp
  src/storage/v2/replication/replication_client.hpp
  src/storage/v2/replication/replication_storage_state.cpp
  src/storage/v2/replication/replication_storage_state.hpp
  tests/CMakeLists.txt
Labels: bug, Docs - changelog only

#2040 Fix NuRaft launcher race condition when creating raft server
  src/coordination/coordinator_instance.cpp
  src/coordination/include/coordination/coordinator_instance.hpp
  src/coordination/include/coordination/raft_state.hpp
  src/coordination/raft_state.cpp
Labels: bug, Docs - changelog only, CI -build=jepsen -test=core, CI -build=release -test=core, CI -build=release -test=e2e

#2041 Add grammar to support create and show enums queries.
  src/query/exceptions.hpp
  src/query/frontend/ast/ast.cpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/ast_visitor.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/frontend/opencypher/grammar/MemgraphCypherLexer.g4
  src/query/frontend/semantic/required_privileges.cpp
  src/query/frontend/stripped_lexer_constants.hpp
  src/query/interpreter.cpp
  src/utils/typeinfo.hpp
  tests/gql_behave/tests/memgraph_V1/features/memgraph.feature
  tests/unit/cypher_main_visitor.cpp
Labels: feature, Docs unnecessary, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=debug -test=core, CI -build=debug -test=integration, CI -build=release -test=core, CI -build=release -test=e2e

#2038 Fix replication server's startup when registering replication instance
  src/coordination/coordinator_handlers.cpp
Labels: bug, Docs unnecessary

#2032 Create user if not exists
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/frontend/opencypher/grammar/MemgraphCypherLexer.g4
  src/query/interpreter.cpp
  tests/e2e/CMakeLists.txt
  tests/e2e/authentication_if_not_exists/CMakeLists.txt
  tests/e2e/authentication_if_not_exists/authentication_if_not_exists.py
  tests/e2e/authentication_if_not_exists/common.py
  tests/e2e/authentication_if_not_exists/workloads.yaml
  tests/unit/query_common.hpp
  tests/unit/query_required_privileges.cpp
Labels: feature, Docs needed

#2047 Add support for RelWithDebInfo docker images
  .github/workflows/reusable_package.yaml
  release/docker/package_docker
  release/docker/v5_deb_relwithdebinfo.dockerfile
  release/package/mgbuild.sh
Labels: Docs unnecessary

#2019 Fix: Wrong assert in recovery process test
  tests/unit/storage_v2_replication.cpp
Labels: tests, Docs unnecessary, CI -build=release -test=core

#2058 Fix image tag for RelWithDebInfo images
  release/docker/package_docker
  release/package/mgbuild.sh
Labels: Docs unnecessary

#2059 Fix arm packaging by running as root
  release/package/mgbuild.sh
Labels: Docs unnecessary

#2043 Improve removal of obsolete indexes
  CMakeLists.txt
  libs/setup.sh
  src/storage/v2/indices/indices.cpp
  src/storage/v2/indices/indices.hpp
  src/storage/v2/inmemory/label_index.cpp
  src/storage/v2/inmemory/label_index.hpp
  src/storage/v2/inmemory/label_property_index.cpp
  src/storage/v2/inmemory/label_property_index.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/inmemory/unique_constraints.cpp
  src/storage/v2/inmemory/unique_constraints.hpp
  tests/e2e/garbage_collection/gc_periodic.py
Labels: Docs - changelog only, customer, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=debug -test=core, CI -build=release -test=core, CI -build=release -test=e2e, CI -build=release -test=benchmark

#2063 Update BSL license change date for v2.17.0
  licenses/BSL.txt
Labels: Docs unnecessary

#2051 Improve HA networking
  src/communication/http/server.hpp
  src/communication/websocket/server.hpp
  src/coordination/coordinator_instance.cpp
  src/coordination/coordinator_server.cpp
  src/coordination/coordinator_state_manager.cpp
  src/coordination/include/coordination/coordinator_handlers.hpp
  src/coordination/include/coordination/coordinator_slk.hpp
  src/coordination/include/coordination/raft_state.hpp
  src/coordination/raft_state.cpp
  src/io/network/addrinfo.cpp
  src/io/network/endpoint.cpp
  src/io/network/endpoint.hpp
  src/io/network/socket.cpp
  src/query/interpreter.cpp
  src/query/replication_query_handler.hpp
  src/replication/replication_server.cpp
  src/replication/state.cpp
  src/replication_handler/replication_handler.cpp
  tests/e2e/replication/common.hpp
  tests/e2e/replication/indices.cpp
  tests/unit/network_endpoint.cpp
  tests/unit/storage_v2_replication.cpp
Labels: feature, Docs - changelog only, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=jepsen -test=core, CI -build=debug -test=core, CI -build=debug -test=integration, CI -build=release -test=core, CI -build=release -test=e2e, CI -build=release -test=stress

#2062 Refresh Jepsen cluster -> Memgraph build
  .github/workflows/diff_jepsen.yaml
Labels: feature, infrastructure, Docs unnecessary, CI -build=jepsen -test=core

#2064 Try to clone Jepsen optimistically from mgdeps-cache
  tests/jepsen/run.sh
Labels: feature, infrastructure, Docs unnecessary, CI -build=jepsen -test=core

#2012 Add HA bank test
  tests/jepsen/README.md
  tests/jepsen/run.sh
  tests/jepsen/src/jepsen/memgraph/bank.clj
  tests/jepsen/src/jepsen/memgraph/client.clj
  tests/jepsen/src/jepsen/memgraph/core.clj
  tests/jepsen/src/jepsen/memgraph/habank.clj
  tests/jepsen/src/jepsen/memgraph/haclient.clj
  tests/jepsen/src/jepsen/memgraph/haempty.clj
  tests/jepsen/src/jepsen/memgraph/support.clj
  tests/jepsen/src/jepsen/memgraph/utils.clj
  tests/jepsen/test/jepsen/memgraph/memgraph_test.clj
Labels: feature, tests, Docs unnecessary, CI -build=jepsen -test=core

#2060 Lazy evaluation of replication DNS
  src/coordination/coordinator_handlers.cpp
  src/coordination/include/coordination/coordinator_communication_config.hpp
  src/coordination/include/coordination/coordinator_handlers.hpp
  src/io/network/endpoint.cpp
  src/io/network/endpoint.hpp
  src/kvstore/kvstore.hpp
  src/query/interpreter.cpp
  src/replication/include/replication/config.hpp
  src/replication/include/replication/status.hpp
  src/replication/replication_client.cpp
  src/replication/replication_server.cpp
  src/replication/state.cpp
  src/replication/status.cpp
  tests/unit/replication_persistence_helper.cpp
  tests/unit/storage_v2_replication.cpp
Labels: feature, Docs - changelog only

#2074 Jepsen improvements
  tests/jepsen/run.sh
  tests/jepsen/src/jepsen/memgraph/bank.clj
  tests/jepsen/src/jepsen/memgraph/client.clj
  tests/jepsen/src/jepsen/memgraph/core.clj
  tests/jepsen/src/jepsen/memgraph/habank.clj
  tests/jepsen/src/jepsen/memgraph/haclient.clj
  tests/jepsen/src/jepsen/memgraph/haempty.clj
  tests/jepsen/src/jepsen/memgraph/support.clj
  tests/jepsen/src/jepsen/memgraph/utils.clj
  tests/jepsen/test/jepsen/memgraph/memgraph_test.clj
Labels: feature, tests, Docs unnecessary, CI -build=jepsen -test=core
