Repository memgraph/memgraph, pull requests merged in 2025-08, with the labels that each got.

#3159 Add math.round to mappings
  config/mappings.json
Labels: feature, Docs unnecessary

#3162 Fix incorrect GraphQL mappings
  config/mappings.json
Labels: bug, Docs - changelog only

#3074 Add Conan build
  .gitignore
  CMakeLists.txt
  conan-profiles/Debug.arm64
  conan-profiles/Debug.x86_64
  conan-profiles/RelWithDebInfo.arm64
  conan-profiles/RelWithDebInfo.x86_64
  conan-profiles/Release.arm64
  conan-profiles/Release.x86_64
  conanfile.py
  libs/CMakeLists.txt
  libs/setup.sh
  memgraph_template_profile
  src/coordination/CMakeLists.txt
  src/csv/CMakeLists.txt
  src/csv/parsing.cpp
  src/flags/CMakeLists.txt
  src/license/CMakeLists.txt
  src/query/CMakeLists.txt
  src/query/frontend/opencypher/parser.hpp
  src/requests/CMakeLists.txt
  src/requests/requests.cpp
  src/storage/v2/CMakeLists.txt
  src/utils/CMakeLists.txt
  tests/benchmark/CMakeLists.txt
  tests/e2e/monitoring_server/CMakeLists.txt
  tests/manual/CMakeLists.txt
  tests/manual/antlr_parser.cpp
  tests/manual/antlr_tree_pretty_print.cpp
  tests/unit/CMakeLists.txt
  tests/unit/cypher_main_visitor.cpp
  toolchain.cmake
Labels: dependencies

#3142 Remove ReplicationEpoch from replication::MainRole
  src/auth/auth.cpp
  src/auth/rpc.cpp
  src/auth/rpc.hpp
  src/coordination/data_instance_management_server_handlers.cpp
  src/dbms/dbms_handler.cpp
  src/dbms/rpc.cpp
  src/dbms/rpc.hpp
  src/replication/include/replication/state.hpp
  src/replication/include/replication/status.hpp
  src/replication/state.cpp
  src/replication/status.cpp
  src/replication_handler/replication_handler.cpp
  src/storage/v2/durability/durability.cpp
  src/system/include/system/action.hpp
  src/system/include/system/transaction.hpp
  tests/unit/replication_persistence_helper.cpp
Labels: Capability - high-availability, Docs unnecessary, Code improvements

#3168 Fix daily coverage build test
  .github/workflows/reusable_release_tests.yaml
Labels: bug, infrastructure, Docs unnecessary

#3127 AllShortestPaths improvements v2
  src/query/plan/operator.cpp
  src/query/typed_value.cpp
  tests/gql_behave/tests/memgraph_V1/features/memgraph_allshortest.feature
  tests/gql_behave/tests/memgraph_V1/graphs/graph_wsp_edge_case_2.cypher
Labels: feature, Docs - changelog only

#3166 Return snapshot path
  src/dbms/inmemory/storage_helper.hpp
  src/query/interpreter.cpp
  src/storage/v2/durability/snapshot.cpp
  src/storage/v2/durability/snapshot.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  tests/e2e/durability/snapshot_recovery.py
  tests/unit/CMakeLists.txt
  tests/unit/storage_v2_create_snapshot.cpp
  tests/unit/storage_v2_durability_inmemory.cpp
Labels: feature, Docs needed, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=debug -test=integration, CI -build=release -test=e2e

#3155 Text index on subset of properties
  src/dbms/inmemory/replication_handlers.cpp
  src/query/db_accessor.hpp
  src/query/dump.cpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/opencypher/grammar/MemgraphCypher.g4
  src/query/interpreter.cpp
  src/storage/v2/CMakeLists.txt
  src/storage/v2/disk/durable_metadata.cpp
  src/storage/v2/disk/durable_metadata.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/durability/durability.cpp
  src/storage/v2/durability/metadata.hpp
  src/storage/v2/durability/snapshot.cpp
  src/storage/v2/durability/version.hpp
  src/storage/v2/durability/wal.cpp
  src/storage/v2/durability/wal.hpp
  src/storage/v2/indices/indices.cpp
  src/storage/v2/indices/indices.hpp
  src/storage/v2/indices/text_index.cpp
  src/storage/v2/indices/text_index.hpp
  src/storage/v2/indices/text_index_utils.cpp
  src/storage/v2/indices/text_index_utils.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/metadata_delta.hpp
  src/storage/v2/storage.cpp
  src/storage/v2/storage.hpp
  src/storage/v2/transaction.hpp
  src/storage/v2/vertex_accessor.cpp
  src/storage/v2/vertex_accessor.hpp
  tests/e2e/durability/durability_with_text_index.py
  tests/e2e/replication/replicate_text_index.py
  tests/gql_behave/tests/memgraph_V1/features/text_search.feature
  tests/integration/durability/memgraph_server_context.py
  tests/integration/durability/tests/v29/test_all/create_dataset.cypher
  tests/integration/durability/tests/v29/test_all/expected_snapshot.cypher
  tests/integration/durability/tests/v29/test_all/expected_wal.cypher
  tests/integration/durability/tests/v29/test_all/snapshot.bin
  tests/integration/durability/tests/v29/test_all/wal.bin
  tests/integration/durability/tests/v29/test_constraints/create_dataset.cypher
  tests/integration/durability/tests/v29/test_constraints/expected_snapshot.cypher
  tests/integration/durability/tests/v29/test_constraints/expected_wal.cypher
  tests/integration/durability/tests/v29/test_constraints/snapshot.bin
  tests/integration/durability/tests/v29/test_constraints/wal.bin
  tests/integration/durability/tests/v29/test_edges/create_dataset.cypher
  tests/integration/durability/tests/v29/test_edges/expected_snapshot.cypher
  tests/integration/durability/tests/v29/test_edges/expected_wal.cypher
  tests/integration/durability/tests/v29/test_edges/snapshot.bin
  tests/integration/durability/tests/v29/test_edges/wal.bin
  tests/integration/durability/tests/v29/test_vertices/create_dataset.cypher
  tests/integration/durability/tests/v29/test_vertices/expected_snapshot.cypher
  tests/integration/durability/tests/v29/test_vertices/expected_wal.cypher
  tests/integration/durability/tests/v29/test_vertices/snapshot.bin
  tests/integration/durability/tests/v29/test_vertices/wal.bin
  tests/unit/query_dump.cpp
  tests/unit/storage_v2_durability_inmemory.cpp
  tests/unit/storage_v2_wal_file.cpp
  tests/unit/text_index.cpp
Labels: feature, Docs needed, CI -build=coverage -test=core, CI -build=release -test=core, CI -build=release -test=e2e

#3147 Remove optional UUID from replica's role
  src/coordination/data_instance_management_server_handlers.cpp
  src/query/interpreter.cpp
  src/query/replication_query_handler.hpp
  src/replication/include/replication/state.hpp
  src/replication/include/replication/status.hpp
  src/replication/state.cpp
  src/replication/status.cpp
  src/replication_handler/include/replication_handler/replication_handler.hpp
  src/replication_handler/replication_handler.cpp
  tests/unit/replication_persistence_helper.cpp
  tests/unit/storage_v2_replication.cpp
Labels: Docs unnecessary, Code improvements, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=jepsen -test=core, CI -build=debug -test=core, CI -build=debug -test=integration, CI -build=release -test=core, CI -build=release -test=e2e

#3174 Improve handling of epochs during data recovery
  src/coordination/coordinator_instance.cpp
  src/dbms/inmemory/replication_handlers.cpp
  src/replication/include/replication/state.hpp
  src/replication_handler/replication_handler.cpp
  src/storage/v2/durability/durability.cpp
  src/storage/v2/replication/replication_client.cpp
  src/storage/v2/replication/rpc.hpp
Labels: bug, Docs - changelog only, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=jepsen -test=core, CI -build=debug -test=core, CI -build=debug -test=integration, CI -build=release -test=core, CI -build=release -test=e2e, CI -build=release -test=stress

#3183 Update default durability version
  src/replication/include/replication/status.hpp
Labels: bug, Docs unnecessary

#3186 Bugfix: ToTree uses wrong ptr checks and might segfault
  query_modules/convert.c
  src/query/procedure/mg_procedure_impl.cpp
  tests/query_modules/to_tree_test/test_exclude_filters/test.yml
  tests/query_modules/to_tree_test/test_nested/test.yml
Labels: bug, Docs unnecessary, CI -build=release -test=query_modules

#3171 Start using the latest mgcxx version
  CMakeLists.txt
  libs/CMakeLists.txt
  libs/setup.sh
  src/query/db_accessor.hpp
  src/query/interpreter.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/indices/text_index.cpp
  src/storage/v2/indices/text_index.hpp
  src/storage/v2/indices/text_index_utils.cpp
  src/storage/v2/indices/text_index_utils.hpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/storage.hpp
  tests/e2e/durability/durability_with_text_index.py
  tests/e2e/replication/replicate_text_index.py
  tests/e2e/schema_info/schema_info.py
  tests/gql_behave/tests/memgraph_V1/features/text_search.feature
  tools/github/clang-tidy/run-clang-tidy.py
Labels: Docs needed, enhancement, CI -build=coverage -test=core

#3193 Concurrent index replication
  src/dbms/database.hpp
  src/dbms/inmemory/replication_handlers.cpp
  src/query/db_accessor.hpp
  src/query/interpreter.cpp
  src/query/interpreter.hpp
  src/query/plan/vertex_count_cache.hpp
  src/query/serialization/property_value.cpp
  src/query/serialization/property_value.hpp
  src/query/trigger.cpp
  src/storage/v2/CMakeLists.txt
  src/storage/v2/access_type.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/durability/wal.cpp
  src/storage/v2/durability/wal.hpp
  src/storage/v2/fmt.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/replication/replication_client.cpp
  src/storage/v2/replication/replication_client.hpp
  src/storage/v2/replication/replication_transaction.hpp
  src/storage/v2/storage.cpp
  src/storage/v2/storage.hpp
  src/storage/v2/ttl.cpp
  tests/e2e/high_availability/ttl.py
  tests/integration/durability/tests/v30/test_all/snapshot.bin
  tests/integration/durability/tests/v30/test_all/wal.bin
  tests/integration/durability/tests/v30/test_constraints/snapshot.bin
  tests/integration/durability/tests/v30/test_constraints/wal.bin
  tests/integration/durability/tests/v30/test_edges/snapshot.bin
  tests/integration/durability/tests/v30/test_edges/wal.bin
  tests/integration/durability/tests/v30/test_vertices/snapshot.bin
  tests/integration/durability/tests/v30/test_vertices/wal.bin
  tests/unit/cpp_api.cpp
  tests/unit/storage_test_utils.cpp
  tests/unit/storage_v2_acc.cpp
  tests/unit/storage_v2_durability_inmemory.cpp
  tests/unit/storage_v2_get_info.cpp
  tests/unit/storage_v2_indices.cpp
  tests/unit/storage_v2_replication.cpp
  tests/unit/storage_v2_wal_file.cpp
Labels: feature, Docs unnecessary

#3196 Use Python `uv` to install tests dependencies
  .github/workflows/daily_benchmark.yaml
  .github/workflows/diff_community.yaml
  .github/workflows/diff_coverage.yaml
  .github/workflows/diff_debug.yaml
  .github/workflows/diff_release.yaml
  .github/workflows/package_memgraph.yaml
  .github/workflows/reusable_package.yaml
  .github/workflows/reusable_release_tests.yaml
  init
  init-test
  release/package/mgbuild.sh
  tests/e2e/sso/test_sso.py
  tests/setup.sh
Labels: infrastructure, Docs unnecessary, Code improvements, CI -build=release -test=e2e

#3213 Release 3.5 fixes
  .github/actions/docker-login/action.yml
  .github/workflows/benchmark_on_pokec_large.yaml
  .github/workflows/build_rc.yml
  .github/workflows/daily_benchmark.yaml
  .github/workflows/diff_community.yaml
  .github/workflows/diff_coverage.yaml
  .github/workflows/diff_debug.yaml
  .github/workflows/diff_jepsen.yaml
  .github/workflows/diff_malloc.yaml
  .github/workflows/diff_release.yaml
  .github/workflows/release_mgbench_client.yaml
  .github/workflows/reusable_package.yaml
  .github/workflows/reusable_release_tests.yaml
  .github/workflows/reusable_stress_jepsen.yaml
  src/py/py.hpp
Labels: infrastructure, Docs unnecessary

#3215 Add option to build without tests for packaging
  .github/workflows/reusable_package.yaml
  release/package/mgbuild.sh
Labels: infrastructure, Docs unnecessary

#3206 Add python3.12-venv inside Memgraph's build image
  release/docker/v6_deb.dockerfile
  release/docker/v6_deb_relwithdebinfo.dockerfile
Labels: infrastructure, Docs - changelog only, Frequency - Daily, Code improvements

#3182 feat: Speed up demote process upon failover
  src/coordination/coordinator_instance.cpp
  src/coordination/coordinator_rpc.cpp
  src/coordination/data_instance_management_server_handlers.cpp
  src/coordination/include/coordination/coordinator_rpc.hpp
  src/coordination/include/coordination/replication_instance_client.hpp
  src/query/replication_query_handler.hpp
  src/replication/include/replication/state.hpp
  src/replication/state.cpp
  src/replication_handler/include/replication_handler/replication_handler.hpp
  src/replication_handler/replication_handler.cpp
Labels: feature, Docs - changelog only, CI -build=community -test=core, CI -build=jepsen -test=core, CI -build=debug -test=core, CI -build=release -test=core, CI -build=release -test=e2e
