Repository memgraph/memgraph, pull requests merged in 2025-01, with the labels that each got.

#2576 Reduce frequency of AsyncTimer GC
  src/storage/v2/inmemory/storage.cpp
  src/utils/async_timer.cpp
  src/utils/async_timer.hpp
Labels: bug, Docs - changelog only, CI -build=release -test=benchmark

#2566 Fix delta release on unique constraint error
  src/storage/v2/inmemory/storage.cpp
  tests/e2e/constraints/constraints_validation.py
Labels: bug, Docs - changelog only, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=jepsen -test=core, CI -build=debug -test=core, CI -build=debug -test=integration, CI -build=release -test=core, CI -build=release -test=e2e, CI -build=release -test=stress, CI -build=release -test=benchmark

#2529 Snapshot unit test robustness fix
  tests/unit/utils_scheduler.cpp
Labels: Docs unnecessary, CI -build=coverage -test=core

#2584 Fix cleanup for e2e tests
  tests/e2e/runner.py
Labels: infrastructure, Docs unnecessary, CI -build=release -test=e2e

#2590 Revert "Add timeouts to RPC messages"
  src/communication/client.cpp
  src/communication/client.hpp
  src/coordination/coordinator_instance_client.cpp
  src/coordination/include/coordination/coordinator_instance_client.hpp
  src/coordination/replication_instance_client.cpp
  src/io/network/socket.cpp
  src/io/network/socket.hpp
  src/rpc/client.cpp
  src/rpc/client.hpp
  src/storage/v2/replication/replication_client.cpp
  src/utils/typeinfo.hpp
  tests/jepsen/src/memgraph/high_availability/bank/test.clj
  tests/unit/CMakeLists.txt
  tests/unit/rpc_messages.hpp
  tests/unit/rpc_timeouts.cpp
Labels: bug, Docs unnecessary

#2588 Pin storage accessors when iterating edge indices
  src/storage/v2/indices/indices_utils.hpp
  src/storage/v2/inmemory/edge_type_index.cpp
  src/storage/v2/inmemory/edge_type_index.hpp
  src/storage/v2/inmemory/edge_type_property_index.cpp
  src/storage/v2/inmemory/edge_type_property_index.hpp
  src/storage/v2/inmemory/storage.hpp
Labels: bug, Docs - changelog only, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=jepsen -test=core, CI -build=debug -test=core, CI -build=debug -test=integration, CI -build=release -test=core, CI -build=release -test=e2e

#2592 Revert "Fix cleanup for e2e tests"
  tests/e2e/runner.py
Labels: bug, Docs unnecessary

#2577 Bugfix: Deadlock when reading replication state during commit
  src/dbms/dbms_handler.cpp
  src/replication_handler/include/replication_handler/replication_handler.hpp
  src/replication_handler/replication_handler.cpp
  src/rpc/client.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/replication/replication_client.cpp
  src/storage/v2/replication/replication_client.hpp
  src/storage/v2/replication/replication_storage_state.cpp
  src/storage/v2/replication/replication_storage_state.hpp
  src/storage/v2/replication/replication_transaction.hpp
  src/storage/v2/storage.hpp
  src/utils/synchronized.hpp
Labels: bug, Docs - changelog only

#2587 Add Cypher `toStringOrNull` function
  src/query/interpret/awesome_memgraph_functions.cpp
  tests/unit/query_expression_evaluator.cpp
Labels: feature, Docs needed

#2596 Fix edge type index cleanup on Abort
  src/storage/v2/inmemory/edge_type_index.cpp
  src/storage/v2/inmemory/edge_type_index.hpp
  src/storage/v2/inmemory/edge_type_property_index.cpp
  src/storage/v2/inmemory/edge_type_property_index.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/storage_error.hpp
  tests/e2e/edge_indices/edge_indices.py
  tests/unit/storage_v2_indices.cpp
Labels: bug, Docs - changelog only

#2609 Remove unused ReplicasInfo method
  src/query/replication_query_handler.hpp
  src/replication/include/replication/replication_client.hpp
  src/replication_handler/include/replication_handler/replication_handler.hpp
  src/replication_handler/include/replication_handler/system_replication.hpp
  src/replication_handler/replication_handler.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/replication/replication_storage_state.cpp
  src/storage/v2/replication/replication_storage_state.hpp
  src/storage/v2/storage.hpp
  tests/unit/storage_v2_replication.cpp
Labels: bug, Docs unnecessary, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=release -test=core

#2603 Always use durable storage in high availability for coordinator data
  src/coordination/coordinator_instance_client.cpp
  src/coordination/coordinator_log_store.cpp
  src/coordination/coordinator_state_machine.cpp
  src/coordination/coordinator_state_manager.cpp
  src/coordination/include/coordination/coordinator_communication_config.hpp
  src/coordination/include/coordination/coordinator_instance_client.hpp
  src/coordination/include/coordination/coordinator_log_store.hpp
  src/coordination/include/coordination/coordinator_state_machine.hpp
  src/coordination/include/coordination/coordinator_state_manager.hpp
  src/coordination/raft_state.cpp
  src/coordination/utils.cpp
  src/flags/coord_flag_env_handler.cpp
  src/flags/coord_flag_env_handler.hpp
  src/flags/coordination.cpp
  src/flags/coordination.hpp
  src/memgraph.cpp
  tests/e2e/configuration/default_config.py
  tests/e2e/high_availability/distributed_coords.py
  tests/unit/coordinator_env_flag_handler.cpp
  tests/unit/coordinator_instance.cpp
  tests/unit/coordinator_raft_state.cpp
  tests/unit/coordinator_state_machine.cpp
  tests/unit/coordinator_state_manager.cpp
  tests/unit/coordinator_utils.cpp
Labels: bug, Docs needed, breaking, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=jepsen -test=core, CI -build=debug -test=core, CI -build=debug -test=integration, CI -build=release -test=core, CI -build=release -test=e2e, CI -build=release -test=stress, CI -build=release -test=benchmark

#2589 Perf improvement for Abort
  src/storage/v2/edge_ref.hpp
  src/storage/v2/inmemory/storage.cpp
  src/utils/CMakeLists.txt
  src/utils/skip_list.cpp
  src/utils/skip_list.hpp
  src/utils/small_vector.hpp
  tests/unit/small_vector.cpp
Labels: bug, Docs - changelog only

#2613 chore: Remove unused lcp/Lisp files
  src/lisp/CMakeLists.txt
  src/lisp/clone.lisp
  src/lisp/code-gen.lisp
  src/lisp/compile-lcp
  src/lisp/debug.lisp
  src/lisp/lcp.asd
  src/lisp/lcp.lisp
  src/lisp/names.lisp
  src/lisp/package.lisp
  src/lisp/reader.lisp
  src/lisp/slk.lisp
  src/lisp/test.lisp
  src/lisp/types.lisp
  src/lisp/util.lisp
  src/query/frontend/ast/ast.lcp
  src/query/frontend/semantic/symbol.lcp
  src/query/plan/operator.lcp
  src/storage/v2/replication/rpc.lcp
  tests/unit/test_lcp.lisp
  tools/emacs-lcp/README.md
  tools/emacs-lcp/lcp-mode.el
  tools/lcp
  tools/vim-lcp/README.md
  tools/vim-lcp/ftdetect/lcp.vim
  tools/vim-lcp/ftplugin/lcp.vim
  tools/vim-lcp/syntax/lcp.vim
Labels: Docs unnecessary, Code improvements, CI -build=release -test=core

#2573 Query modules testing infrastructure
  .github/workflows/diff_release.yaml
  .github/workflows/reusable_release_tests.yaml
  include/mg_procedure.h
  include/mgp.py
  query_modules/CMakeLists.txt
  query_modules/vector_search_module.cpp
  release/package/mgbuild.sh
  src/flags/experimental.hpp
  src/query/frontend/ast/ast_visitor.hpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/stripped_lexer_constants.hpp
  src/query/procedure/mg_procedure_impl.cpp
  src/query/procedure/module.cpp
  src/query/procedure/py_module.cpp
  src/storage/v2/durability/marker.hpp
  src/storage/v2/durability/serialization.cpp
  src/storage/v2/durability/storage_global_operation.hpp
  src/storage/v2/durability/version.hpp
  src/storage/v2/indices/indices.cpp
  src/utils/event_counter.cpp
  tests/e2e/CMakeLists.txt
  tests/e2e/enterprise_query_modules/CMakeLists.txt
  tests/e2e/enterprise_query_modules/common.py
  tests/e2e/enterprise_query_modules/query_modules/CMakeLists.txt
  tests/e2e/enterprise_query_modules/query_modules/utils.py
  tests/e2e/enterprise_query_modules/test_enterprise.py
  tests/e2e/enterprise_query_modules/workloads.yaml
  tests/query_modules/README.md
  tests/query_modules/example_online_test/example_1_online/input.cyp
  tests/query_modules/example_online_test/example_1_online/test.yml
  tests/query_modules/example_test/example_1/input.cyp
  tests/query_modules/example_test/example_1/test.yml
  tests/query_modules/example_test/example_2/input.cyp
  tests/query_modules/example_test/example_2/test.yml
  tests/query_modules/pytest.ini
  tests/query_modules/runner.py
  tests/unit/storage_v2_decoder_encoder.cpp
Labels: infrastructure, Docs needed, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=jepsen -test=core, CI -build=debug -test=core, CI -build=debug -test=integration, CI -build=release -test=core, CI -build=release -test=e2e, CI -build=release -test=stress, CI -build=release -test=benchmark

#2561 Change query modules allocator
  include/mgp.hpp
  query_modules/convert.cpp
  query_modules/text_search_module.cpp
  query_modules/vector_search_module.cpp
  src/query/plan/operator.cpp
  src/query/procedure/mg_procedure_impl.cpp
Labels: feature, Docs needed, breaking

#2604 Add text index to drop graph
  src/slk/serialization.hpp
  src/storage/v2/durability/durability.cpp
  src/storage/v2/indices/indices.cpp
  src/storage/v2/indices/text_index.cpp
  src/storage/v2/indices/text_index.hpp
  src/storage/v2/storage.cpp
  tests/e2e/drop_graph/drop_graph.py
  tests/e2e/drop_graph/workloads.yaml
Labels: bug, Docs - changelog only, CI -build=coverage -test=core, CI -build=release -test=core, CI -build=release -test=e2e

#2597 Feat/add exponentiation operator
  src/query/frontend/ast/ast.cpp
  src/query/frontend/ast/ast.hpp
  src/query/frontend/ast/ast_visitor.hpp
  src/query/frontend/ast/cypher_main_visitor.cpp
  src/query/frontend/ast/cypher_main_visitor.hpp
  src/query/frontend/ast/pretty_print.cpp
  src/query/frontend/semantic/symbol_generator.hpp
  src/query/interpret/eval.hpp
  src/query/plan/preprocess.hpp
  src/query/plan/rewrite/enum.hpp
  src/query/plan/rule_based_planner.cpp
  src/query/typed_value.cpp
  src/query/typed_value.hpp
  src/utils/typeinfo.hpp
  tests/unit/cypher_main_visitor.cpp
  tests/unit/query_expression_evaluator.cpp
Labels: feature, Docs - changelog only, CI -build=release -test=core

#2598 Bugfix: PeriodicCommit crashes if commit generates replication error
  src/query/plan/operator.cpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/replication/replication_client.cpp
Labels: bug, Docs - changelog only, CI -build=coverage -test=core, CI -build=debug -test=integration, CI -build=release -test=e2e

#2625 Correct async timer memory order
  src/utils/async_timer.cpp
  tests/unit/utils_async_timer.cpp
Labels: bug, Docs - changelog only

#2610 Improve cleanup of e2e tests
  tests/e2e/runner.py
Labels: infrastructure, Docs unnecessary, CI -build=release -test=e2e

#2618 Patch rocksdb to tolerate exceptions
  libs/CMakeLists.txt
  libs/rocksdb8.1.1.patch
Labels: bug, Docs - changelog only

#2628 Upgrade python dependencies
  init
  src/auth/reference_modules/requirements.txt
Labels: Docs - changelog only, CI -build=release -test=core, CI -build=release -test=e2e

#2617 Improving replication recovery process
  src/dbms/inmemory/replication_handlers.cpp
  src/memgraph.cpp
  src/query/plan/hint_provider.hpp
  src/storage/v2/inmemory/replication/recovery.cpp
  src/storage/v2/inmemory/replication/recovery.hpp
  src/storage/v2/replication/replication_client.cpp
  src/storage/v2/replication/rpc.cpp
  src/storage/v2/replication/rpc.hpp
  tests/e2e/memgraph.py
  tests/e2e/replication/workloads.yaml
  tests/unit/storage_v2_replication.cpp
  tests/unit/utils_async_timer.cpp
Labels: bug, Docs - changelog only

#2632 Performance fix: Using poll only if timeout is needed
  src/communication/buffer.cpp
  src/communication/buffer.hpp
  src/communication/client.cpp
  src/communication/client.hpp
Labels: Docs unnecessary, CI -build=release -test=benchmark

#2633 Protect the iterator lifetime with shared_ptr
  include/_mgp.hpp
  include/mgp.hpp
Labels: bug, Docs unnecessary

#2634 Bugfix: Recursive allocations inside query memory tracker
  src/memory/CMakeLists.txt
  src/memory/query_memory_control.cpp
  src/memory/query_memory_control.hpp
  src/utils/skip_list.hpp
  tests/unit/CMakeLists.txt
  tests/unit/utils_query_memory_tracker.cpp
Labels: bug, Docs - changelog only, CI -build=coverage -test=core, CI -build=debug -test=core, CI -build=debug -test=integration, CI -build=release -test=e2e, CI -build=release -test=stress, CI -build=release -test=query_modules

#2637 Fix query modules CI jobs
  .github/workflows/check_flakiness.yaml
  .github/workflows/diff.yaml
  tools/diff_setup.py
Labels: infrastructure, Docs unnecessary, CI -build=release -test=query_modules

#2643 Fix memory leak in query modules
  include/mgp.hpp
  query_modules/convert.cpp
Labels: bug, Docs - changelog only

#2638 Avoid reloading dgl and numpy modules; remove deprecated python C-API function
  src/memgraph.cpp
  src/query/procedure/module.cpp
Labels: bug, Docs - changelog only, CI -build=debug -test=core, CI -build=release -test=e2e, CI -build=release -test=query_modules

#2640 Function calls made cheaper
  src/query/interpret/eval.hpp
  src/query/typed_value.cpp
  src/query/typed_value.hpp
Labels: performance optimization, Docs - changelog only, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=debug -test=core, CI -build=debug -test=integration, CI -build=release -test=core, CI -build=release -test=e2e, CI -build=release -test=benchmark, CI -build=release -test=query_modules

#2647 Increase Jepsen stress test to 10h
  .github/workflows/stress_jepsen.yaml
Labels: Docs unnecessary, enhancement

#2650 Add reserve to list in C & C++ APIs
  include/_mgp.hpp
  include/mg_procedure.h
  include/mgp.hpp
  query_modules/convert.cpp
  src/query/procedure/mg_procedure_impl.cpp
Labels: feature, Docs - changelog only

#2655 Fix copy and move assignment operators in TypedValue
  src/query/typed_value.cpp
  tests/query_modules/runner.py
Labels: bug, Docs unnecessary, CI -build=release -test=core, CI -build=release -test=e2e, CI -build=release -test=query_modules
