Repository memgraph/memgraph, pull requests merged in 2025-05, with the labels that each got.

#2931 User-configurable option to failover only to SYNC replica
  src/coordination/coordinator_cluster_state.cpp
  src/coordination/coordinator_instance.cpp
  src/coordination/coordinator_state_machine.cpp
  src/coordination/include/coordination/constants.hpp
  src/coordination/include/coordination/coordinator_cluster_state.hpp
  src/coordination/include/coordination/coordinator_communication_config.hpp
  src/coordination/include/coordination/coordinator_state_machine.hpp
  src/coordination/include/coordination/raft_state.hpp
  src/coordination/raft_state.cpp
  src/replication_coordination_glue/role.hpp
  tests/e2e/high_availability/distributed_coords.py
  tests/unit/coordinator_cluster_state.cpp
  tests/unit/coordinator_log_store.cpp
Labels: feature, Capability - high-availability, Docs needed, CI -build=coverage -test=core, CI -build=release -test=core, CI -build=release -test=e2e

#2940 Increase runner timeouts
  .github/workflows/reusable_release_tests.yaml
Labels: infrastructure, Docs unnecessary

#2938 Bugfix: Impersonate user misalignment between interpreter and session
  src/communication/bolt/client.cpp
  src/communication/bolt/client.hpp
  src/glue/SessionHL.cpp
  src/glue/SessionHL.hpp
  src/query/frontend/semantic/required_privileges.cpp
  src/query/interpreter.cpp
  src/query/interpreter.hpp
  tests/drivers/python/v5_8/impersonate_user.py
  tests/integration/audit/runner.py
  tests/integration/audit/tester.cpp
Labels: bug, Docs - changelog only, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=debug -test=integration, CI -build=release -test=core, CI -build=release -test=e2e

#2937 Bugfix: Improve the usage of RMW pattern in HA coordinators
  src/coordination/coordinator_instance.cpp
  src/coordination/coordinator_log_store.cpp
  src/coordination/coordinator_state_machine.cpp
  src/coordination/include/coordination/coordinator_log_store.hpp
  src/coordination/include/coordination/coordinator_state_machine.hpp
Labels: bug, Capability - high-availability, Docs - changelog only, CI -build=coverage -test=core, CI -build=release -test=core, CI -build=release -test=e2e

#2950 Bugfix: PageSlabMemoryResource large allocation return wrong address
  src/utils/allocator/page_slab_memory_resource.hpp
Labels: bug, Docs - changelog only, CI -build=coverage -test=core, CI -build=release -test=e2e, CI -build=release -test=stress

#2947 Set the UID of memgraph user in Docker container to match that of MAGE
  release/docker/v6_deb.dockerfile
  release/docker/v6_deb_relwithdebinfo.dockerfile
Labels: infrastructure, Docs - changelog only

#2941 Improve read-write benchmark test
  tests/e2e/replication/read_write_benchmark.cpp
  tests/e2e/replication/workloads.yaml
Labels: Docs unnecessary, CI -build=release -test=e2e

#2952 Added missing debug builds
  .github/workflows/promote_rc_release.yml
  .github/workflows/release_build_test.yaml
Labels: infrastructure, Docs - changelog only

#2957 Fix Jepsen Workflow
  .github/workflows/stress_jepsen_ha.yaml
Labels: infrastructure

#2956 Release 3.2.1 fixes
  .github/workflows/promote_rc_release.yml
Labels: infrastructure, Docs unnecessary

#2949 Add timeout on socket connect
  src/io/network/socket.cpp
  src/io/network/socket.hpp
  src/rpc/client.hpp
  tests/jepsen/src/memgraph/core.clj
Labels: feature, Capability - high-availability, Docs needed, CI -build=coverage -test=core, CI -build=release -test=core, CI -build=release -test=e2e, CI -build=release -test=benchmark

#2959 Add fuzzer for property store
  CMakeLists.txt
  src/CMakeLists.txt
  src/csv/CMakeLists.txt
  src/dbms/CMakeLists.txt
  src/http_handlers/CMakeLists.txt
  src/query/CMakeLists.txt
  src/storage/v2/CMakeLists.txt
  src/storage/v2/fuzz/CMakeLists.txt
  src/storage/v2/fuzz/fuzz_property_store.cpp
  src/storage/v2/fuzz/helpers/read_parse.hpp
  src/storage/v2/property_store.cpp
  tests/benchmark/CMakeLists.txt
  tests/concurrent/CMakeLists.txt
  tests/e2e/garbage_collection/CMakeLists.txt
  tests/integration/telemetry/CMakeLists.txt
  tests/property_based/CMakeLists.txt
  tests/unit/CMakeLists.txt
Labels: Docs unnecessary

#2948 Align HA nomenclature. Introduce abstract failure detector
  src/coordination/coordinator_instance_connector.cpp
  src/coordination/include/coordination/replication_instance_client.hpp
  src/coordination/include/coordination/replication_instance_connector.hpp
  src/coordination/replication_instance_client.cpp
  src/coordination/replication_instance_connector.cpp
  src/replication/include/replication/replication_client.hpp
  src/replication_coordination_glue/handler.hpp
  src/replication_handler/include/replication_handler/replication_handler.hpp
  src/rpc/client.hpp
  src/rpc/protocol.cpp
  src/rpc/protocol.hpp
  src/rpc/server.hpp
  src/storage/v2/inmemory/replication/recovery.hpp
  src/storage/v2/replication/replication_client.cpp
  tests/e2e/high_availability/rpc_comm.cpp
  tests/unit/replication_rpc_progress.cpp
  tests/unit/rpc.cpp
  tests/unit/rpc_in_progress.cpp
  tests/unit/rpc_timeouts.cpp
  tests/unit/snapshot_rpc_progress.cpp
Labels: Capability - high-availability, Docs unnecessary, Code improvements

#2961 Add support for replication benchmark
  tests/e2e/interactive_mg_runner.py
  tests/mgbench/benchmark.py
  tests/mgbench/benchmark_context.py
  tests/mgbench/runners.py
  tests/mgbench/setup.py
Labels: benchmarking, Capability - high-availability, Docs unnecessary, CI -build=release -test=benchmark

#2965 Add StartTxnReplication, FinalizeTxnReplication and DataFailover metrics for better HA monitoring
  src/coordination/coordinator_instance.cpp
  src/storage/v2/replication/replication_client.cpp
  src/storage/v2/replication/replication_transaction.hpp
  src/utils/event_histogram.cpp
  tests/e2e/show_metrics/show_metrics.py
Labels: feature, Capability - high-availability, Docs - changelog only

#2967 Bugfix: fails to create empty user while using auth modules
  src/glue/auth_checker.cpp
  src/glue/auth_checker.hpp
  src/memgraph.cpp
  src/query/auth_checker.hpp
  src/query/stream/streams.cpp
  src/query/time_to_live/time_to_live.cpp
  tests/e2e/sso/test_sso.py
  tests/unit/query_trigger.cpp
Labels: bug, Docs - changelog only, customer, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=debug -test=integration, CI -build=release -test=e2e

#2970 Bugfix: utils::Scheduler start_time drift
  src/utils/scheduler.cpp
  tests/unit/utils_scheduler.cpp
Labels: bug, CI -build=coverage -test=core, CI -build=release -test=e2e

#2963 Use std::pmr::memory_resource
  CMakeLists.txt
  src/query/frame_change.hpp
  src/query/graph.cpp
  src/query/graph.hpp
  src/query/interpret/awesome_memgraph_functions.cpp
  src/query/interpret/eval.hpp
  src/query/interpret/frame.hpp
  src/query/path.hpp
  src/query/plan/operator.cpp
  src/query/plan/rewrite/index_lookup.hpp
  src/query/procedure/mg_procedure_impl.cpp
  src/query/procedure/mg_procedure_impl.hpp
  src/query/procedure/py_module.cpp
  src/query/typed_value.cpp
  src/query/typed_value.hpp
  src/utils/memory.cpp
  src/utils/memory.hpp
  src/utils/skip_list.hpp
  tests/unit/query_expression_evaluator.cpp
  tests/unit/typed_value.cpp
  tests/unit/utils_memory.cpp
Labels: Docs unnecessary, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=jepsen -test=core, CI -build=debug -test=core, CI -build=debug -test=integration, CI -build=release -test=core, CI -build=release -test=e2e, CI -build=release -test=benchmark, CI -build=release -test=query_modules

#2969 Add support for MT benchmark
  tests/mgbench/benchmark.py
  tests/mgbench/benchmark_context.py
  tests/mgbench/client.cpp
  tests/mgbench/runners.py
  tests/mgbench/workloads/pokec.py
Labels: feature, benchmarking, Capability - high-availability, Docs unnecessary, CI -build=release -test=benchmark

#2973 Bugfix: Fix replication state machine when recovery and commit tasks are interleaved
  src/storage/v2/replication/replication_client.cpp
Labels: bug, Capability - high-availability, Docs - changelog only, CI -build=release -test=core, CI -build=release -test=e2e

#2979 Make bulletproof snapshot recovery e2e test
  tests/e2e/durability/snapshot_recovery.py
Labels: tests, Docs unnecessary, Code improvements, CI -build=release -test=e2e

#2964 Protect special member functions of a concurrent data structure representing cluster state
  src/coordination/coordinator_cluster_state.cpp
Labels: bug, Docs unnecessary, CI -build=release -test=core, CI -build=release -test=e2e

#2985 Update workflows to re-tag mgbench images
  .github/workflows/release_mgbench_client.yaml
  .github/workflows/reusable_build_mgbench_client.yml
Labels: infrastructure, Docs unnecessary

#2835 Add bolt+routing connection to HA create Jepsen test
  .github/workflows/reusable_stress_jepsen.yaml
  src/coordination/coordinator_instance.cpp
  src/coordination/raft_state.cpp
  tests/jepsen/src/memgraph/high_availability/create/nemesis.clj
  tests/jepsen/src/memgraph/high_availability/create/test.clj
  tests/jepsen/src/memgraph/high_availability/utils.clj
  tests/jepsen/src/memgraph/query.clj
  tests/jepsen/src/memgraph/utils.clj
Labels: tests, Capability - high-availability, Docs unnecessary

#2986 Reduce running time to 3h for MT Jepsen test
  .github/workflows/reusable_stress_jepsen.yaml
Labels: Docs unnecessary, Code improvements

#2984 Bugfix: Fix deadlock when using ASYNC replicas by skipping recovery tasks if lock cannot be obtained
  src/rpc/client.hpp
  src/rpc/exceptions.hpp
  src/storage/v2/inmemory/replication/recovery.hpp
  src/storage/v2/replication/replication_client.cpp
Labels: bug, Capability - high-availability, Docs - changelog only, CI -build=release -test=core, CI -build=release -test=e2e

#2976 Bugfix: Unreleased deltas when using HA
  src/dbms/inmemory/replication_handlers.cpp
  src/replication_handler/replication_handler.cpp
  src/storage/v2/commit_log.cpp
  src/storage/v2/commit_log.hpp
  src/storage/v2/inmemory/storage.cpp
  tests/unit/commit_log_v2.cpp
Labels: bug, Capability - high-availability, Docs - changelog only, CI -build=coverage -test=core, CI -build=release -test=core, CI -build=release -test=e2e

#2988 Add ability to build single mgbench image and create artifact
  .github/workflows/release_mgbench_client.yaml
  .github/workflows/reusable_build_mgbench_client.yml
Labels: infrastructure, Docs unnecessary

#2987 Bugfix: mgbench using external vendor
  tests/mgbench/runners.py
Labels: tests, benchmarking, Docs unnecessary, Code improvements

#2990 Fix license path
  licenses/third-party/libstdc++/COPYING
Labels: infrastructure, Docs unnecessary

#2997 Unpin tzdata
  environment/os/debian-11.sh
  environment/os/ubuntu-22.04.sh
  environment/os/ubuntu-24.04.sh
  release/docker/v5_deb.dockerfile
  release/docker/v5_deb_relwithdebinfo.dockerfile
  release/docker/v6_deb.dockerfile
  release/docker/v6_deb_relwithdebinfo.dockerfile
Labels: infrastructure, Docs unnecessary

#2992 Use std::source_location for MG_ASSERT
  src/utils/logging.cpp
  src/utils/logging.hpp
  src/utils/thread_pool.hpp
Labels: Docs unnecessary, Code improvements, CI -build=coverage -test=core, CI -build=release -test=core, CI -build=release -test=benchmark

#2995 Bugfix: Parallel snapshot fails if sendfile can't send the whole file at once
  src/storage/v2/durability/snapshot.cpp
Labels: bug, Docs needed, CI -build=coverage -test=core, CI -build=debug -test=integration, CI -build=release -test=e2e

#3008 Bugfix: Snapshot fails to mark whole range of committed timestamps
  src/dbms/inmemory/replication_handlers.cpp
  src/storage/v2/inmemory/storage.cpp
  tests/e2e/durability/snapshot_recovery.py
Labels: bug, Docs unnecessary, CI -build=coverage -test=core, CI -build=debug -test=integration, CI -build=release -test=e2e
