Repository memgraph/memgraph, pull requests merged in 2025-07, with the labels that each got.

#3071 Use deltas' timestamp instead of wal.to_timestamp
  src/dbms/inmemory/replication_handlers.cpp
  src/replication_handler/replication_handler.cpp
  src/storage/v2/durability/durability.cpp
  src/storage/v2/durability/wal.cpp
  src/storage/v2/replication/replication_client.cpp
  tests/jepsen/src/memgraph/high_availability/create/test.clj
Labels: Capability - high-availability, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=jepsen -test=core, CI -build=debug -test=core, CI -build=release -test=core, CI -build=release -test=e2e, CI -build=release -test=stress

#3078 Fix HA upgrade 3.2.1 -> 3.3
  src/coordination/coordinator_cluster_state.cpp
  src/coordination/coordinator_state_machine.cpp
  src/coordination/include/coordination/constants.hpp
  tests/unit/coordinator_cluster_state.cpp
Labels: bug, Docs - changelog only, CI -build=release -test=core, CI -build=release -test=e2e

#3083 Improve ISO 8601 date conversions in GraphQL compatibility
  query_modules/date.py
  tests/e2e/graphql/CMakeLists.txt
  tests/e2e/graphql/graphql_library_config/CMakeLists.txt
  tests/e2e/graphql/graphql_library_config/types.js
  tests/e2e/graphql/graphql_types.py
  tests/e2e/graphql/workloads.yaml
  tests/query_modules/date_test/convert_format/test.yml
Labels: bug, Docs unnecessary, CI -build=community -test=core, CI -build=release -test=core, CI -build=release -test=e2e, CI -build=release -test=stress, CI -build=release -test=benchmark, CI -build=release -test=query_modules

#3064 Non blocking edge type index creation
  ADRs/004_concurrent_index_creation.md
  src/dbms/inmemory/replication_handlers.cpp
  src/query/db_accessor.hpp
  src/query/interpreter.cpp
  src/query/plan/rewrite/edge_index_lookup.hpp
  src/query/plan/used_index_checker.cpp
  src/query/plan/vertex_count_cache.hpp
  src/storage/v2/CMakeLists.txt
  src/storage/v2/common_function_signatures.hpp
  src/storage/v2/disk/edge_type_index.cpp
  src/storage/v2/disk/edge_type_index.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/durability/durability.cpp
  src/storage/v2/durability/snapshot.cpp
  src/storage/v2/indices/active_indices.hpp
  src/storage/v2/indices/edge_type_index.cpp
  src/storage/v2/indices/edge_type_index.hpp
  src/storage/v2/indices/errors.hpp
  src/storage/v2/indices/indices.cpp
  src/storage/v2/indices/indices.hpp
  src/storage/v2/indices/indices_utils.hpp
  src/storage/v2/indices/label_property_index.hpp
  src/storage/v2/inmemory/edge_property_index.cpp
  src/storage/v2/inmemory/edge_property_index.hpp
  src/storage/v2/inmemory/edge_type_index.cpp
  src/storage/v2/inmemory/edge_type_index.hpp
  src/storage/v2/inmemory/edge_type_property_index.cpp
  src/storage/v2/inmemory/edge_type_property_index.hpp
  src/storage/v2/inmemory/label_index.cpp
  src/storage/v2/inmemory/label_property_index.cpp
  src/storage/v2/inmemory/label_property_index.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/storage.hpp
  src/storage/v2/vertex.hpp
  src/storage/v2/vertex_info_helpers.hpp
  src/utils/event_counter.cpp
  tests/e2e/show_metrics/show_metrics.py
  tests/manual/interactive_planning.cpp
  tests/unit/query_plan_checker.hpp
  tests/unit/snapshot_rpc_progress.cpp
  tests/unit/storage_v2_durability_inmemory.cpp
  tests/unit/storage_v2_indices.cpp
  tests/unit/storage_v2_wal_file.cpp
Labels: feature, Docs needed

#3073 Non blocking label index creation
  src/query/db_accessor.hpp
  src/query/interpreter.cpp
  src/query/plan/rewrite/index_lookup.hpp
  src/query/plan/vertex_count_cache.hpp
  src/storage/v2/CMakeLists.txt
  src/storage/v2/disk/edge_import_mode_cache.cpp
  src/storage/v2/disk/label_index.cpp
  src/storage/v2/disk/label_index.hpp
  src/storage/v2/disk/label_property_index.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/durability/durability.cpp
  src/storage/v2/durability/snapshot.cpp
  src/storage/v2/indices/active_indices.hpp
  src/storage/v2/indices/edge_type_index.hpp
  src/storage/v2/indices/indices.cpp
  src/storage/v2/indices/indices_utils.hpp
  src/storage/v2/indices/label_index.hpp
  src/storage/v2/indices/label_property_index.cpp
  src/storage/v2/indices/label_property_index.hpp
  src/storage/v2/inmemory/edge_type_index.cpp
  src/storage/v2/inmemory/label_index.cpp
  src/storage/v2/inmemory/label_index.hpp
  src/storage/v2/inmemory/label_property_index.cpp
  src/storage/v2/inmemory/label_property_index.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/storage.hpp
  src/storage/v2/vertex_accessor.cpp
  tests/e2e/concurrency/concurrency.py
  tests/manual/interactive_planning.cpp
  tests/unit/cpp_api.cpp
  tests/unit/query_plan_checker.hpp
  tests/unit/snapshot_rpc_progress.cpp
  tests/unit/storage_v2_durability_inmemory.cpp
  tests/unit/storage_v2_get_info.cpp
  tests/unit/storage_v2_indices.cpp
  tests/unit/storage_v2_wal_file.cpp
Labels: feature, Docs needed

#3091 Non blocking edge type property and global property index
  src/query/db_accessor.hpp
  src/query/interpreter.cpp
  src/query/plan/rewrite/edge_index_lookup.hpp
  src/query/plan/used_index_checker.cpp
  src/query/plan/vertex_count_cache.hpp
  src/storage/v2/CMakeLists.txt
  src/storage/v2/disk/edge_property_index.cpp
  src/storage/v2/disk/edge_property_index.hpp
  src/storage/v2/disk/edge_type_index.cpp
  src/storage/v2/disk/edge_type_index.hpp
  src/storage/v2/disk/edge_type_property_index.cpp
  src/storage/v2/disk/edge_type_property_index.hpp
  src/storage/v2/disk/storage.cpp
  src/storage/v2/disk/storage.hpp
  src/storage/v2/durability/durability.cpp
  src/storage/v2/durability/snapshot.cpp
  src/storage/v2/indices/active_indices.hpp
  src/storage/v2/indices/edge_property_index.cpp
  src/storage/v2/indices/edge_property_index.hpp
  src/storage/v2/indices/edge_type_index.hpp
  src/storage/v2/indices/edge_type_property_index.cpp
  src/storage/v2/indices/edge_type_property_index.hpp
  src/storage/v2/indices/indices.cpp
  src/storage/v2/indices/indices.hpp
  src/storage/v2/inmemory/edge_property_index.cpp
  src/storage/v2/inmemory/edge_property_index.hpp
  src/storage/v2/inmemory/edge_type_index.cpp
  src/storage/v2/inmemory/edge_type_index.hpp
  src/storage/v2/inmemory/edge_type_property_index.cpp
  src/storage/v2/inmemory/edge_type_property_index.hpp
  src/storage/v2/inmemory/label_index.cpp
  src/storage/v2/inmemory/label_index.hpp
  src/storage/v2/inmemory/label_property_index.cpp
  src/storage/v2/inmemory/label_property_index.hpp
  src/storage/v2/inmemory/storage.cpp
  src/storage/v2/inmemory/storage.hpp
  src/storage/v2/property_value.hpp
  src/storage/v2/storage.hpp
  src/storage/v2/vertex_info_helpers.hpp
  src/utils/event_counter.cpp
  tests/e2e/schema_info/schema_info.py
  tests/e2e/show_metrics/show_metrics.py
  tests/manual/interactive_planning.cpp
  tests/unit/CMakeLists.txt
  tests/unit/query_dump.cpp
  tests/unit/query_plan_checker.hpp
  tests/unit/snapshot_rpc_progress.cpp
  tests/unit/storage_v2_durability_inmemory.cpp
  tests/unit/storage_v2_indices.cpp
  tests/unit/storage_v2_wal_file.cpp
Labels: feature, Docs needed

#3101 Premature exit from reading WAL info
  src/storage/v2/durability/wal.cpp
Labels: Capability - high-availability, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=jepsen -test=core, CI -build=debug -test=core, CI -build=release -test=core, CI -build=release -test=e2e

#3111 Add database uuid in show storage info
  src/query/interpreter.cpp
  tests/e2e/configuration/storage_info.py
Labels: feature, Docs needed, customer, CI -build=release -test=e2e

#3116 Fix WAL chain by comparing ldt
  src/storage/v2/durability/durability.cpp
  src/storage/v2/durability/snapshot.cpp
Labels: CI -build=debug -test=core, CI -build=release -test=core, CI -build=release -test=e2e

#3119 Fix AllShortestPaths operator
  src/query/plan/operator.cpp
  src/query/typed_value.cpp
  src/query/vertex_accessor.hpp
  src/utils/visitor.hpp
  tests/gql_behave/tests/memgraph_V1/features/memgraph_allshortest.feature
  tests/gql_behave/tests/memgraph_V1/graphs/graph_wsp_edge_case.cypher
Labels: bug, Docs - changelog only

#3128 Added mappings for new apoc functions
  config/mappings.json
Labels: Docs unnecessary, CI -build=release -test=query_modules

#3132 Fix Jepsen Workflows
  .github/workflows/reusable_release_tests.yaml
  .github/workflows/reusable_stress_jepsen.yaml
Labels: bug, infrastructure, Docs unnecessary

#3134 Bugfix: Don't abort rpc client for async replica which doesn't own the stream
  src/storage/v2/replication/replication_transaction.cpp
Labels: bug, Capability - high-availability, Docs unnecessary, CI -build=release -test=e2e, jepsen

#3144 Bugfix: SSO users missing from SHOW ACTIVE USERS INFO results
  src/glue/SessionHL.cpp
  tests/e2e/sso/dummy_sso_module.py
  tests/e2e/sso/test_sso.py
Labels: bug, Docs - changelog only, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=debug -test=integration, CI -build=release -test=e2e

#3151 Reduce docker image size
  release/docker/v6_deb.dockerfile
  release/docker/v6_deb_relwithdebinfo.dockerfile
Labels: infrastructure, Docs - changelog only

#3152 Add missing apoc mappings
  config/mappings.json
Labels: bug, Docs - changelog only, CI -build=release -test=core, CI -build=release -test=e2e

#3154 Fix unwind checking symbols in all scopes to checking in current scope
  src/query/frontend/semantic/symbol_generator.cpp
  tests/gql_behave/tests/memgraph_V1/features/subqueries.feature
Labels: bug, CI -build=community -test=core, CI -build=coverage -test=core, CI -build=jepsen -test=core, CI -build=debug -test=core, CI -build=release -test=core, CI -build=release -test=e2e
